### ISSUE TITLE
[AdminBundle] Character counter for input fields not properly aligned

### ISSUE THREAD

**Issue by dbeerten** [Kunstmaan/KunstmaanBundlesCMS#1004]
The counter is not properly aligned with the input.

Screenshot:
<img width="439" alt="screen shot 2016-02-12 at 14 55 31" src="https://cloud.githubusercontent.com/assets/5577291/13008802/e3921136-d198-11e5-85aa-dd5fc6a15e93.png">

**Comment by sandergo90** [comment]
@dbeerten if this is still the case, can you make a PR for it ?
