### ISSUE TITLE
Is it possible to add KunstmaanBundlesCMS to existing Symfony2 App?

### ISSUE THREAD

**Issue by Mrkisha** [Kunstmaan/KunstmaanBundlesCMS#1005]
I was wondering if its possible to add KunstmaanBundlesCMS to existing Symfony2 App?

**Comment by Caroga** [comment]
+1

**Comment by jockri** [comment]
Yes, this is possible, but it will be time consuming.
Do you have a small SF2 application? If this is the case, it is better to create a new project based on the KunstmaanBundlesStandardEdition and migrate your own code to the created project.
If you have a bigger application, you should can compare the composer.json and the SF configuration directory of the KunstmaanBundlesStandardEdition with your own application, and copy the relevant parts.
