### ISSUE TITLE
[SEOBundle] get_title_for will not return AbstractPage#getPageTitle()

### ISSUE THREAD

**Issue by tentwofour** [Kunstmaan/KunstmaanBundlesCMS#1020]
There seems to be something missing:
* SeoTwigExtension#getTitleForPageOrDefault checks, in order of pref:
 * The Page's SEO metaTitle property 
 * The Page's title property

But it never checks for the Page's pageTitle property; which it should (I think?) I realize that I can call get_title_for(null, page.pageTitle), or just call {{ page.pageTitle }} as well...

Lines 95 and 118 of SeoTwigExtension should be changed to:

```php
$arr[] = $entity->getPageTitle();
```

as that method checks for the pageTitle property, and if not set, will return the title property.

I think this could cause some potential SEO/indexing issues for anyone using the get_title_for() function to output the title element content, or elsewhere, so maybe it's a BC break?

Happy to work out a PR, but direction would be appreciated.

**Comment by jockri** [comment]
The navigation title is used in the url (page.title).
If you want to use the page.pageTitle, you can override the Twig function or template.
