### ISSUE TITLE
[MediaBundle]: How to add a FolderType chooser to KunstmaanMediaBundle_chooser

### ISSUE THREAD

**Issue by Perni1984** [Kunstmaan/KunstmaanBundlesCMS#1029]
My `YachtModelAdminType` has a field called `exteriorGallery` where I would like to save a `Kunstmaan\MediaBundle\Entity\Folder`, which contains all the pictures for the photo gallery of this specific yacht model.

Now what I would like to do is to use the `KunstmaanMediaBundle_chooser` to choose the specific folder that contains the pictures. For now I can only select individual pictures in the chooser, but not folders to my knowledge. How would I go best to modify the KunstmaanMediaBundle_chooser to be able to select a folder for the `exteriorGallery` field of my `AdminType`?

**Comment by mlebkowski** [comment]
How about leaving the media chooser, but replace the selected image with it’s folder?

```php
class  YachtModel {
   public function setExteriorGallery(Media $media) {
      $this->exteriorGallery = $media->getFolder();
   }
}
```

A slightly more advanced solution would be to use [`DataTransformer`](http://symfony.com/doc/current/cookbook/form/data_transformers.html) on the form field to exchange `Media` into `Folder` and back. 

BTW, I’m starting to look forward to your new Yacht site ;)

**Comment by Perni1984** [comment]
@mlebkowski: Thanks for the idea, but I would consider this more a hack - a very clever one, but still a hack ;-). I would rather like to extend the KunstmaanMediaBundle_chooser to support a Folder Mediatype - any help or more documentation on how to do that would be appreciated.

**Comment by jockri** [comment]
A simple solution would be to show a select box with all folders in it. To make it more user friendly, you can customise the select fields labels like we did in the folder chooser when you edit a media item.

**Comment by Perni1984** [comment]
@jockri: Thanks for the suggestion, I went for this solution now, it's simple and effective. Eventually I add an link besids to open up the Kunstmaan Media Bundle chooser and go for mlebowski's solution additionally.
