### ISSUE TITLE
Update to 3.5.0 PagePart::getDefaultAdminType broken

### ISSUE THREAD

**Issue by virtualize** [Kunstmaan/KunstmaanBundlesCMS#1031]
After updating to 3.5.0 it's not possible to use a form type service name in PagePart::getDefaultAdminType. Unfortunately we heavily rely on this feature.

EDIT:
I saw it already has been fixed in 7c56264baa81df50c773b9cb8965bfcf74299f91
When do you plan to release a fixed 3.5.1 Version?

Thanks.

**Comment by sandergo90** [comment]
Hi,

You can use the dev-master branch of the bundles for now. We will create a new release soon.

Sander

**Comment by virtualize** [comment]
Hi Sander, thanks for you fast reply. I was hoping for something like "end of the week" or "in the next 2 weeks". So for now I will leave our production sites on 3.4.
