### ISSUE TITLE
UPGRADE-3.5.md is missing required form type changes

### ISSUE THREAD

**Issue by virtualize** [Kunstmaan/KunstmaanBundlesCMS#1033]
I had to upgrade all our (generated) AdminType forms that where we used kunstmaan's `media`, `wysiwyg` and `urlchooser` form types from something like this

````
$builder
    ->add('image', 'media', array(
        'pattern' => 'KunstmaanMediaBundle_chooser',
        'mediatype' => 'image',
    ))
    ->add('summary', 'wysiwyg')
    ->add('link', 'urlchooser')
;
````

to this

````
$builder
    ->add('image', MediaType::class, array(
        'mediatype' => 'image',
    ))
    ->add('summary', WysiwygType::class)
    ->add('link', URLChooserType::class)
;
````
Include the required use statements.

This should be in the update docs. I'm willing to create a PR for it.
Are there any other form types where this also applies?

**Comment by virtualize** [comment]
Oh. I see thats part of the upgrade process to symfony 3 and https://github.com/umpirsky/Symfony-Upgrade-Fixer is nicely taking care of this. Well.

**Comment by aistis-** [comment]
Unfortunately Symfony-Upgrade-Fixer did not work for me in this case :/
Anyway, `'pattern' => 'KunstmaanMediaBundle_chooser'` should be prelaced by ` 'chooser' => 'KunstmaanMediaBundle_chooser'`
