### ISSUE TITLE
3.5 fresh install frontend error - getOwner() on a non-object

### ISSUE THREAD

**Issue by alexborton** [Kunstmaan/KunstmaanBundlesCMS#1040]
Having performed a fresh install of Kunstmaan 3.5, i am getting the following error on all frontend pages;

`Fatal error: Call to a member function getOwner() on a non-object in /...../app/cache/prod/classes.php on line 8100`

The admin area seems to be functioning as it should and i can log in with no issues. I have tried two fresh installs and both throw the same error. I have also tried removed all of the calls to layout partials on the view template and still get the same error. 

I am running;
OSX El Capitan
PHP v5.5.32
MySql v5.5.44 (homebrew)

Keen to get up and running on 3.5. Thanks

**Comment by sandergo90** [comment]
Hi @alexborton,

I've already submitted a pull request for this. 

There was an upgrade of the sensioframeworkextrabundle that created this error ;)

https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/1039

**Comment by alexborton** [comment]
Thanks @sandergo90, ill keep an eye out for the release!

**Comment by lroth** [comment]
@alexborton You can always keep previous version of the sensioframeworkextrabundle in your composer.json file by adding there:
"sensio/framework-extra-bundle": "3.0.12"
I need to deal with it last monday ;)

**Comment by alexborton** [comment]
Yes, this is what i went ahead and did! Thanks
