### ISSUE TITLE
Is it possible to add site wide pagepart widget?

### ISSUE THREAD

**Issue by lroth** [Kunstmaan/KunstmaanBundlesCMS#1046]
I'm thinking about something which is shared by whole website (ie. footer credits). 
How do you deal with it? 
I want to prevent the situation where I have to add the pagepart for all the pages with the same content inside. 
I can always create some custom module and create the twig helper to fetch the data but maybe there is an easier solution for that?

**Comment by aistis-** [comment]
Our workaround was to have this footer in homepage page part like `footer` and coding it into the layout.

```
<div class="footer">
    {% set node = get_node_by_internal_name('homepage', app.request.locale) %}
    {% if node is not null %}
        {% set nodeTrans = node.getNodeTranslation(app.request.locale) %}
        {% set homepage = get_page_by_node_translation(nodeTrans) %}
        {% for pagepart in getpageparts(homepage, 'footer') %}
            {% include pagepart.defaultview with {'resource': pagepart} %}
         {% endfor %}
    {% endif %}
</div>
```

**Comment by lroth** [comment]
Thanks @aistis- for answear. We have similar approach - page in the structure called "shared" hidden from menu and we use it for sharing components.

**Comment by jockri** [comment]
Yes this is a good approach. An other solution would be to use translations (Settings -> Translations) for the footer area since the content will probably never change.

**Comment by aistis-** [comment]
Unfortunately our footer had some extra links, social icons and buttons which had to be modified via CMS.

**Comment by jockri** [comment]
When you need a menu in the footer, you can use the MenuBundle.
But yes, everything depends on the requirements you have.
