### ISSUE TITLE
Is not able to release Kunstmann CMS in host sub-directory (example: http://example.com/subdir), 

### ISSUE THREAD

**Issue by indigo-valdas** [Kunstmaan/KunstmaanBundlesCMS#1052]
Assets are hard coded in twig files to load from "/bundles/....", but if i host all application in "http://example.com/subdir" i expect to load all bundles assets from: "http://example.com/subdir/bundles", but currently all assets are loaded from: "http://example.com/bundles"

**Comment by Slurp** [comment]
Out of the box it doesn't work. But it is fixable. You should override the _css.html.twig view and adjust the paths in the scss. also use the cssrewrite filter in the css asset
