### ISSUE TITLE
problem in instaling 

### ISSUE THREAD

**Issue by hindB** [Kunstmaan/KunstmaanBundlesCMS#1054]
Hello, please I need help in kunstmaan instaling in my symfony project, I've added this line in composer.json : "kunstmaan/bundles-standard-edition": "^3.5.1"
 then I update, but it's not succesful, I've tried other bundles it's succesful, but with kunstmaan I find problems, also with kunstmaan/bundles-cms...  "your requirement could not be an installable set of packages"

**Comment by Caroga** [comment]
Could you give some more information, like the a copy paste of your error message(s)?

**Comment by sandergo90** [comment]
@jockri close
