### ISSUE TITLE
Password reset page needs some default styling

### ISSUE THREAD

**Issue by sandergo90** [Kunstmaan/KunstmaanBundlesCMS#1056]
When resetting your password and clicking on the link in your e-mail, you will go to the password reset page.

There should be some more default styling for the input fields etc.
![screenshot 2016-03-03 16 19 51](https://cloud.githubusercontent.com/assets/1516413/13498887/15fac708-e15c-11e5-9b77-42e91c5d6862.png)

**Comment by jockri** [comment]
@sandergo90 Is this still the case?

**Comment by sandergo90** [comment]
Looks fine now indeed. I will close the issue.
