### ISSUE TITLE
Bring the design of the backend into 2015

### ISSUE THREAD

**Issue by roderik** [Kunstmaan/KunstmaanBundlesCMS#106]
Update CMS to new look and feel
- [ ] Designs validated
- [ ] Bring design to CMS (FE)

**Comment by tentwofour** [comment]
If you need a tester for any of this, let me know (hopefully it's a move to twbs3, and responsive?)

**Comment by roderik** [comment]
@tentwofour there is a branch available to test. And indeed, twbs3 and responsive :) We did not change the design yet, so it should be an easy upgrade

**Comment by tentwofour** [comment]
Looking good so far!

Not sure if I should add an issue (or PR?), but is there any chance that a 'help' block could be added to AdminBundle/Resources/views/Form/fields.html.twig (and, I suppose, a twig extension & service definition). It'd be useful for both page parts, and adminlist-based forms, imo.

Let me know, can add a PR if you'd like.
