### ISSUE TITLE
Having multiple WysiwygType fields in a single page part causes an error

### ISSUE THREAD

**Issue by mtnorthrop** [Kunstmaan/KunstmaanBundlesCMS#1062]
If you create a page part that contains more than one Wysiwyg field type, you will not be able to add this page part to a page in the admin section.

When you try to do so, the new page part never appears and you can see an error in FireBug, stating `TypeError: this.filter is undefined`.

It appears that error is thrown somewhere in the process of re-initializing the rich editors. I've tried to track down the bug but have not been able to. The most I could find out is that the `TypeError` exception is from CKEditor, and it is being thrown during the rich editor reinit process.

From what I can see, the first of the wysiwyg editors is intialized properly, but the error appears while trying to do the second.

**Comment by aistis-** [comment]
I cannot reproduce the error. We use multiple `WysiwygType` fields in same page part, but the error does not appear. Using `dev-master` at the moment.

**Comment by bakie** [comment]
When using the last stable version (3.5.1) you will get the TypeError. This is fixed in master :)

**Comment by aistis-** [comment]
Close the issue? :)

**Comment by bakie** [comment]
@mtnorthrop or @jockri can close it :). I cannot :(

**Comment by mtnorthrop** [comment]
Thanks for fixing this. I'll close the issue.
