### ISSUE TITLE
[PagePartBundle] CKeditor reinit on unsaved pageparts clears text

### ISSUE THREAD

**Issue by Devolicious** [Kunstmaan/KunstmaanBundlesCMS#1069]
When adding/editing a page with multiple TextPageParts without saving before adding a new TextPagePart will clear all entered/edited text for the already existing TextPageParts.

Example:
Add page > add text pagepart > enter some text > add another text pagepart (without saving first) = text from first pp is cleared

**Comment by mtnorthrop** [comment]
I'm also experiencing this bug, using version 3.5.1.
