### ISSUE TITLE
Kunstmaan LeadGenerationBundle Entity Rule AbstractRule not found

### ISSUE THREAD

**Issue by onalekitso** [Kunstmaan/KunstmaanBundlesCMS#1073]
**Please help on the below error**

[Doctrine\Common\Persistence\Mapping\MappingException]                                                                                                       
  The class 'Kunstmaan\LeadGenerationBundle\Entity\Rule\AbstractRule' was not found in the chain configured namespaces Gedmo\Translatable\Entity, Gedmo\Trans  
  lator\Entity, Gedmo\Loggable\Entity, Gedmo\Tree\Entity, Kunstmaan\NodeBundle\Entity, Kunstmaan\SeoBundle\Entity, Kunstmaan\MediaBundle\Entity, Kunstmaan\Ad  
  minBundle\Entity, Kunstmaan\PagePartBundle\Entity, Kunstmaan\MediaPagePartBundle\Entity, Kunstmaan\FormBundle\Entity, Kunstmaan\NodeSearchBundle\Entity, Ku  
  nstmaan\SitemapBundle\Entity, Kunstmaan\ArticleBundle\Entity, Kunstmaan\TranslatorBundle\Entity, Kunstmaan\RedirectBundle\Entity, Kunstmaan\DashboardBundle  
  \Entity, Acme\Bundle\MookaneBundle\Entity, FOS\UserBundle\Model

**My composer.json is**
"require": {
        "kunstmaan/bundles-cms": "dev-master",
        "symfony-cmf/routing-bundle": "~1.4.0-RC1",
        "symfony-cmf/routing": "~1.4.0-RC2",
        "raven/raven": "~0.13.0",
        "friendsofsymfony/http-cache-bundle": "~1.3.6",
        "ekino/newrelic-bundle": "~1.3.2",
        "doctrine/doctrine-migrations-bundle": "~1.1.1",
        "friendsofsymfony/user-bundle": "2.0.*@dev",
        "kriswallsmith/spork": "~0.3.0",
        "jms/serializer-bundle": "dev-master",
        "beberlei/DoctrineExtensions": "1.0.7"
    },

**Comment by jockri** [comment]
Cleaning up old issues
