### ISSUE TITLE
Is this repository / issue list being maintained ?

### ISSUE THREAD

**Issue by Caroga** [Kunstmaan/KunstmaanBundlesCMS#1079]
Hi,

No offence, but it seems that this repository is no longer being maintained. Reported issues go unanswered for many days. Also, your documentation looks like it's behind the current codebase. 

It would be nice to know if this is still active as this would severely affect the decision for me, and many others, to use your components and offer PRs (it would be a waste of time if the repository is just not maintained).

**Comment by roderik** [comment]
Hi, everything is maintained actively. With over 26 PR's merged last month https://github.com/Kunstmaan/KunstmaanBundlesCMS/pulse/monthly

Answering issues is done on a best effort case. Saying that if we have a lot of paid work, answers might be lagging a bit.

**Comment by Caroga** [comment]
Okay good to know there is activity. I understand that paid work has preference but Open Source software actually has no office hours, just saying. 

I would gladly see the documentation being updated as I am struggling (and that's actually an understatement) to get this the kunstmaanbundles to work on my development area. The documentation does not provide a clear way on what the requirements are, as for example the bundles depend on APC still being used and the Vagrantbox, both puppet and ansible, are not in working order and fail to provide a development box.

I am currently trying my best to get all of this to work with a Docker setup and will provide you with all the steps to do so if I succeed. I think this would benefit everyone if it would be committed inside the documentation.

Thank you very much.

**Comment by Caroga** [comment]
As said earlier: I've tried in creating a docker setup with the kunstmaandbundles standard edition. So far so good, below is the list of containers running and providing the cms successfully:
```
Starting project_elasticsearch_1
Starting project_db_1
Starting project_adminer_1
Starting project_application_1
Starting project_php_1
Starting project_nginx_1
```
I will share this as soon as possible, currently running into some other problems which I think might be more framework related. Will create a issue for that.

**Comment by Devolicious** [comment]
Hi @Caroga,

We're also working on a docker environment for the KunstmaanBundles so it will be interesting to see your approach against ours. We'll be releasing our docker setup probably this week or the next.


Happy coding!

**Comment by Caroga** [comment]
@Devolicious That really sounds good. 
What would you like me to do, wait for your release or push mine as well ?

**Comment by Devolicious** [comment]
@Caroga if you're ready you can already create a PR so we can evaluate. Afterwards we'll see how to proceed when we release our setup.

**Comment by Devolicious** [comment]
Hi @Caroga, you can take a look at https://github.com/Kunstmaan/spaceport
We want to make our docker workflow as simple as possible so we are building a small app for it. You can find the docker-compose.yml in the templates folder. It's not quite finished, but you can already use it/fork it if you want. 

Also, you can have a look at this: https://github.com/Devolicious/AwesomeDockerHelpers
Yet again some stuff to make the workflow easier.

Happy coding!

**Comment by Caroga** [comment]
Hi thank you for answering, sorry for the long delay. Currently I have a working setup with docker, will still have to take a look at your setup as my current one is more of a private setup (it's from the company where I currently work at).
