### ISSUE TITLE
Custom ckeditor config

### ISSUE THREAD

**Issue by aistis-** [Kunstmaan/KunstmaanBundlesCMS#1080]
Hello, I found hard to add plugin to CKEditor. Could I get some guidelines how to add http://ckeditor.com/addon/embed to the editor located at admin panel?

**Comment by jockri** [comment]
Did you manage to add the plugin?

**Comment by aistis-** [comment]
Unfortunately no :disappointed: I did not have enough time to find the solution.

**Comment by mtnorthrop** [comment]
Here's an overview of how to add the Embed plugin to CKEditor in the Admin bundle:

1. Override _ckeditor_configs_extra.html.twig by creating a new file with that name under app/Resources/KunstmaanAdminBundle/views/Default/

2. Create a new custom config in _ckeditor_configs_extra.html.twig. Make sure to include the <script></script> tags.

3. Download the Embed plugin and put it under your webroot. I put mine in /js/ckeditor/plugins/.

4. Download all the dependencies for the Embed plugin and put these under your webroot as well. You'll have to follow a line of dependencies when downloading from the CKEditor website. For example, when you go to download Embed from http://ckeditor.com/addon/embed, you'll see that they list Media Embed Base as a dependency. So then you have to go to http://ckeditor.com/addon/embedbase and download it as well. This also has it's own dependencies that you'll have to download. Make sure you get them all.

5. Set up a custom CKEditor config in your  _ckeditor_configs_extra.html.twig file. Here's an example of what it could look like:

```
<script>
ckEditorConfigs['myCustomConfig'] = {
            skin: 'bootstrapck',
            startupFocus: false,
            bodyClass: 'CKEditor',
            filebrowserWindowWidth: 970,
            filebrowserImageWindowWidth: 970,
            filebrowserImageUploadUrl: '',
            extraAllowedContent: 'div(*)',
            toolbar: [
                { name: 'basicstyles', items : ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', 'RemoveFormat'] },
                { name: 'lists', items : ['NumberedList', 'BulletedList'] },
                { name: 'dents', items : ['Outdent', 'Indent'] },
                { name: 'links', items : ['Link','Unlink', 'Anchor'] },
                { name: 'insert', items : ['Image', 'Table', 'SpecialChar'] },
                { name: 'clipboard', items : ['SelectAll', 'Cut', 'Copy', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo'] },
                { name: 'editing', items : [] },
                { name: 'document', items : ['Source'] }
            ],
            extraPlugins: 'embed'
};

externalPlugins = [
    ['embed', '/js/ckeditor/plugins/embed'],
    ['embedbase', '/js/ckeditor/plugins/embedbase/']
];

</script>
```

The key is to create the custom config, add "embed" to the extraPlugins property, and then add "embed" and **all** its dependencies to the externalPlugins array. Note that the externalPlugins array is *not* part of your custom config object.

Once that's set up, you need to make sure that your Symfony form is using your custom config for your WysiwygType.

You do that by adding something like this to your Symfony form class:

```
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('myTextField', WysiwygType::class, [
            'attr' => [
                'type' => 'myCustomConfig'
            ]
        ]);
    }
```

The key is setting 'type' to the name of your custom config in your 'attr' array.

These are the key elements that you need to get a custom CKEditor plugin set up and working. I might have forgotten a few details, but if there are any problems you can probably find the answer in the CKEditor documentation.

I hope this helps!

**Comment by jockri** [comment]
Thanks for the detailed explanation @mtnorthrop !
