### ISSUE TITLE
Single language installation generates error on homepage

### ISSUE THREAD

**Issue by Caroga** [Kunstmaan/KunstmaanBundlesCMS#1086]
Hi,

After installation, and configuration, of the single language routings / security files, I get errors on the homepage. 
It turned out that the site bundle generation did not generate a default index action, so I am wondering what this would be ? 
As currently I have the following and this works, but I do not understand what template to return in order to get the homepage visible again ? 
Also, weird thing, when browsing to the `/nl` I do get the home page in working order....

Anyone could shed a light on this ?

Thank you very much.
Kind regards

**Comment by mennowame** [comment]
For a single language website this should not be a problem. I've also got a few single language websites where there isn't any indexAction in the DefaultController. With these sites it works fine. The indexAction that is generated for multilanguage sites is only there to make multilanguage websites work (in dev mode?)

Did you perhaps change the URL of the homepage? What errors are you getting?

**Comment by iknowfoobar** [comment]
This happens to us all the time. We always install the bundles using the instructions and then convert to a single language site afterwards.

When the site is generated it creates an indexAction method in the DefaultController that always forwards you to the default language slug regardless of whether the site is set to single language. For us this always results in a redirect loop. Just deleting the indexAction method fixes this for us.

**Comment by iknowfoobar** [comment]
Could possibly do with a note in the instructions for converting to single language to check this redirect doesn't exist and to remove it if it does.
