### ISSUE TITLE
Update the router to support country/language and domain based routing

### ISSUE THREAD

**Issue by roderik** [Kunstmaan/KunstmaanBundlesCMS#109]
À generic version of the Mxxxxxx version
Also add http://inchoo.net/online-marketing/google-shows-meta-description-wrong-website/

**Comment by yoshz** [comment]
Any update about language specific domain routing? 
We are looking into a solution to have different domains for translated pages, but the admin must work on each domain with the _locale prefix or query parameter.

**Comment by roderik** [comment]
Coming in the next month or two.

**Comment by yoshz** [comment]
Any idea's about this yet? 
Otherwise we will just submit a pull request with our changes.

**Comment by jockri** [comment]
Solved with https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/633
