### ISSUE TITLE
Update from 3.4.1 to 3.5.1 issue

### ISSUE THREAD

**Issue by aistis-** [Kunstmaan/KunstmaanBundlesCMS#1092]
Hello,

I have fixed version of kunstmaan in my `composer.json` on `"kunstmaan/bundles-cms": "3.4.1"`. I am updating to `"kunstmaan/bundles-cms": "3.5.1"` with `composer update kunstmaan/bundles-cms` but getting an error:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for kunstmaan/bundles-cms 3.5.1 -> satisfiable by kunstmaan/bundles-cms[3.5.1].
    - kunstmaan/bundles-cms 3.5.1 requires symfony-cmf/routing-bundle ~1.4.0-RC1 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
```

**Comment by aistis-** [comment]
My `composer.json` contained `"minimum-stability": "stable"`. Temporary solution could be decreasing minimum stability to `"minimum-stability": "RC"`.

**Comment by mlebkowski** [comment]
@aistis-, if you require those packages in this version you don’t need to change the stability flag:

```
    "symfony-cmf/routing-bundle": "~1.4.0-RC1",
    "symfony-cmf/routing": "~1.4.0-RC2",
```

**Comment by aistis-** [comment]
@mlebkowski Yeah, but I also do not include packages I do not use myself. Anyway yesterday they released stable packages :)
