### ISSUE TITLE
[MediaBundle] Upload big file in chunks

### ISSUE THREAD

**Issue by aistis-** [Kunstmaan/KunstmaanBundlesCMS#1095]
Hi guys,

I was looking a way of uploading big files (~500MB) via media manager, but seems it does not have chunk uploading at the moment. Do you have chunk uploading on your plans?

**Comment by jockri** [comment]
Hi @aistis- ,

No, we did not yet need such big uploads. Are there any upload libraries that we could use? If you have time you may send a PR request :-)

**Comment by aistis-** [comment]
I am developing a feature where a big .zip (any archive) file could be uploaded and extracted on the server. I am going to implement file chunking via [1up-lab/OneupUploaderBundle/](https://github.com/1up-lab/OneupUploaderBundle/) and [plupload](http://www.plupload.com/)  which is already bundled with `MediaBundle`. The idea is that archived file is shown as one file in the media manager while it could be contained of whole (physical) directory tree.

I am creating something like `ArchiveHandler` :)

**Comment by aistis-** [comment]
At the end of the day my handler got very customized and not suitable for open source :(
