### ISSUE TITLE
[SeoBundle] getimagesize

### ISSUE THREAD

**Issue by jverdeyen** [Kunstmaan/KunstmaanBundlesCMS#1107]
When getting the dimensions of seo images, this function is used:

https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/src/Kunstmaan/SeoBundle/Twig/SeoTwigExtension.php#L251

And here the **after** filter image **url** is passed:

https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/src/Kunstmaan/SeoBundle/Resources/views/SeoTwigExtension/metadata.html.twig#L60

Can't we rely on the metadata? This is a relative resize onto `1200` px width.

The function relies on the "speed" of the server whois serving the image. This could pull up the loadtimes when there is latency?

**Comment by jockri** [comment]
I think it is correct to return the dimensions for the filtered image url.

When the filtered image is not hosted locally, it increases the load time drastically...
We should find a solution, but I'm not sure which options we have to fix this.
