### ISSUE TITLE
Controller handling page part

### ISSUE THREAD

**Issue by w3q** [Kunstmaan/KunstmaanBundlesCMS#1116]
Hi, 

I want to create a page part, that should basically be handled by a controller action. I want to call REST api and retrieve data and then basically render them within the twig template.

Is it possible to do that somehow, or I can not link the controller action to a page part?

Thank you.

**Comment by jockri** [comment]
Currently there are two options:
* Use a twig extension
* Use the render controller function (esi is also possible here)

**Comment by w3q** [comment]
Thank you a lot.
