### ISSUE TITLE
[SearchBundle] Incompatibility with Elasticsearch 2.1.1 version

### ISSUE THREAD

**Issue by fchris82** [Kunstmaan/KunstmaanBundlesCMS#1117]
I find some fatal errors:

    Mapping definition for has unsupported parameters: index_name

https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_20_mapping_changes.html#_literal_index_name_literal_and_literal_path_literal_removed

    Root mapping definition has unsupported parameters:  [analyzer : index_analyzer_hu] [_boost : {name=_boost, null_value=1}]

https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_20_mapping_changes.html#_analyzer_mappings

**Comment by fchris82** [comment]
There is a new version from `ruflin/Elastica` : https://github.com/ruflin/Elastica/releases . It might be a custom `elastic2` branch: https://getcomposer.org/doc/articles/aliases.md#require-inline-alias , with different `ruflin/Elastica` version.

**Comment by Numkil** [comment]
These issues will be resolved in the next release of the Bundles. As of yet the max supported version of elasticsearch is 1.7.
