### ISSUE TITLE
[AdminBundle] Google sign in not correct for existing users 

### ISSUE THREAD

**Issue by sandergo90** [Kunstmaan/KunstmaanBundlesCMS#1144]
I have activated the Google auth for a project. I already have an existing user for the e-mail address I would like to login with in my application.

In the OAuthUserCreator in the function "getOrCreateUser" there is a check to look for a user with username equal to the e-mail address provided. My username is not equal to my e-mail address. Therefor I think the check needs to be done on e-mail address and not on username.

**Comment by Numkil** [comment]
@sandergo90 A fix has been merged that changes the default behaviour to something a bit more expected. Also included in this merge is an improvement to the code itself to allow users to override the default search for users with google login data functionality with their own or even to override the complete login code.

**Comment by sandergo90** [comment]
Superb ;)
