### ISSUE TITLE
KunstmaanSeoBundle Twitter Card Image bug

### ISSUE THREAD

**Issue by iknowfoobar** [Kunstmaan/KunstmaanBundlesCMS#1150]
We just noticed this in a 3.5.1 website we are building. If you add Twitter Card info to a page but don't select an image you get a fatal error on the front end:

```php
Impossible to access an attribute ("contentType") on a null variable in KunstmaanSeoBundle:SeoTwigExtension:metadata.html.twig at line 73
```

I would imagine the solution would be to either validate that an image is selected in the admin area or test the variable first before trying to access it in the template file.

**Comment by jockri** [comment]
Yes, this is indeed a bug. Can you create a PR to fix this? Thanks!

**Comment by iknowfoobar** [comment]
I shall, may be in a few days though

**Comment by iknowfoobar** [comment]
Looks like @bakie already fixed this.
