### ISSUE TITLE
PCNTL

### ISSUE THREAD

**Issue by Kharestani** [Kunstmaan/KunstmaanBundlesCMS#1152]
Hi people
congratulation for the great job on Kunstmaan.
WAMP is running on my system(windows) and I use that to develop and do magic!
I know I should not live on windows and it is a shame for an open source developer to do so but I am limited so please don't judge! ;D
could you please do something about making PCNTL optional cause PHP does not run this on windows and I really want to use Kunstmaan for my projects.

**Comment by jockri** [comment]
The KunstmaanBundles do not use that extension, but some vendors/libraries need it.
Perhaps you can use Vagrant (with a linux OS) for running your application on your local machine?

**Comment by Kharestani** [comment]
thank you for your response I will try it.
