### ISSUE TITLE
Generator remove created Article

### ISSUE THREAD

**Issue by KevinSleegers** [Kunstmaan/KunstmaanBundlesCMS#1153]
Hi,

I would like to remove a previously generated article completely.
I've tried to do it manually, but somehow when I've deleted all related files, I get an error from Symfony that says `Attempted to load class "FaqOverviewPage" from namespace "Kevin\WebsiteBundle\Entity\Pages".` Strange thing is that when I do a global search in PHPStorm I cannot find any files that contain a reference to 'FaqOverviewPage'. For that reason I'd like to do it by using a command, to be sure it got deleted everywhere.

I am not sure if it has something to do with caching, because after I open my application (and new caching files gets generated) they have a reference to 'FaqOverviewPage'. Even when I delete my entire cache folder they come back.

Anyone who can help me?

**Comment by jockri** [comment]
Probably there is a link in your database to that entity. Check the `kuma_nodes`, `kuma_node_versions` and `kuma_page_part_refs` tables.

**Comment by KevinSleegers** [comment]
Yeah you're right, thanks!
