### ISSUE TITLE
[AdminList] Eye icon in admin list for the "view" action

### ISSUE THREAD

**Issue by mtnorthrop** [Kunstmaan/KunstmaanBundlesCMS#1161]
When you activate the "view" action for an admin list, the link to the view action in the "Actions" column is the word "View".

The code that produces this is in the widget.html.twig file:
```twig
{% if adminlist.canView(item) %}
    <a href="{{ path(adminlist.getViewUrlFor(item)["path"], adminlist.getViewUrlFor(item)[("params")] ) }}">
        <i class="icon-eye"></i>View
    </a>
{% endif %}
```

It looks like we should have an icon here, but the .icon-eye class does not appear to exist in any of the Kunstmaan bundles.

Shouldn't this show an eye icon instead?

Maybe the widget.html.twig file could be updated as such:
```twig
{% if adminlist.canView(item) %}
    <a href="{{ path(adminlist.getViewUrlFor(item)["path"], adminlist.getViewUrlFor(item)[("params")] ) }}" class="link--text table__actions__item" title="View">
        <i class="fa fa-eye"></i>
    </a>
{% endif %}
```

This would make the icon for the View action on the admin list match the display of the icon for the Preview action on the Pages list. (In the suggested replacement code I've also included the css classes on the link to match the other action items.)

**Comment by jockri** [comment]
Yes, it should be an icon.
Can you send a PR?
Thanks!

**Comment by jockri** [comment]
Thanks!
