### ISSUE TITLE
Got error when not logging in

### ISSUE THREAD

**Issue by aunn** [Kunstmaan/KunstmaanBundlesCMS#1164]
Attempted to call an undefined method named "getProviderKey" of class "Symfony\Component\Security\Core\Authentication\Token\AnonymousToken"

I think it because of this commit.
https://github.com/Kunstmaan/KunstmaanBundlesCMS/commit/74c004eeecfe2535b926a6258969c364c69db414

I have tried to use old code and it works fine.

**Comment by davidgorges** [comment]
Fresh install leads to this bug.
