### ISSUE TITLE
SettingsBundle

### ISSUE THREAD

**Issue by aistis-** [Kunstmaan/KunstmaanBundlesCMS#1173]
Hello, is there a solution similar to https://github.com/Sylius/SyliusSettingsBundle for settings control in Kunstmaan?
Let's say I have some global website settings, which must be editable via CMS. It could be a pagination number, some integration API credentials, an image (a relation to a Media entity) which must be rendered as a background in whole website.
I do not want to end up creating an entity for each of these settings row :)

**Comment by sandergo90** [comment]
Hi!

Yes there is as of symfony 3.

We have implemented this recently and you can find it here https://github.com/Kunstmaan/KunstmaanBundlesCMS/tree/sf3/src/Kunstmaan/ConfigBundle.

Cheers!

**Comment by aistis-** [comment]
Great, is there any example I could check?

**Comment by sandergo90** [comment]
Hi,

Yes there is ;) https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/sf3/src/Kunstmaan/ConfigBundle/Resources/doc/ConfigBundle.md

Cheers

**Comment by aistis-** [comment]
Thanks a lot!
