### ISSUE TITLE
Custom user entity

### ISSUE THREAD

**Issue by w3q** [Kunstmaan/KunstmaanBundlesCMS#1176]
Hello,

I have a question. Is it possible to configure custom user and group entity without rewriting some kunstmaan code?

We have our own implementation of the FOS user and we want to use it as a kunstmaan users, but Ive found out there were some group stuff fighting, so Ive rewritten MappingListener in AdminBundle for now, but i guess this is terrible solution. 

Is it possible to somehow replace your user with ours without too much pain?

Thanks.

**Comment by jockri** [comment]
Here is an example that can be useful:
https://bundles.kunstmaan.be/news/extending-the-admin-user-entity

**Comment by w3q** [comment]
Thank you, this looks really good.

**Comment by w3q** [comment]
@jockri Is there any way to extend groups as well? I want to replace Kunstmaan group entity with ours, i have configured FOS to use it, but it still fight sometimes somewhere.

**Comment by jockri** [comment]
Good question, I did not have done it before. Let me know if you have found a solution to do it :-)

**Comment by w3q** [comment]
We have decided to do the fork of the bundles and rewrite it. Since the code was not written in any configurable way to replace groups.

**Comment by sandergo90** [comment]
@jockri close
