### ISSUE TITLE
Default pageparts: Image pp

### ISSUE THREAD

**Issue by IbeVanmeenen** [Kunstmaan/KunstmaanBundlesCMS#118]
MediaPagePartBundle:

- [ ] Change ```<div class="image-pp">``` to ```<figure class="image-pp">```
- [ ] Add possibility to add caption (```<figcaption>```)
- [ ] Add possibility to choose positioning (left - right - center - full-width)
- [ ] Add responsive behaviour (src-set)
 - Add one big image
 - ```src-set``` done by big, medium, small imagine-filter (no upscaling!)
 - ```sizes="100vw"```
- [ ] Add default styleguide markup in resources/ui/scss/_image-pp.scss
- [ ] Fix the url issue when running from a sub-directory. (see issue/pr #126)

**Comment by Maff-** [comment]
May I suggest to add tackling the url issue when running from a sub-directory as mentioned in issue/pr #126 ?

**Comment by IbeVanmeenen** [comment]
@Maff- Will do. Added in the list above.

**Comment by Maff-** [comment]
Awesome, thank you!

**Comment by FVKVN** [comment]
related to #852

**Comment by FVKVN** [comment]
@diskwriter this can be closed now I think
