### ISSUE TITLE
Installation guide missing Bundler

### ISSUE THREAD

**Issue by TomoGlavas** [Kunstmaan/KunstmaanBundlesCMS#1199]
Not sure if just me, but the docs for installation were missing `gem install bundler` before I could execute `bundle install`.

**Comment by InnekeVM** [comment]
`apt-get install bundler` gets the job done as well

**Comment by jockri** [comment]
@TomoGlavas can you create a PR to add it to the documentation (see docs folder in the root of the project). Thanks!

**Comment by sandergo90** [comment]
@jockri close
