### ISSUE TITLE
Allow multiple views in page parts

### ISSUE THREAD

**Issue by henrypenny** [Kunstmaan/KunstmaanBundlesCMS#12]
New Feature Suggestion:

Add a preferred view field and allowedViews function to AbstractPagePart.
This will allow AbstractPageParts to have multiple views.

The following is an example abstract subclass of AbstractPagePart that I'm currently using.

    abstract class AbstractMultiViewPagePart extends AbstractPagePart {
    
        /**
         * @ORM\Column(type="string", name="preferred_view", nullable=true)
         */
        protected $preferredView;
    
        /**
         * Set preferredView
         *
         * @param string $preferredView
         * @return ImagePagePart
         */
        public function setPreferredView($preferredView)
        {
            $this->preferredView = $preferredView;
    
            return $this;
        }
    
        /**
         * Get preferedView
         *
         * @return string
         */
        public function getPreferredView()
        {
            return $this->preferredView;
        }
    
        public function getView(PageInterface $page = null, $view = null)
        {
            if($view != null) {
                $_view = $view;
            }
            else if($this->preferredView != null) {
                $_view = $this->preferredView;
            }
            else {
                $_view = $this->getDefaultView();
            }
            return $_view;
        }
    
        /**
         * Returns an array of available views.
         * @return array
         */
        abstract public function getAvailableViews();
    } 

Subclasses implement getAvailableViews like this:

    public function getAvailableViews() {
        $views = array(
            'AcmeBundle:PageParts/ConcretePagePart:view.html.twig' => 'Default',
            'AcmeBundle:PageParts/ConcretePagePart:summary.html.twig' => 'Summary',
            'AcmeBundle:PageParts/ConcretePagePart:expanded.html.twig' => 'Expanded'
        );
        return $views;
    }

Then the AdminType would have this:

        $builder->add('preferredView', 'choice', array(
            'required' => false,
            'choices' => (new ConcretePagePart())->getAvailableViews()
        ));

I have also overridden: 
    
    KunstmaanPagePartBundle/views/PagePartTwigExtension/widget.html.twig

    {% for box in pageparts %}
        {% set resource = box %}
        {% if view is defined and box.getView(page, view) is defined %}
            {% include box.getView(page, view) %}
        {% else %}
            {% include box.getView(page) %}
        {% endif %}
    {% endfor %}

This allows the view to be manually overridden when you're rendering a page part direct from a template.

**Comment by denbatte** [comment]
Hi,
Thank you for your feature suggestion.
We discussed your proposal today and decided not to implement this directly into the Kunstmaan bundles. We feel that such a feature is more a add on to the PagePartBundle, because not all page parts need multiple views.

A blog post will be written about this and other methods to achieve your intended result in the near future.
That way, everyone can still benefit from this.

Once more, thank you for the suggestion.
