### ISSUE TITLE
[MediaBundle]: Make media in folder sortable

### ISSUE THREAD

**Issue by Perni1984** [Kunstmaan/KunstmaanBundlesCMS#1203]
Hi,

for a project of mine I would like to make the media inside some specific folders sortable (Galleries, Download Folders, etc.) What what be the best way of doing that?

Create a SortableFolder type, eventually using DoctrineExtension "sortable" or is such a behaviour eventually already built into kunstmaan?

**Comment by jockri** [comment]
The media items in a folder are already sortable. Both in the list-view as in the thumb-view.
Did you test the latest version of the bundles?

![image](https://cloud.githubusercontent.com/assets/517574/16187098/a8d7e0ca-36ce-11e6-9441-c602bb914847.png)
![image](https://cloud.githubusercontent.com/assets/517574/16187123/cb527dae-36ce-11e6-8b75-24b5def02efd.png)

**Comment by Perni1984** [comment]
sorry, I was not really clear about my intent in the issue. What I would like to achieve is to have a specific custom sort order in a folder that I can change via drag/drop or up/down arrows - e.g. for a photo gallery.

**Comment by Perni1984** [comment]
@jockri: would you have an idea of how to ensure that?

**Comment by mlebkowski** [comment]
For what it’s worth, I never use Media items and Folders directly, but instead create a PagePart to select a media file. This way you can organise your Media any way you want, and only publish those you wish, using the order you wish (provided by page parts interface). YMMV.

**Comment by Perni1984** [comment]
@mlebowski: thanks for your help - this would certainly be a way. For e.g. a photogallery with 20+ photos, I would rather prefer the upload a media folder option and sort the media objects directly in the media manager via drag and drop ultimately. I think I could eventually provide a PR for that functionality, I just want to make sure, that if I develop this now, it is in line with the overall Kunstmaan approach so the PR could be accepted.

**Comment by jockri** [comment]
This should indeed not be developed in the media manager, but in a custome adminlist or pagepart for the project.
