### ISSUE TITLE
FOSUserBundle fields not in database on doctrine:schema:update

### ISSUE THREAD

**Issue by sandervanhooff1997** [Kunstmaan/KunstmaanBundlesCMS#1214]
I'm running an older version of Kunstmaan "2.3._" and my FOSUserBundle currently has version "2.0._@dev".
1. When logging in, the page refreshes without showing ANY errors.. 
2. When I run the command "doctrine:schema:validate" I get an error that my "database schema is not in sync with the current mapping file".
3. Next I run the command "doctrine:schema:update --force", this updates the database with 7 executed queries.
4. After updating my database all the BaseUser fields are disappeared from the user table and only my custom fields are in the user table.

Has this anything to do with my Kunstmaan or FOSUserBundle version? 
And if it does, what version's of Kunstmaan->FOSUserBundle work together on a Symfony 2.3 project?

Thanks in advance,
Sander

**Comment by jockri** [comment]
Is this still an issue?
Can you update to the latest version of FOSUserBundle?

**Comment by delboy1978uk** [comment]
Have we dropped support for this version? It appears the minimum branch we can check out is 3.0, and tag-wise v3.0.0, so I am unable to try to replicate the issue
