### ISSUE TITLE
How to use kunstmaan media bundle with aws

### ISSUE THREAD

**Issue by w3q** [Kunstmaan/KunstmaanBundlesCMS#1216]
Hello,

I would like to use Kunstmaan and load images to it from aws server. Is there any way how to do it?

**Comment by iknowfoobar** [comment]
You can view the documentation at https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/docs/05-12-using-a-custom-filesystem-for-the-media-bundle.md

We have it working on several v3.6 websites

**Comment by sandergo90** [comment]
@jockri close
