### ISSUE TITLE
Excel export is too slow for large exports

### ISSUE THREAD

**Issue by jockri** [Kunstmaan/KunstmaanBundlesCMS#1234]
Replace the current excel lib with a more performant one

**Comment by Numkil** [comment]
https://github.com/box/spout
This one seems to be specialized in large exports while keeping the internal memory low. I will check out if I can get it work.

**Comment by Numkil** [comment]
Since the first test results were quite positive using box/spout I went ahead and created a PR where I replace the current excel lib with box/spout.
PR #1241.
