### ISSUE TITLE
Large select value

### ISSUE THREAD

**Issue by dbeerten** [Kunstmaan/KunstmaanBundlesCMS#1238]
When a value is to large to fit in the select, it goes to the next line outside the wrapper.

![issue](https://cloud.githubusercontent.com/assets/5577291/16874733/4ee6ffc0-4a9b-11e6-96ea-7f7783bb5461.png)

**Comment by KMBenjaminSchodts** [comment]
Dit is blijkbaar enkel in de bundles versie van kunsthuis, de standaard Bundles versie houdt alle tekst in zijn veld.
![image](https://cloud.githubusercontent.com/assets/19650038/17322567/5bec9912-589e-11e6-8d79-da5a4a6415df.png)
