### ISSUE TITLE
Main actions in backend should be more compact

### ISSUE THREAD

**Issue by indrikenens** [Kunstmaan/KunstmaanBundlesCMS#124]
Only show 2 main action buttons, hide the others under  More ▾

Now:
![screen shot 2015-01-22 at 17 37 24](https://cloud.githubusercontent.com/assets/772236/5859832/8baf72da-a25d-11e4-814d-5aed320d79af.png)

Should become:
Save  Preview   More ▾

**Comment by IbeVanmeenen** [comment]
Needs some Backend work:
Provide extra attribute for the actions buttons where you can specify is the button is important or not. If important is set, the button will be visible. Otherwise, the button will be added under "more"

**Comment by krispypen** [comment]
Maybe the decision of showing 2 buttons is not backend dependend, but frontend dependent? responsive. Then it's maybe better to just show the first 2 buttons and the rest behind the "more" button?

**Comment by roderik** [comment]
Indeed, what @krispypen says

**Comment by IbeVanmeenen** [comment]
Ready on development
