### ISSUE TITLE
Implementing Sortable in a AdminListConfigurator sets the SortableField to 1

### ISSUE THREAD

**Issue by InnekeVM** [Kunstmaan/KunstmaanBundlesCMS#1254]
I've created a new AdminList called `DiskAdminList` but noticed that my `releaseDate` (a DateTime) always gets set to `1`. It seems that this is due to my `DiskAdminListConfigutrator` that is implementing `SortableInterface`.

My `DiskAdminListConfigurator` has the following code:
```php
    public function getSortableField()
    {
        return "releaseDate";
    }
```

In this Bundle's `AdminListController` is the following code in the function `doAddAction`:
```php
                // Check if Sortable interface is implemented
                if ($configurator instanceof SortableInterface) {
                    $sort = $configurator->getSortableField();
                    $weight = $this->getMaxSortableField($repo, $sort);
                    $setter = "set".ucfirst($sort);
                    $helper->$setter($weight + 1);
                }
```

If I'm following this correctly, the code gets in this if because I am implementing the SortableInterface, and `$sort` will be `releaseDate`, the $weight is `0`, and the `$setter` will be `setReleaseDate`. Then, my entity is called with `setReleaseDate(0+1)`, and the `releaseDate` will be set to 1.

This causes an issue when saving a bit later since `1` can not be converted to a DateTime in Doctrine.

**Comment by sandergo90** [comment]
Hi,

I think your on the wrong way here. The sortable field is used in the admin list to allow the items to move from position with use of the up and down arrows. If you want to sort your admin list on the releasedate, you don't have to use the sortable behaviour. You can just override the querybuilder for your adminlist and change the order in your query.

Cheers

**Comment by sandergo90** [comment]
@jockri close
