### ISSUE TITLE
Undefined function when trying to implement new field in Admin List

### ISSUE THREAD

**Issue by alexborton** [Kunstmaan/KunstmaanBundlesCMS#1258]
I have an admin list for an article setup that i need to customise in the backend. Following the doc's, i added;

`public function buildFields()
    {
        $this->addField('title', 'article.page.list.header.title', true, 'KunstmaanNodeBundle:Admin:title.html.twig');
        $this->addField('popular', 'Popular', true, 'SuperrbMyBundle:AdminList\FAQPageAdminList:popular.html.twig');
    }`

but only get an undefined notice for the field 'popular';

`undefined function [get/is/has]popular()`

I have the getters and setters in place for 'popular', a boolean value. I also have the custom template in place (which is functional). I am unsure what i am missing and struggling to debug. I can't see any issues with my code on this project specifically, so wonder if it could be a wider bug.

**Comment by alexborton** [comment]
This is presumably to do with the query builder not including the actual node translation when building the fields?

**Comment by sandergo90** [comment]
Hi,

Can you past the adminlistconfigurator here in a snippet ? Then I can have a closer look.

Sander

**Comment by alexborton** [comment]
```
<?php

namespace Superrb\MyBundle\AdminList;

use Doctrine\ORM\QueryBuilder;
use Kunstmaan\ArticleBundle\AdminList\AbstractArticlePageAdminListConfigurator;

/**
 * The AdminList configurator for the FAQPage
 */
class FAQPageAdminListConfigurator extends AbstractArticlePageAdminListConfigurator
{

    public function buildFields()
    {
        $this->addField('title', 'article.page.list.header.title', true, 'KunstmaanNodeBundle:Admin:title.html.twig');
//        $this->addField('popular', 'Popular', false, 'SuperrbMyBundle:AdminList\FAQPageAdminList:popular.html.twig');
//        $this->addField('date', 'Date', false, 'SuperrbMyBundle:AdminList\FAQPageAdminList:popular.html.twig');
        $this->addField('updated', 'article.page.list.header.updated_at', true);
        $this->addField('online', 'article.page.list.header.online', true, 'KunstmaanNodeBundle:Admin:online.html.twig');
    }

    public function getLimit()
    {
        return 50;
    }

    /**
     * Return current bundle name.
     *
     * @return string
     */
    public function getBundleName()
    {
        return 'SuperrbMyBundle';
    }

    /**
     * Return current entity name.
     *
     * @return string
     */
    public function getEntityName()
    {
        return 'Pages\FAQPage';
    }

    /**
     * @param QueryBuilder $queryBuilder The query builder
     */
    public function adaptQueryBuilder(QueryBuilder $queryBuilder)
    {
        parent::adaptQueryBuilder($queryBuilder);

        $queryBuilder->setParameter('class', 'Superrb\MyBundle\Entity\Pages\FAQPage');
    }

    /**
     * @return \Doctrine\ORM\EntityRepository
     */
    public function getOverviewPageRepository()
    {
        return $this->em->getRepository('SuperrbMyBundle:Pages\FAQOverviewPage');
    }

    /**
     * @return string
     */
    public function getListTemplate()
    {
        return 'SuperrbMyBundle:AdminList/FAQPageAdminList:list.html.twig';
    }
}

```

That's my complete adminlistconfigurator. You can see the extra fields that i tried to add commented out. 

I believe this is because the query builder (further up the chain) is not including the actual page node itself, rather the top-level entity. For example, i can add the 'slug' successfully as it is located in the kuma_node_translations. The properties i want to access are in mb_faq_pages because they are additional fields. Hope that all makes sense, appreciate the help!

**Comment by sandergo90** [comment]
Hi,

That's correct. The adminlistconfigurator will not join your custom page by default. You will have to adapt the querybuilder and join the node with the page table. Below an example, you are probably better with using a DBALAdminlistconfigurator for this purpose.

`/**
     * @param QueryBuilder $queryBuilder
     * @param array $params
     */
    public function adaptQueryBuilder(QueryBuilder $queryBuilder, array $params = array())
    {
        $qbQuery = clone $queryBuilder;
        $qbQuery
            ->select('b.id, b.title, b.online, nv.created, nv.updated, b.weight, n.id as node_id, b.lang, fp.faq_id, fc.name as category')
            ->from('kuma_node_translations', 'b')
            ->innerJoin('b', 'kuma_nodes', 'n', 'b.node_id = n.id')
            ->innerJoin('b', 'kuma_node_versions', 'nv', 'b.public_node_version_id = nv.id and b.lang = :lang')
            ->innerJoin('nv', 'bo_faqpages', 'fp', 'nv.ref_id = fp.id')
            ->innerJoin('fp', 'bo_faq_categories', 'fc', 'fp.faq_id = fc.id')
            ->where('n.deleted = 0')
            ->andWhere('n.ref_entity_name = :class')
            ->setParameter('class', '[your_class]')
            ->andWhere('b.lang = :lang')
            ->setParameter('lang', $this->locale)
            ->orderBy('b.weight', 'asc');

        /**
         * This is necessary for the results query happening in the pagerfanta adapter,
         * otherwise it will result in a groupBy with count query that results with count = 1
         * and no pagination will be available
         */
        $qbHelper = clone $queryBuilder;
        $qbHelper
            ->select('a.*')
            ->from('('.$qbQuery->getSQL().')', 'a')
            ->groupBy('a.node_id')
        ;

        $queryBuilder
            ->select('b.*')
            ->from('('.$qbHelper->getSQL().')', 'b')
            ->setParameter('lang', $this->locale)
            ->setParameter('class', $this->getPageClass());
    }`

Sander

**Comment by alexborton** [comment]
Thanks Sander. A quick copy and paste and replace of some classes didn't work, but i should get the chance to take proper look later today

**Comment by alexborton** [comment]
@sandergo90 I couldn't get your snippet to work. It seems like a strange approach to have to define the columns directly in the query? For example, if i was to add another column that i wanted to display, i would have to also update the query. Also, the function; `getSQL()` is undefined and not available.

Is the above snippet relevant to the latest version of Kunstmaan? Thanks

**Comment by sandergo90** [comment]
Hi,

Sure it is. You are sure you are using the dbal querybuilder and a dbal adminlistconfigurator?

Sander

**Comment by alexborton** [comment]
Yes @sandergo90 , with both those extensions instead of ORM Query builder and AbstractArticlePageAdminListConfigurator. I am a little confused as to why i have to change the uses as this seems to throw out all the other functionality of the adminlistconfigurator as well, just to manually join some columns? There must be a more simple way that works..?

**Comment by KevinSleegers** [comment]
Hi, I'm currently facing the same issue. I would like to show data of my Page within the Adminlist. Could you maybe provide a updated example, I can't make it work using the code @sandergo90 provided)?

Thanks in advance,

**Comment by Numkil** [comment]
Closing because PR which provides this functionality has been merged
