### ISSUE TITLE
Question: Is it possible to add custom URLs to the frontend menu?

### ISSUE THREAD

**Issue by mtnorthrop** [Kunstmaan/KunstmaanBundlesCMS#1265]
This is not a bug report, so I'm sorry if this is not the correct place to ask, but I don't know of any other support forum for the Kunstmaan bundles.

I'd like to add menu items to the frontend menu that point to routes that I've created in my own controllers.

I know that this is possible in the backend by creating a menu adaptor and using the adaptChildren() method, but I haven't found a way to do this for the frontend menu.

Is it possible to add menu items to the frontend menu without creating pages for them? If so, would anyone be able to point me in the right direction and let me know where I can do this?

Thanks!

**Comment by sandergo90** [comment]
Hi,

Sure this is possible. You can use the KunstmaanMenuBundle for this purpose!

Sander

**Comment by mtnorthrop** [comment]
Thank your for your quick answer! I completely overlooked the MenuBundle.

Can pages that are created in the AdminBundle be automatically added to a MenuBundle menu, or do they have to be added manually?

For example, at the moment I'm using the default node menu for the frontend, and every time a new page is created, it automatically appears on the menu.

If I replace the default node menu with a MenuBundle menu, will I have to add each new page to it manually from now on?

Thanks!

**Comment by sandergo90** [comment]
Hi,

Yes indeed, you have to add it to the custom menu automatically. 

Maybe you can add some eventlistener that adds a menu item automatically when you create a node ?

Cheers

**Comment by mtnorthrop** [comment]
Thanks for confirming that. An event listener sounds like a great way of dealing with the issue!
