### ISSUE TITLE
Select search for relationship selection

### ISSUE THREAD

**Issue by alexborton** [Kunstmaan/KunstmaanBundlesCMS#1266]
Is it at all possible to build in a searchable select/dropdown for parsing through large potential relationship lists. 

For example, if i want to allow my admin to manually select some related products for a product page, it would be great if that large list (200+) items could be searched using a custom select builder like Chosen.js

If this is a bespoke element outside of the core Kuma build scope, how would i go about hooking into the necessary JS for adding/removing and updating JS on page part add or duplicate. 

Thanks

**Comment by mlebkowski** [comment]
Like selecting groups when editing user? Look at [UserType.php#L83-L86](https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/33e6aa58da2a94d96dfe135cb797a0dc7768685a/src/Kunstmaan/AdminBundle/Form/UserType.php#L83-L86). It’s not ajax loaded or anything, but should do just fine as long as your list is not extra huge.

As for the second part of your question:

 * Extend the `add_or_edit.html.twig` template and add your javascript in the `extrajavascript` block (look it up, I don’t remember)
 * The Configurator has methods to return the [add] and [edit] templates, override them with your template
 * If the choice widget you’d like to use has a complex template (not configured only by some extra attributes), you may add your form theme easily using [config](http://symfony.com/doc/current/form/form_customization.html#making-application-wide-customizations)

[add]: https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/src/Kunstmaan/AdminListBundle/AdminList/Configurator/AbstractAdminListConfigurator.php#L651-L654
[edit]: https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/src/Kunstmaan/AdminListBundle/AdminList/Configurator/AbstractAdminListConfigurator.php#L691-L694

**Comment by alexborton** [comment]
This is exactly what i was looking for. Thanks @mlebkowski !
