### ISSUE TITLE
[AdminListBundle] Excel export does not allow custom templates for fields

### ISSUE THREAD

**Issue by mtnorthrop** [Kunstmaan/KunstmaanBundlesCMS#1277]
The admin list export service does not allow custom templates to be used for fields, unless they are objects.

I would expect to be able to create a custom template for my Excel export fields, using the `AbstractAdminListConfigurator::addExportField()` method, in the same way that I can create templates for my admin list fields using the `addField()` method.

At the moment, though, that is not possible because custom templates that are set using the `addExportField()` method are only used if the exported entity's property is an object.

The line that is responsible for this is here:
https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/src/Kunstmaan/AdminListBundle/Service/ExportService.php#L131

In order to allow developers to create custom templates for the fields in their exported Excel files, I'd propose changing this line to:

```
if ($column->getTemplate()) {
```

This way, we can create our own templates regardless of the data type for a given field. Would this be an acceptable change? (For the moment, I've fixed the problem in my own project by creating my own ExportService class that extends the original, and updating the `createExcelSheet()` method.)

**Comment by mlebkowski** [comment]
we had this problem as well and made a quick fix:

Instead of exporting `$foo` field, we created a getter: `getDummyFoo()` that returns `$this` and used that field in the configurator. That enables us to use a custom template (since the value is an object), for example `{{ object.foo | format_me_anyway_youd_like }}`.

It’s easier, because you’re not overwriting the whole exporter.

**Comment by mtnorthrop** [comment]
Thanks for the suggestion. I might even use your approach instead if there end up being complications with my extended service.
