### ISSUE TITLE
How to pronounce Kunstmaan?

### ISSUE THREAD

**Issue by aistis-** [Kunstmaan/KunstmaanBundlesCMS#1284]
Hello,

could you guys define how to pronounce **Kunstmaan** correctly?
It is serious :) I sometimes end up saying "Yeah, we use cunts man on that project".

**Comment by Numkil** [comment]
Stick these 2 words together :)
http://forvo.com/word/kunst/#nl
http://forvo.com/word/maan/#nl

**Comment by aistis-** [comment]
Thanks @Numkil :)
