### ISSUE TITLE
How can I make CKE not set image width and height

### ISSUE THREAD

**Issue by tarjei** [Kunstmaan/KunstmaanBundlesCMS#1289]
Hi, I'm looking for pointers wrt to the CKE media chooser code.

I would like to be able to not have it set image height and width automatically, but instead just add a default class or (even better) let me define the markup that is injected into the page.

The reason is that the images that are inserted need to live in a responsive design and thus they cannot have explicit height and width.

I.e. todays behaviour is:

1. User opens "add image", 
2. chooses `browse server`
3. selects an image.
4. The image properties are displayed _with the image height and width inserted automatically_.

What I want is:

1. User opens "add image", 
2. chooses `browse server`
3. selects an image.
4. The image properties are displayed, but no explicit height and width is defined.

Is this possible to do?

**Comment by jockri** [comment]
We do not recommend using images in RTE. It is better to create a new pagepart when you want ot use Image + Text. This makes it more easy to style, for mobile, etc..
