### ISSUE TITLE
Problem new link chooser for social Open Graph url

### ISSUE THREAD

**Issue by jockri** [Kunstmaan/KunstmaanBundlesCMS#1293]
Only absolute url should be allowed, no choose button.

![image](https://cloud.githubusercontent.com/assets/517574/18541654/c36e00b2-7b26-11e6-9a87-39c6472e92f1.png)

**Comment by sandergo90** [comment]
This will always be a absolute URL because you will choose a page in the tree structure of your website. This will generate a token that will always be replaced by a absolute URL.

Or do we not want the URL chooser here but only the option to enter absolute URL?
