### ISSUE TITLE
Dependency imagine/imagine v0.5.0

### ISSUE THREAD

**Issue by cmberlin** [Kunstmaan/KunstmaanBundlesCMS#1303]
Could you please remove the dependency to the imagine bundle, as liip already defines it. Your bundle uses a far old (v0.5.0) imagine integration. Would be nice if the user of your bundles could choose by itself.

Thanks
Carsten

**Comment by sandergo90** [comment]
Hi,

This was needed for the following pull request.

https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/935

**Comment by aistis-** [comment]
Could it be fixed to work with a newer imagine?
