### ISSUE TITLE
Request: unique constraint for Redirect

### ISSUE THREAD

**Issue by aistis-** [Kunstmaan/KunstmaanBundlesCMS#1309]
Hello, what do you think of having Unique constraint for `Redirect` entity on fields `domain`, `origin`, `target`?

https://github.com/Kunstmaan/KunstmaanRedirectBundle/blob/sf3/Entity/Redirect.php

**Comment by jockri** [comment]
I think it should be on domain + origin. Can you send PR to sf3 branch?
