### ISSUE TITLE
Consider using `Accept-Language` HTTP header to set default locale

### ISSUE THREAD

**Issue by michaelarnauts** [Kunstmaan/KunstmaanBundlesCMS#1316]
The browser sends a list of preferred languages in the `Accept-Language` HTTP-header. We could use this to redirect to the requested language (if it exists) when the site is requested on `/`. Currently, all visits go to the specified default language. This will make sure the visitor gets the website in his preferred language.

**Comment by aistis-** [comment]
I've created a regular controller for homepage which basically redirects to one of the locales `/de`, `/en` or whatever.
The logic you redirect is any you want. In case it is preferred language:
```
$request->getPreferredLanguage()
```

**Comment by jockri** [comment]
@aistis- sounds like a good idea, can you send a PR to update the default / controller?

**Comment by aistis-** [comment]
@jockri I sure would, if I had a time :disappointed: now working on a bunch of customs features, so maybe in the future :)

**Comment by michaelarnauts** [comment]
I've implemented this by replacing the `indexAction()` of the `DefaultController` with the following code.

This can probably be cleaner (like error checking if HTTP_ACCEPT_LANGUAGE header is unavailable), but it does it job. In case no match is found, it redirects to the default language as it is currently.

```php
    /**
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     * @Route("/")
     */
    public function indexAction(Request $request)
    {
        $defined_locales = explode('|', $this->container->getParameter('requiredlocales'));
        $accept_language = explode(',', $request->server->get('HTTP_ACCEPT_LANGUAGE'));
        foreach ($accept_language as $accept_language) {
            $lang = explode(';', $accept_language);
            if (in_array($lang[0], $defined_locales)) {
                return new RedirectResponse($this->generateUrl('_slug', array('url' => '', '_locale' => $lang[0])));
            }
        }
        return new RedirectResponse($this->generateUrl('_slug', array('url' => '', '_locale' => $this->container->getParameter('locale'))));
    }
```

**Comment by Numkil** [comment]
Closing because proposed functionality written by @cv65kr and merged.
