### ISSUE TITLE
Nested regions in page template config

### ISSUE THREAD

**Issue by jockri** [Kunstmaan/KunstmaanBundlesCMS#1332]
In the page template configuration (yml) it should be possible the nest regions.
In this way a sidebar can span multiple rows.

**Comment by mlebkowski** [comment]
You’re talking about this piece?  ;)

https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/src/Kunstmaan/PagePartBundle/DependencyInjection/Configuration.php#L51-L54

**Comment by jockri** [comment]
If you want a sidebar that spans on multiple regions, this is not possible in the admin.
The first scheme is the current situation, the second scheme is the would be situation where the "sidebar region" spans multiple other regions on the right.

![untitled diagram](https://cloud.githubusercontent.com/assets/517574/19303162/e3afbd6a-9067-11e6-8b7b-04ac02412ab5.png)

**Comment by Perni1984** [comment]
I realised something like that already, writing a separate PageTemplateConfigurationReader, that reads a dynamic page templated configuration with nested rows / columns out of the db. I am not sure how you would like to implement this, but I imagine I could eventually extract some of the code to a separate bundle.

**Comment by sandergo90** [comment]
HI @Perni1984,

I'm currently working on a pull request for nested regions. Almost finished! 

Cheers

**Comment by Perni1984** [comment]
@sandergo90: Ok, I see - thanks for the info - I guess I must have missed that on the roadmap somewhere. BTW if you are interested in the dynamic page templates I can support on that aswell - see some real-life example of that here:
![image](https://cloud.githubusercontent.com/assets/9039956/19756843/af2e8b8e-9c1f-11e6-96ab-4e95e894ba57.png)

**Comment by sandergo90** [comment]
Looking good @Perni1984 

Here are some screens of what I am doing.

https://cl.ly/3q2E0P1l2H3U

https://cl.ly/1A1S3n1H2S0f

**Comment by Perni1984** [comment]
@sandergo90: perfect - looks similar ;-) Eventually there would have been some synergies before, when I knew that you guys needed such a feature aswell.

**Comment by sandergo90** [comment]
Indeed ;)

And for the configuration, this looks like the following:

![screen shot 2016-10-27 at 08 37 14](https://cloud.githubusercontent.com/assets/1516413/19756997/9ca18f2e-9c20-11e6-9544-0b9310e39428.png)

**Comment by wesleylancel** [comment]
@Perni1984 Those screenshots look pretty cool! Does it allow for adding regions dynamically? Any chance it's out there as a bundle?

**Comment by Perni1984** [comment]
@wesleylancel: Yes, regions are added dynamically on a page, and each region is represented as bootstrap column basically. You are also able to nest an arbitrary number of regions inside regions. Moreover you have several layout options to customize the regions according to different bootstrap breakpoints.

Unfortunately I don't have the time to carve this out as an extra bundle now. I expected this feature has already landed in Kunstmaan as @sandergo90 indicated it should be ready soon?

**Comment by sandergo90** [comment]
@Perni1984 it's ready for merging ;)

https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/1379

**Comment by wesleylancel** [comment]
@sandergo90 @Perni1984 Does that PR allow for adding regions inside the admin itsself too or is it just for allowing regions within regions defined within the .yml configuration file? It's be awesome if the dynamically added regions could make it into core as well. Is that planned in any way?

**Comment by sandergo90** [comment]
@wesleylancel the configuration that I created has to be i the .yml configuration files. The way @Perni1984 describes this is something different, maybe when he has the time he can create a PR for this?
