### ISSUE TITLE
Can't delete just a language version in pages

### ISSUE THREAD

**Issue by markmedia** [Kunstmaan/KunstmaanBundlesCMS#1365]
Deleting the page will lead to a total data loss from the DB. Client wanted to recopy page from a primary language and in result deleted all the pages/data.

Some backup solution would be cool to restore deleted pages (it can be done also only for admin user).

**Comment by sandergo90** [comment]
Hi @markmedia ,

We are already using a soft delete solution for this. When you delete a node, this node will still remain in the database but with the column "deleted" set to 1. You can set it back to 0 for your node to return.

**Comment by Devolicious** [comment]
@markmedia I'm assuming that @sandergo90 's explanation suffices, so I'm closing this.
