### ISSUE TITLE
[AdminBundle] Bug: Old guzzle version in use

### ISSUE THREAD

**Issue by aistis-** [Kunstmaan/KunstmaanBundlesCMS#1369]
Hi,

file https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/sf3/src/Kunstmaan/AdminBundle/Helper/VersionCheck/VersionChecker.php#L6 uses old v3 Guzzle version when in the `composer.json` is defined `"guzzlehttp/guzzle": "~6.1"` https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/sf3/src/Kunstmaan/AdminBundle/composer.json

in the result, it occurs, that the class has a dependency on not existed file.

Solution: upgrade `VersionChecker.php` to use the required guzzle.

**Comment by sandergo90** [comment]
Hi @aistis- 

Can you make this pull request on the master branch to?

Cheers
