### ISSUE TITLE
The controller must return a response (null given).

### ISSUE THREAD

**Issue by iBenito** [Kunstmaan/KunstmaanBundlesCMS#1373]
Trying to follow the documentation: [Cookbook: Custom Controller](https://bundles.kunstmaan.be/documentation/cookbook/adding-a-custom-controller-to-a-page)

Which results in the following exception:
> The controller must return a response (null given).

This is problematic, but not the worst problem, since this functionality is easily replaced using a Twig extension. 

The worst problem is trying to follow this documentation: [Cookbook: News of Blog](https://bundles.kunstmaan.be/documentation/content-management/adding-a-news-section-or-blog)

The problem is the Controller does not return a response. In this instance specifically it's in the ArticleBundle: [KunstmaanArticleBundle:AbstractArticleOverviewPage:service](KunstmaanBundlesCMS/src/Kunstmaan/ArticleBundle/Controller/AbstractArticleOverviewPageController.php)

Is there a plan to fix this? Or a workaround?

**Comment by sandergo90** [comment]
Hi @iBenito,

I've updated the documentation in the following pull request.

https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/1388

Cheers
