### ISSUE TITLE
Call to undefined function apc_fetch

### ISSUE THREAD

**Issue by ChrisButterworth** [Kunstmaan/KunstmaanBundlesCMS#1378]
So I have nginx, php70 and mariadb installed on macOS and every other project I work on is great this one doesn't...
I have opcache and apc installed but still getting this message

`Fatal error: Uncaught Symfony\Component\Debug\Exception\UndefinedFunctionException: Attempted to call function "apc_fetch" from namespace "Doctrine\Common\Cache". in /Users/thedistrict/Sites/kunstmaan/vendor/doctrine/cache/lib/Doctrine/Common/Cache/ApcCache.php:41 Stack trace: #0 /Users/thedistrict/Sites/kunstmaan/vendor/doctrine/cache/lib/Doctrine/Common/Cache/CacheProvider.php(212): Doctrine\Common\Cache\ApcCache->doFetch('DoctrineNamespa...') #1 /Users/thedistrict/Sites/kunstmaan/vendor/doctrine/cache/lib/Doctrine/Common/Cache/CacheProvider.php(185): Doctrine\Common\Cache\CacheProvider->getNamespaceVersion() #2 /Users/thedistrict/Sites/kunstmaan/vendor/doctrine/cache/lib/Doctrine/Common/Cache/CacheProvider.php(78): Doctrine\Common\Cache\CacheProvider->getNamespacedId('Kunstmaan\\Trans...') #3 /Users/thedistrict/Sites/kunstmaan/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php(211): Doctrine\Common\Cache\CacheProvider->fetch('Kunstmaan\\Trans...') #4 /Users/thedistrict/Sites in /Users/thedistrict/Sites/kunstmaan/vendor/doctrine/cache/lib/Doctrine/Common/Cache/ApcCache.php on line 41`

I know using Vagrant would fix this but I really don't want to as it means one Vagrant box running at a time which slows me down.

Any ideas??

**Comment by sandergo90** [comment]
Hi,

Do you Have apcu installed also ? This is required for php7 ;)

Cheers

**Comment by mlebkowski** [comment]
@ChrisButterworth, you can just [turn off the apc cache in the configuration](https://github.com/Kunstmaan/KunstmaanBundlesStandardEdition/blob/master/app/config/config_prod.yml#L8-L12)

@KunstmaanLabs, the standard edition package uses apc and yet `ext-apc` is not specified in the `composer.json`. I’d either add it there or even better make the apc cache optional / commented out by default.

**Comment by aistis-** [comment]
For php 7 which compatibles with [apcu v5+](https://pecl.php.net/package/APCU) you need [apcu-bc extension](https://pecl.php.net/package/apcu_bc).

**Comment by ChrisButterworth** [comment]
Yes @sandergo90 apcu is installed.

@mlebkowski that would make sense during development but not for production.

@aistis- that fixed it! Installed apcu-bc and it works fine now!

Thanks for the tips guys

**Comment by mlebkowski** [comment]
@ChrisButterworth, this is configured in `config_prod.yml`, you shouldn’t be using that one in dev. What’s your `SYMFONY_ENV`? are you routing via `app.php` or `app_dev.php`?
