### ISSUE TITLE
Can you folks split the livereload bundle out?

### ISSUE THREAD

**Issue by jrobeson** [Kunstmaan/KunstmaanBundlesCMS#141]
This bundle seems to have no dependencies on the rest of the kunstmaan bundles. Is it possible that it can be split out and have its own release schedule?

I have quite a few PRs i'd like to submit against it, but i i wouldn't want to be tied up to the overall release schedule of the rest of your CMS bundles.

**Comment by roderik** [comment]
Don't worry about it, since changes here don't bring bc breaks for the base cms we can tag point releases quite easily.

**Comment by jrobeson** [comment]
so, you're ok with breaking BC in the bundle?

I'd like to drop the server and port options in favor of server_url and script_url, as the current way makes it problematic to use the livereload server when your dev environment is SSL and you are proxying through your webserver.

**Comment by jrobeson** [comment]
I had done most of the work on the split bundle repository, so I'd like a bit of review before i bother submitting it as a PR. 

I also have some questions:
   * Can i upgrade it to guzzle 5.x? 3.x is a no-go due to the way it configures SSL cert bundles
   * Do you see a way in which i can make the Configuration class error out if host (and/or port) are specified, without removing the defaults from script_url and server_url?
  * Should i try to make server_url somehow different from script_url?
  * Should i name script_url and server_url something different?

Here is a link to the branch comparison of all the changes: https://github.com/jrobeson/KunstmaanLiveReloadBundle/compare/devel?expand=1

**Comment by jrobeson** [comment]
a guzzle 5.x dependency would require php 5.4, i wonder if there is some way i can make guzzle 3.* do the right thing with ssl.

**Comment by jrobeson** [comment]
i tried playing with various options with setSslVerification, but i couldn't get it to work right.

When will Kunstmaan bump to php 5.4 ?

**Comment by jockri** [comment]
It will be removed in in v4
