### ISSUE TITLE
Feature request: notes for redirects

### ISSUE THREAD

**Issue by aistis-** [Kunstmaan/KunstmaanBundlesCMS#1411]
Hello!

It would be nice to be able add some notes for created redirects via CMS. It would be just a text field for notes, which would make easier to remember why the redirect is created or whatever is the reason :)

In one of our projects we have more than 30 redirects and it became hard to remember why the old redirects still exists.

What do you think?

**Comment by sandergo90** [comment]
Hi @aistis- 

Sounds like a good use case. You can make a PR for this ;)

Cheers

**Comment by Numkil** [comment]
Merging because feature implemented.
