### ISSUE TITLE
Kunstmaan 4.0 generated defaultsite not working

### ISSUE THREAD

**Issue by KevinSleegers** [Kunstmaan/KunstmaanBundlesCMS#1425]
Hi,

I've followed all the steps in the documentation to create a Kunstmaan 4.0 project, and generated a defaultsite and a database using doctrine:fixtures:load.

I had no issues whatsoever, but when I try to access app_dev.php or app_dev.php/en/admin/nodes/ I am getting errors. 

`An exception has been thrown during the rendering of a template ("An exception occurred while executing 'SELECT n.id, n.parent_id AS parent, t.url, t.id AS nt_id,
IF(t.weight IS NULL, v.weight, t.weight) AS weight,
IF(t.title IS NULL, v.title, t.title) AS title,
IF(t.online IS NULL, 0, t.online) AS online,
n.hidden_from_nav AS hidden,
n.ref_entity_name AS ref_entity_name FROM kuma_nodes n LEFT JOIN kuma_node_translations t ON (t.node_id = n.id AND t.lang = :lang) LEFT JOIN kuma_node_translations v ON (v.node_id = n.id AND v.lang <> :lang) INNER JOIN (SELECT DISTINCT o.object_identifier as id FROM stedin-website.acl_object_identities as o
INNER JOIN stedin-website.acl_classes c ON c.id = o.class_id
LEFT JOIN stedin-website.acl_entries e ON (
e.class_id = o.class_id AND (e.object_identity_id = o.id
OR e.object_identity_id IS NULL)
)
LEFT JOIN stedin-website.acl_security_identities s ON (
s.id = e.security_identity_id
)
WHERE c.class_type = "Kunstmaan\\NodeBundle\\Entity\\Node"
AND (s.identifier = "IS_AUTHENTICATED_ANONYMOUSLY" OR s.identifier = "ROLE_SUPER_ADMIN" OR s.identifier = "ROLE_PERMISSIONMANAGER" OR s.identifier = "ROLE_ADMIN" OR s.identifier = "ROLE_ALLOWED_TO_SWITCH" OR s.identifier = "Kunstmaan\\AdminBundle\\Entity\\User-admin")
AND e.mask & 1 > 0) perms_ ON perms_.id = n.id WHERE n.deleted = 0 GROUP BY n.id ORDER BY t.weight ASC, t.title ASC' with params ["en"]:

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-website.acl_object_identities as o
INNER JOIN stedin-website.acl_classes c ON c' at line 6") in KunstmaanAdminBundle:Default:app_header.html.twig at line 35.`

I get that error when trying to access the Homepage. I've Googled a bit, and found out it might have something to do with the mysql_mode that mysql 5.7 expects, however I am running mysql version 5.6.32 on my Linux server.

Anyone  got any idea how I could fix this? It is a brand new project, so I'm sure I can't be the only one who has run into this problem.

Thanks,
Kevin

**Comment by tentwofour** [comment]
You can't have a hyphen in a mysql database name. Change to an underscore, and you'll be up and running.

Not sure if that's a mysql or orm thing, I believe its mysql though.

On January 2, 2017 1:23:25 PM CST, Kevin <notifications@github.com> wrote:
>Hi,
>
>I've followed all the steps in the documentation to create a Kunstmaan
>4.0 project, and generated a defaultsite and a database using
>doctrine:fixtures:load.
>
>I had no issues whatsoever, but when I try to access app_dev.php or
>app_dev.php/en/admin/nodes/ I am getting errors. 
>
>`An exception has been thrown during the rendering of a template ("An
>exception occurred while executing 'SELECT n.id, n.parent_id AS parent,
>t.url, t.id AS nt_id,
>IF(t.weight IS NULL, v.weight, t.weight) AS weight,
>IF(t.title IS NULL, v.title, t.title) AS title,
>IF(t.online IS NULL, 0, t.online) AS online,
>n.hidden_from_nav AS hidden,
>n.ref_entity_name AS ref_entity_name FROM kuma_nodes n LEFT JOIN
>kuma_node_translations t ON (t.node_id = n.id AND t.lang = :lang) LEFT
>JOIN kuma_node_translations v ON (v.node_id = n.id AND v.lang <> :lang)
>INNER JOIN (SELECT DISTINCT o.object_identifier as id FROM
>stedin-website.acl_object_identities as o
>INNER JOIN stedin-website.acl_classes c ON c.id = o.class_id
>LEFT JOIN stedin-website.acl_entries e ON (
>e.class_id = o.class_id AND (e.object_identity_id = o.id
>OR e.object_identity_id IS NULL)
>)
>LEFT JOIN stedin-website.acl_security_identities s ON (
>s.id = e.security_identity_id
>)
>WHERE c.class_type = "Kunstmaan\\NodeBundle\\Entity\\Node"
>AND (s.identifier = "IS_AUTHENTICATED_ANONYMOUSLY" OR s.identifier =
>"ROLE_SUPER_ADMIN" OR s.identifier = "ROLE_PERMISSIONMANAGER" OR
>s.identifier = "ROLE_ADMIN" OR s.identifier = "ROLE_ALLOWED_TO_SWITCH"
>OR s.identifier = "Kunstmaan\\AdminBundle\\Entity\\User-admin")
>AND e.mask & 1 > 0) perms_ ON perms_.id = n.id WHERE n.deleted = 0
>GROUP BY n.id ORDER BY t.weight ASC, t.title ASC' with params ["en"]:
>
>SQLSTATE[42000]: Syntax error or access violation: 1064 You have an
>error in your SQL syntax; check the manual that corresponds to your
>MySQL server version for the right syntax to use near
>'-website.acl_object_identities as o
>INNER JOIN stedin-website.acl_classes c ON c' at line 6") in
>KunstmaanAdminBundle:Default:app_header.html.twig at line 35.`
>
>I get that error when trying to access the Homepage. I've Googled a
>bit, and found out it might have something to do with the mysql_mode
>that mysql 5.7 expects, however I am running mysql version 5.6.32 on my
>Linux server.
>
>Anyone  got any idea how I could fix this? It is a brand new project,
>so I'm sure I can't be the only one who has run into this problem.
>
>Thanks,
>Kevin
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Kunstmaan/KunstmaanBundlesCMS/issues/1425

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by KevinSleegers** [comment]
Wow, how did I miss that... must have been a lack of coffee ;).

Thanks a lot, you're a lifesaver! 👍
