### ISSUE TITLE
Kunstmaan 4.0 ImagePagePart srcset no different sizes

### ISSUE THREAD

**Issue by KevinSleegers** [Kunstmaan/KunstmaanBundlesCMS#1435]
Hi,

I'm using Kunstmaan 4.0 for a new project, and found out that the srcset in the new ImagePagePart does not work (tested it with both png and jpg).

All the images that are being generated (huge_, big_, medium_, and small_) but they all have the exact same size. I have not changed anything in the liip_imagine configuration in my config.yml.

Can you tell me what I am doing wrong?

Thanks in advance,
Kevin

**Comment by Devolicious** [comment]
@KevinSleegers what dimensions does the image have? As the default filters downscale but not upscale.

**Comment by KevinSleegers** [comment]
@Devolicious Hi, the dimensions the image has are 960x653.

**Comment by KevinSleegers** [comment]
Do you have any ideas what might be going wrong?

**Comment by Devolicious** [comment]
@KevinSleegers, I just installed a new KunstmaanBundlesCMS 4.0 project and can't replicate this issue. Could you give some more information about it? Which size is being generated? Are all filters being generated?

**Comment by Devolicious** [comment]
@KevinSleegers Did you manage to get everything working? If so, what was the issue?

**Comment by Perni1984** [comment]
@KevinSleegers: could you kindly post the relevant entries for imagine in config.yml

**Comment by KevinSleegers** [comment]
Hi, 

These are the entries in my config.yml.

```image_huge_jpg:
            quality: 95
            format: jpg
            filters:
                strip: ~
                thumbnail: { size: [2400,null], mode: outbound, allow_upscale: false }
        image_big_jpg:
            quality: 95
            format: jpg
            filters:
                strip: ~
                thumbnail: { size: [1200,null], mode: outbound, allow_upscale: false }
        image_medium_jpg:
            quality: 95
            format: jpg
            filters:
                strip: ~
                thumbnail: { size: [600,null], mode: outbound, allow_upscale: false }
        image_small_jpg:
            quality: 95
            format: jpg
            filters:
                strip: ~
                thumbnail: { size: [400,null], mode: outbound, allow_upscale: false }
```

**Comment by Perni1984** [comment]
@KevinSleegers: looks good to me.

can you post the relevant call to `imagine_filter()` in the twig template?

Are you sure you aren't passing custom configs to `imagine_filter()`?

Have you cleared your cache in the browser before checking:
http://website.dev/app_dev.php/media/cache/resolve/image_huge_jpg/uploads/media/588dd920bc58a/keukm5n-e-g-samuel-scrimshaw.jpg 
http://website.dev/app_dev.php/media/cache/resolve/image_small_jpg/uploads/media/588dd920bc58a/keukm5n-e-g-samuel-scrimshaw.jpg 400w

Aren't you missing a default fallback 'src' attribute in the img tag?

**Comment by KevinSleegers** [comment]
Hi, 

Yes I have cleared my cache, several times.

I am just using the default image pagepart so I am not sure if that's missing a fallback src.

**Comment by Devolicious** [comment]
Hi @KevinSleegers,

I'm going to close this issue since we were not able to reproduce it nor other users had issues like this. I hope you found what the issue was and were able to fix it. If so, a short explanation is always welcome.

Happy coding!
