### ISSUE TITLE
Form submissions documentation

### ISSUE THREAD

**Issue by konstantinsp** [Kunstmaan/KunstmaanBundlesCMS#144]
Hi,
Could you add some documentation on how to implement 
form submissions on pages?

or could you explain me how to do that?:)

**Comment by mennowame** [comment]
I was also trying to find this out today. I'm working on some example/documentation for usage of the FormBundle. 
After making a form page manually we found out that if you generate the demosite (when installing KunstmaanCMS) there is a good example of the FormBundle, look at the FormPage in the demosite.

**Comment by mennowame** [comment]
I've just added the pullrequest for the formpage generator in #185.

**Comment by krispypen** [comment]
the pull request was merged
