### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by cv65kr** [Kunstmaan/KunstmaanBundlesCMS#1443]
Hello,

Can you share demopage from http://demo.bundles.kunstmaan.be/en/ with layout and modules ? I want to see how you build modules and integrate layout with admin data.
I know about --demosite param but not giving me everything from demo or maybe i doing something wrong?

Cheers !

**Comment by cv65kr** [comment]
Ok, i know it was my mistake.
I used setup_project.sh, my problem was in path to sass. Maybe path to uglifyjs, uglifycss, node etc. should be declarated in parameters.yml ?

**Comment by Devolicious** [comment]
@cv65kr, you can specify those paths in your config_dev.yml
