### ISSUE TITLE
Set minimum PHP requirement to 7.1

### ISSUE THREAD

**Issue by Devolicious** [Kunstmaan/KunstmaanBundlesCMS#1445]

**Comment by aistis-** [comment]
Why not for v5.0.0? PHP 5.6 is already in the end of life cycle.

**Comment by Devolicious** [comment]
@aistis- maybe your right, but PHP 5.6 will not reach EOL until 2019. You can use PHP 7+ already, the KunstmaanBundlesCMS is works great with it, but we do not depend on it yet. So for now, why not support PHP 5.6?

**Comment by dannyvw** [comment]
I vote also for 5.0.0. Then we can also bump twig to 2.x

**Comment by carakas** [comment]
You should probably skip 7.0 and go directly to 7.1, symfony and other projects are doing the same
https://gophp71.org/

**Comment by Devolicious** [comment]
Yes indeed, in order to support SF4.0 we will also have to skip 7.0

**Comment by acrobat** [comment]
See #2090
