### ISSUE TITLE
Upgrading to Symfony 2.8 breaks all generated pageparts

### ISSUE THREAD

**Issue by tarjei** [Kunstmaan/KunstmaanBundlesCMS#1448]
Do you have a strategy for handling this? Maybe there should be some documentation on how to handle this transition?

Regards,
Tarjei

**Comment by Perni1984** [comment]
hey Tarjei - what exactly was broken?

**Comment by tarjei** [comment]
Hi @Perni1984 , Sorry for a bad bug report :(

The generated Pageparts contain form types where the fields are defined like this:
```
$builder->add('image', 'image', ...);
```
Whereas 2.8 requires the form type to be a class, i.e. 
```
$builder->add('image', Image::class...);
```

T

**Comment by Devolicious** [comment]
Hi @tarjei,

That is normal since Symfony made that change. It's not related to our bundles. But @jockri wrote a thorough guide on [how to upgrade your project to Symfony 3](https://labs.kunstmaan.be/blog/how-to-upgrade-your-project-to-symfony-3).

Happy Coding!

**Comment by tarjei** [comment]
Thanks for the input and kudos to @jockri for a great guide!
