### ISSUE TITLE
[] operator not supported for strings BUG

### ISSUE THREAD

**Issue by nlefebvre1410** [Kunstmaan/KunstmaanBundlesCMS#1454]
hi 
on click settings users :
[] operator not supported for strings
in vendor/kunstmaan/bundles-cms/src/Kunstmaan/AdminListBundle/AdminList/Configurator/AbstractAdminListConfigurator.php at line 62

**Comment by Devolicious** [comment]
Hi @nlefebvre1410,

Which version are you using? Line 62 of the `AbstractAdminListConfigurator` is a docblock.

**Comment by nlefebvre1410** [comment]
@Devolicious 
 v4.0

**Comment by aistis-** [comment]
There is a fix already for this bug.

https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/1447

**Comment by tarjei** [comment]
@Devolicious the correct linenr is 622. Anyhow #1447 contains a good patch for this. Any posibility of getting out a hotfix?

**Comment by nlefebvre1410** [comment]
hi 
my php 7

**Comment by Devolicious** [comment]
This is fixed in #1483
