### ISSUE TITLE
Is branch sf3 necessary?

### ISSUE THREAD

**Issue by aistis-** [Kunstmaan/KunstmaanBundlesCMS#1456]
Hi, is branch `sf3` still in use?

**Comment by tarjei** [comment]
I do not think so, see:
https://github.com/Kunstmaan/KunstmaanBundlesCMS/releases/tag/4.0.0

**Comment by Devolicious** [comment]
@aistis- not actively but since it has been used for quite a while during the transition between 3.6 and 4.0 we cant just remove this one as it will break composer installs/upgrades.
