### ISSUE TITLE
VersionChecker

### ISSUE THREAD

**Issue by ChristerGustavsson** [Kunstmaan/KunstmaanBundlesCMS#146]
The bundles version checker in the settings doesn't seem to work any more.

Just getting the message "Something went wrong while fetching the version information. Please try again later."

Taking a look at the runtime exception thrown in Kunstmaan\AdminBundle\Helper\VersionCheck\VersionChecker.php and it looks like this:

> An exception occurred while executing 'INSERT INTO kunstmaan__version_projectinfo (created, host, project, installed, ip_address, public_url, screenshot) VALUES (?, ?, ?, ?, ?, ?, ?)' with params ....

> SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'public_url' cannot be null

Why are you guys requiring a public_url?

**Comment by jockri** [comment]
Someone (@roderik) made a mistake in a database migration, public_url was supposed to be nullable. W fixed it now.
Thanks for the report!
