### ISSUE TITLE
Adding multiple image relationship to entity

### ISSUE THREAD

**Issue by ismaserrano** [Kunstmaan/KunstmaanBundlesCMS#1461]
I've created a new entity and I want to relate media with that entity with @ManyToMany:

```
$builder->add('image',
            MediaType::class,
            array(
                'chooser'  => 'KunstmaanMediaBundle_chooser',
                'required' => false,
            )
        );
```

But Symfony shows me:

> Expected an object, but got a collection. Did you forget to pass "multiple=true" to an entity field?

I tried to pass 'multiple' attr to chooser, but with not success... Chooser of Media can do that? Thank you!

**Comment by sandergo90** [comment]
Hi @ismaserrano,

You should create a new entity that will have a image as field. Then you can create a many to many relationship from your entity to the new created entity. For example you have a ImageGallery entity that has a many to many to the ImageGalleryItem entity where the ImageGalleryItem contains the image.

Cheers

**Comment by ismaserrano** [comment]
Hi @sandergo90,

That's it! I've created a Project entity with:

```
/**
     * @var \Kunstmaan\MediaBundle\Entity\Media
     *
     * @ORM\ManyToMany(targetEntity="Kunstmaan\MediaBundle\Entity\Media")
     * @ORM\JoinTable(name="overalia_cmsbundle_projects_images",
     *      joinColumns={@ORM\JoinColumn(name="project_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="image_id", referencedColumnName="id", unique=true)}
     *  )
     */
    private $image;
```

And then, in the form builder, related to the previous message, with:

```
$builder->add('image',
            MediaType::class,
            array(
                'chooser'  => 'KunstmaanMediaBundle_chooser',
                'required' => false,
            )
        );
```

And shows error:

> Expected an object, but got a collection. Did you forget to pass "multiple=true" to an entity field?

I think Media entity hasn't the option... maybe?

**Comment by sandergo90** [comment]
Hi @ismaserrano ,

Sorry it should be a one to many relationship like this on the ImageGallery entity.

 /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="path\to\WebsiteBundle\Entity\ImageGalleryImage", mappedBy="imageGallery", cascade={"all"}, orphanRemoval=true)
     * @Assert\Valid()
     */
private $images;

And then on your ImageGalleryItem entity:

/**
     * @var ImageGalleryPagePart
     *
     * @ORM\ManyToOne(targetEntity="path\to\WebsiteBundle\Entity\ImageGallery", inversedBy="images", fetch="EAGER")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="image_gallery_id", referencedColumnName="id")
     * })
     */
    private $imageGallery;

Cheers!

**Comment by ismaserrano** [comment]
Hi @sandergo90,

Thank you. I see that in your code you are working with pageparts... is not the case.
I understand the entity relationship, how to focus multiple images with an entity, but I'm trying to implement MediaBundle of Kunstmaan automatically, and has not functionality for multiple choosing. I think I'll trying to extend MediaBundle.

**Comment by sandergo90** [comment]
Hi,

It does not make any difference if you are using pageparts or custom entities because a pagepart is also just an entity. 

MediaBundle has indeed no support of multiple images out of the box. Therefore with the entity in between it can work ;)

Cheers

**Comment by ismaserrano** [comment]
Hi @sandergo90,

Thank you! but... your example is not clear at all. You're only create PagePart to relate with ImageGallery entity... where is MediaBundle relationship?

Cheers!
