### ISSUE TITLE
Missing assets after install

### ISSUE THREAD

**Issue by w3q** [Kunstmaan/KunstmaanBundlesCMS#1465]
After installation of kunstmaan like mentioned in the installation manual, the styles are broken.

I did 2 installations, on mac and on the windows, but both are broken the same way.
See screenshot.
<img width="1280" alt="snimka obrazovky 2017-02-28 o 11 30 27" src="https://cloud.githubusercontent.com/assets/1138670/23399577/5cf7661a-fda9-11e6-9c2a-cb6ee1f6e47b.png">

I remember I had this issue before, but can not remember what was the fix for that.

Thanks for all suggestions.

**Comment by Devolicious** [comment]
Hi @w3q,

Since only your images are not rendering it's likely a permission problem on your `web/uploads` folder. We did 3 new bundles installs yesterday and everything went fine. 
Hope this helps.

Cheers.

**Comment by w3q** [comment]
Actually, looks like the assetic is not working properly for me, as I have whole admin without the styles for example.

**Comment by indigo-valdas** [comment]
Run command Assetic:dump,  this command will generate all admin assets.
