### ISSUE TITLE
Fix cmf routing bundle

### ISSUE THREAD

**Issue by Devolicious** [Kunstmaan/KunstmaanBundlesCMS#1467]
cmf routing changed it's requirements and because of this a new install fails

**Comment by iknowfoobar** [comment]
We are still having a problem with this, When will v4.0.2 be released? Currently we can't do any composer updates or start any new projects on v4?

**Comment by Devolicious** [comment]
Hi @iknowfoobar,

v4.0.2 will be released this week. Because of this issues we also decides to start a new major release and drop php 5.5 support and implement the latest release of the cmf routing bundle.

**Comment by iknowfoobar** [comment]
Hi @Devolicious, thanks. Yeah causing problems here as I have developers who can't install any Kunstmaan CMS websites to work on ;)

**Comment by iknowfoobar** [comment]
Hi @Devolicious, sorry to keep asking. Any word on the v4.0.2 release yet, we still can't install or update any of our v4 Kunstmaan websites?

**Comment by Devolicious** [comment]
Hi @iknowfoobar,

I'm sorry about that. Should have happened last week but didn't come to it. If nothing gets in the way, I'll do a new release tomorrow.

**Comment by Devolicious** [comment]
Hi @iknowfoobar,

The new 4.0.2 release is available!

Cheers

**Comment by iknowfoobar** [comment]
Hi @Devolicious , this doesn't appear to have been fixed. We still can't install KunstmaanCMS without manually changing the minimum stability to 'dev' which we aren't really comfortable doing on live websites?
Or have I missed something?

Cheers

**Comment by iknowfoobar** [comment]
Actually changing the stability to 'dev' just puts us back to the same error as previously. Sorry I hadn't let it finished before commenting ;)

**Comment by Devolicious** [comment]
@iknowfoobar, which error? I did a new install yesterday and it worked like a charm. But you're right though about the dev stability. Our 4.0 will never be able again to run in stable mode due to the conflict with `cmf-routing`. The good news is that we are going to do a pre-release of the 5.0 version tomorrow or the next day where that problem will be solved.

**Comment by iknowfoobar** [comment]
Hi @Devolicious the error I got before changing the stability to 'dev' was:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for symfony-cmf/routing-bundle dev-master -> satisfiable by symfony-cmf/routing-bundle[dev-master].
    - symfony-cmf/routing-bundle dev-master requires symfony-cmf/routing ^2.0 -> satisfiable by symfony-cmf/routing[2.0.0, 2.0.0-RC1, 2.0.0-RC2, 2.0.0-RC3, 2.0.x-dev] but these conflict with your requirements or minimum-stability.
  Problem 2
    - kunstmaan/bundles-cms 4.0.0 requires symfony-cmf/routing-bundle dev-master -> satisfiable by symfony-cmf/routing-bundle[dev-master].
    - kunstmaan/bundles-cms 4.0.1 requires symfony-cmf/routing-bundle dev-master -> satisfiable by symfony-cmf/routing-bundle[dev-master].
    - kunstmaan/bundles-cms 4.0.2 requires symfony-cmf/routing dev-master#b93704ca098334f56e9b317932f21a4362e620db as 2.0 -> satisfiable by symfony-cmf/routing[dev-master] but these conflict with your requirements or minimum-stability.
    - symfony-cmf/routing-bundle dev-master requires symfony-cmf/routing ^2.0 -> satisfiable by symfony-cmf/routing[2.0.0, 2.0.0-RC1, 2.0.0-RC2, 2.0.0-RC3, 2.0.x-dev] but these conflict with your requirements or minimum-stability.
    - Installation request for kunstmaan/bundles-cms ~4.0.0 -> satisfiable by kunstmaan/bundles-cms[4.0.0, 4.0.1, 4.0.2].
```

Changing it to 'dev' I get:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: symfony-cmf/routing[2.0.x-dev, 1.4.0].
    - Can only install one of: symfony-cmf/routing[2.0.x-dev, 1.4.0-RC1].
    - Can only install one of: symfony-cmf/routing[2.0.x-dev, 1.4.0-RC2].
    - Can only install one of: symfony-cmf/routing[2.0.x-dev, 1.4.0-RC3].
    - symfony-cmf/routing-bundle dev-master requires symfony-cmf/routing ^2.0 -> satisfiable by symfony-cmf/routing[2.0.x-dev].
    - Installation request for symfony-cmf/routing-bundle dev-master -> satisfiable by symfony-cmf/routing-bundle[dev-master].
    - Installation request for symfony-cmf/routing ~1.4 -> satisfiable by symfony-cmf/routing[1.4.0, 1.4.0-RC1, 1.4.0-RC2, 1.4.0-RC3].
```

I haven't made any changes to my root composer.json other than adding the minimum stability line, do I need to change that one too?

**Comment by Devolicious** [comment]
@iknowfoobar, can you make sure that you've updated the requirements in your composer.json so that they match the following:
```
"kunstmaan/bundles-cms": "~4.0.2",
"symfony-cmf/routing-bundle": "dev-master#09a74726050e02eb5eafb5d3d40fe411ab934a37 as 2.0",
"symfony-cmf/routing": "dev-master#b627f34920087c8e35582f963fa6ccd622b1342b as 2.0",
```

Those make it possible to update your vendors. I know it's not pretty but we had to downgrade because the php requirements and that would conflict with our new release process. That's why the v5.0 will be released.

**Comment by iknowfoobar** [comment]
@Devolicious, thanks that has worked for me now. Looking forward to v5.0!

**Comment by Devolicious** [comment]
@iknowfoobar, awesome! Glad to help.
