### ISSUE TITLE
Can't use KunstmaanFormBundle > Sequence Number error

### ISSUE THREAD

**Issue by indigo-valdas** [Kunstmaan/KunstmaanBundlesCMS#1472]
Than I click, Modules > Form Submission I receive this exception:

An exception has been thrown during the rendering of a template ("[Semantical Error] line 0, col 210 near 'sequenceNumber': Error: Class Kunstmaan\NodeBundle\Entity\Node has no field or association named sequenceNumber") in KunstmaanAdminListBundle:AdminListTwigExtension:widget.html.twig at line 5.

I have successfully created ContactPage, but it cant be show due to Service Unavailable.

Can you give some highlight how to set up Form Submission properly?

**Comment by Devolicious** [comment]
Hi @indigo-valdas,

Did you execute the `kuma:generate:formpage` command? This command generates your form page where you can start using the form submissions. Does your `ContactPage` extends the `AbstractFormPage` or implements the `FormPageInterface` interface? One of those is needed to work properly with the formsubmissions.
