### ISSUE TITLE
dependencies problems on symfony3

### ISSUE THREAD

**Issue by adrianaapetrei** [Kunstmaan/KunstmaanBundlesCMS#1478]
Hi. I have a problem when adding kunstmaan/bundles-cms v4.0.* on a sf v3.* project: it seems that symfony-cmf/routing-bundle: dev-master is now at v2.* and other dependencies requires v1.4*. Is there a way to make it work? Thanks!

**Comment by Devolicious** [comment]
Hi @adrianaapetrei,

We are aware of this problem. There will be a new version release shortly to solve this problem. You can read more about it here #1467
