### ISSUE TITLE
Can get another type page from other type page?

### ISSUE THREAD

**Issue by ismaserrano** [Kunstmaan/KunstmaanBundlesCMS#1487]
Hi,
I'm trying to get FormPage like a form (not like a page) to put into ContentPage. It is possible?

**Comment by Devolicious** [comment]
Hi @ismaserrano,

A formpage is very much a page where you can put content. The added functionality is that you can build a form within that formpage. You don't need to build a form inside a form page and than put it inside a contentpage.

**Comment by ismaserrano** [comment]
You're right, but, if I don't want a type page extend from FormPage with thank you field, from and to email field... only another type of page with a form inside but that form with all FormPage functionallity?

**Comment by Perni1984** [comment]
@ismaserrano if you want to put a form on your ContentPage you have basically 2 options:

1. don't use a ContentPage, but use a FormPage instead and build the form there with all available form PageParts
2. Create a FormPagePart that you can use as PagePart on your ContentPage and have an "route" or action parameter in this PagePart that you put in the rendered template e.g. 

```php
<form action="{{ url(resource.route)}}"> 
    <!-- your form html code -->
</form>
```

You can then write your own Controller and register your own route to handle the form submission on your own - but this is basic Symfony stuff not directly related to KunstmaanCms.
