### ISSUE TITLE
Allow for wildcards in in redirects

### ISSUE THREAD

**Issue by bakie** [Kunstmaan/KunstmaanBundlesCMS#1488]
E.g. Origin: /nl/my-blog/* Target: /nl/blog/*

**Comment by mlebkowski** [comment]
bakie, wouldn’t this mean changing the redirect architecture entirely, since the whole redirecting is done at the routing level now?

**Comment by bakie** [comment]
@mlebkowski not sure. This is just a thought I had, so we first need to see if this is doable and how :)

**Comment by delboy1978uk** [comment]
we can now add a redirect on this feature pull request like so:
`/some-url/etc/*`  can redirect to `/somewhere-else/*`
Currently, the wildcard will only work at the end of the URL.

**Comment by Numkil** [comment]
Closing because feature has been merged. See PR for more information.
