### ISSUE TITLE
Broken image url in preview wysiwyg

### ISSUE THREAD

**Issue by bakie** [Kunstmaan/KunstmaanBundlesCMS#1503]
When you have a text area and want to add an image you get broken links because of the way the url's are structured now (e.g. <img alt="" src="[M6]" />).
![broken_image_wysisyg](https://cloud.githubusercontent.com/assets/1597449/25472213/9a59de80-2b2a-11e7-823d-22756b8fc77e.png)

**Comment by sandergo90** [comment]
Fixed in https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/1492

**Comment by bakie** [comment]
Fixed with https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/1492
