### ISSUE TITLE
Styleguide CSS fix

### ISSUE THREAD

**Issue by fchris82** [Kunstmaan/KunstmaanBundlesCMS#1508]
The generated pages seem to be wrong now.

![kmtest - forms](https://cloud.githubusercontent.com/assets/1598178/25661809/5f630fe4-3012-11e7-8619-aa27bc30ee5e.png)

**Comment by Devolicious** [comment]
Hi @fchris82,

We are currently looking to switch out hologram for something newer and better. If you want to fix this you can submit a PR but know that changes are coming for this :)
