### ISSUE TITLE
StructureNode isOnline=false breaks search indexing

### ISSUE THREAD

**Issue by mwoynarski** [Kunstmaan/KunstmaanBundlesCMS#1509]
As the search bundle is configured to ignore any offline page, and its children, the default `isOnline=false` in [StructureNode](https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/src/Kunstmaan/NodeBundle/Entity/StructureNode.php#L17) prevents the search bundle from indexing any page that is a child of a structure node.

This can be remedied easily enough by changing the return value for isOnline() to `true` in either StructureNode itself or any of your own classes that extend it, but I'm hesitant to globally make that change in a PR because it may have repercussions beyond my own use cases.

I do consider this a bug, though, because the default behaviour renders the search bundle completely unusable.

**Comment by Devolicious** [comment]
Hi @mwoynarski,

Thanks for reporting this bug. We'll look into it.

**Comment by treeleaf** [comment]
I have created a pull request : https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/1550
