### ISSUE TITLE
BehatTestPage Class

### ISSUE THREAD

**Issue by Perni1984** [Kunstmaan/KunstmaanBundlesCMS#1512]
Hi all,

I am starting with behat tests for our own projects now and I am wrapping around my head, why you created a BehatTestPage class, when I could do the same functionality with a "standard" ContentPage. Could somebody of the Kunstmaan Core developers shed some light on the decision - did I oversee something?

Thanks!

**Comment by Devolicious** [comment]
Hi @Perni1984, 

The `BehatTestPage` makes it easier to test in some scenarios. For example. If you have a setup where you have pageparts that do not belong to the main region. 
When they are only available for a specific region on a specific page type, then you can use the `BehatTestPage` where all pageparts are allowed.
