### ISSUE TITLE
Make Authors optional in Article generation

### ISSUE THREAD

**Issue by henrypenny** [Kunstmaan/KunstmaanBundlesCMS#1513]
I use the Article generator all the time, but I almost always want to remove the Author code that is generated. It would be great if this was optional during generation.

**Comment by Devolicious** [comment]
Hi @henrypenny,

We will add this as a feature request to our roadmap.

Thanks for contributing!

**Comment by Devolicious** [comment]
@henrypenny this one has been fixed in the rewrite of the article bundle on the 5.0 version
