### ISSUE TITLE
[AdminBundle] MediaTokenTransformer issue with TextPagePart

### ISSUE THREAD

**Issue by peterbxyz** [Kunstmaan/KunstmaanBundlesCMS#1514]
What is the logic behind the ```MediaTokenTransformer```?

Right now it is not working as expected with TextPagePart.

Scenario:

1, We select an image, the data-src is /uploads/media/592d25e1709db/big-jpg.jpg?token=[M144]
2, In the editor window it is 

```<img alt="" data-cke-saved-src="/uploads/media/592d25e1709db/big-jpg.jpg?token=[M144]" src="/uploads/media/592d25e1709db/big-jpg.jpg?token=[M144]" style="width: 4262px; height: 3412px;">```

3, After save the ```MediaTokenTransformer``` set the src to be the token, so the img is going to be:

```<img alt="" src="[M144]" style="height:3412px; width:4262px" data-src="/uploads/media/592d25e1709db/big-jpg.jpg?token=[M144]">```

Happens in https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/src/Kunstmaan/AdminBundle/Form/MediaTokenTransformer.php#L56

@sandergo90 @Devolicious do we missed something?

**Comment by peterbxyz** [comment]
If there is more then one img tag it also gives a 500.

**Comment by wesleylancel** [comment]
We're getting 500's on all TextPagePart's being added on the 5.x-dev branch.

**Comment by Devolicious** [comment]
The mediatoken transformer has been introduced to fix the problem that images are not displayed in the editor because the src is a token. @peterbxyz, is it a new install of did you update to this instance?

**Comment by sandergo90** [comment]
Hi,

It's fixed in the following PR: https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/1517

The 500 error when adding a new text PP was already resolved in the 4.0 branch but was not yet upmerged to the 5.0 branch. So this will also be fixed ;)
