### ISSUE TITLE
Translating missing strings

### ISSUE THREAD

**Issue by mablae** [Kunstmaan/KunstmaanBundlesCMS#1523]
Hello Team, 

I would love to help translating missing strings into german. 
Is there a standard procedure to follow or even an online tool like weblate? 

How can I contribute? Ping @jockri

**Comment by mablae** [comment]
Okay, I have now started translating missing strings to german language. 

Should I provide a PR on that?

**Comment by Devolicious** [comment]
Hi @mablae,

Yes you are very welcome to do so. To submit a PR you can just follow our [contribution guide](https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/docs/99-02-pull-requests.md)

**Comment by mablae** [comment]
Hey @Devolicious , 

I am already half done. 😄  I am using `jms/translation-bundle` to extract the strings. 

Quick question: Which branch should I use as a base? It's kind of a bugfix, isn't it? 

I am currently using the `v4.0.2`

**Comment by Devolicious** [comment]
Hi @mablae,

It's fair to say that missing translations are a bugfix :) So for that you should use the `4.0` branch as the base for your PR.

**Comment by sandergo90** [comment]
As PR #1651 says, the translation will be soon available with crowdin. If you want to add more german translations, they can be added there.
