### ISSUE TITLE
Relate custom entity to Custom Page Type

### ISSUE THREAD

**Issue by mablae** [Kunstmaan/KunstmaanBundlesCMS#1536]
Hi folks, 

I have a custom page type entity "StorePage". 

Now I want to relate to these store pages from an custom `Event` entity. 
(One Store can have many Events)

But internally all the `Node*` entities confuse me. Would I relate against a NodeTranslation or NodeVersion? 

Another way doing this, would be mapping the store via a pagepart and dont have a custom page type? 

How to do this? Any idea appreciated.

**Comment by sandergo90** [comment]
Hi @mablae,

You have to relate against the Node entity and you can use the "NodeChoiceType" as form type for your field on your Event entity.

Cheers

**Comment by mablae** [comment]
Thank you much! This is exactly the answer I needed!!! 🤗

**Comment by sandergo90** [comment]
You're welcome ! ;)

**Comment by mablae** [comment]
Awesome! This is what I ended up with: 

```php

  $builder->add('store', NodeChoiceType::class, [
            'page_class' => [
                StorePage::class

            ],
            'locale' => $this->locale
        ]);


```

Without locale option it was throwing an error in PropertyAccessor... Thanks again!

**Comment by sandergo90** [comment]
Perfect!
