### ISSUE TITLE
[Node][NodeSearch] Child nodes not reindexed after changing parent url

### ISSUE THREAD

**Issue by dannyvw** [Kunstmaan/KunstmaanBundlesCMS#1547]
After changing the parent node url, all childs have still the old url indexed (only affected on search page).

https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/src/Kunstmaan/NodeSearchBundle/EventListener/NodeIndexUpdateEventListener.php#L47

Possible solution, change `$nodeSearchConfiguration->indexNodeTranslation($event->getNodeTranslation(), true);` to `$nodeSearchConfiguration->indexNode($event->getNode(), $event->getNodeTranslation()->getLang());`

**Comment by treeleaf** [comment]
I have modified this in an pull request: https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/1550

**Comment by Numkil** [comment]
Closing because referenced PR is merged
