### ISSUE TITLE
[Suggestion] Extract docs to separate repository

### ISSUE THREAD

**Issue by svenluijten** [Kunstmaan/KunstmaanBundlesCMS#1554]
# Problem
The documentation is currently "hosted" in this repository, which can make it fairly unwieldy to handle pull requests and issues. With [_nearly 90,000 git objects_](https://gist.github.com/svenluijten/b1d9867a5017dec74b2d1e1a747175f9), it's also far from the smallest project to clone locally, which can deter contributors from making what would normally be a relatively simple fix.

# Solution
I propose we extract the `docs/` folder in this project to its own repository here on GitHub. This has the added benefit of being easier to find for (new) contributors (at first I had no idea the docs were even open source!), and you gain a better overview of what's happening to _the code_ in this repo, and what's happening to the docs in the other one.

Obviously the website would also need to be tweaked in that case. Currently I don't know how that is set up (it doesn't appear to be open source?), so I don't know the impact that would have on the current build / deploy process.

**Comment by sandergo90** [comment]
Maybe we should use readthedocs.io for documentation ?

**Comment by svenluijten** [comment]
I have no experience with readthedocs other than being a consumer, but it looks pretty easy to manage as well, it appears to read the `.md` or `.rst` files from a regular GitHub repository, so it fits the opensource-ness pretty well 🙂

**Comment by Numkil** [comment]
Closing because problem is being tackled and first PR has already been merged.
