### ISSUE TITLE
Load bootstrapcdn over HTTPS

### ISSUE THREAD

**Issue by svenluijten** [Kunstmaan/KunstmaanBundlesCMS#1555]
Currently, all pages under https://bundles.kunstmaan.be/documentation are loaded over HTTPS, but they still pull in some HTTP stylesheets from http://netdna.bootstrapcdn.com. This makes Chrome throw some errors in the JavaScript console, as well as show an icon in the URL bar letting the user know about "unsafe" scripts being loaded. The CDN [also supports HTTPS](https://netdna.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css), so the switch should be fairly painless. I would PR this, but the site isn't open source (as far as I can see 😉).

![javascript console](http://i.imgur.com/BiuWsFK.png)
![icon in URL bar](http://i.imgur.com/aZj1oEf.png)

**Comment by delboy1978uk** [comment]
It is indeed a separate website, so I'm afraid I'll be closing closing this issue. I have however let the devs know, so no doubt we'll get it sorted at some point. Thanks for letting us know though!

**Comment by Numkil** [comment]
I'm opening an issue for this on our internal issue tracker. thanks for letting me know.
