### ISSUE TITLE
[MediaBundle] Not all items visible in media chooser thumb view

### ISSUE THREAD

**Issue by dannyvw** [Kunstmaan/KunstmaanBundlesCMS#1565]
If you have remote media added like youtube videos then the list-view returns all items and the thumb-view returns only the items without remote media.

Looks like this line is the problem https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/src/Kunstmaan/MediaBundle/Resources/views/Chooser/chooserShowFolder.html.twig#L197

**Comment by delboy1978uk** [comment]
This ticket I think has been fixed? 
I see a thumbnail for a YouTube video in the Media Thumbnail view!

**Comment by dannyvw** [comment]
I close this ticket, if it does not work I will reopen or create an new issue.
