### ISSUE TITLE
Kunstmaan Adminlist does not support tabs, for SEO and SOCIAL form typ.

### ISSUE THREAD

**Issue by ramini524** [Kunstmaan/KunstmaanBundlesCMS#157]
Is there a way I can use the Seo and Social  Forms and Tabs on AdminList edit and add?
  just like on the Page created on the backend?

**Comment by krispypen** [comment]
@ramini524 I assigned this to the Q2 milestone because it's not so urgent for us. But if you submit a PR before milestone Q1, we maybe can have a look :)

**Comment by woutervandamme** [comment]
https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/349
