### ISSUE TITLE
Pagepart Editor 'add' event target always undefined

### ISSUE THREAD

**Issue by mablae** [Kunstmaan/KunstmaanBundlesCMS#1571]
In the pagePartEditor.js:

https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/src/Kunstmaan/AdminBundle/Resources/ui/js/_pagepart-editor.js#L119 results in `{ target: undefined }`

**Comment by delboy1978uk** [comment]
Can you give us the steps to reproduce this?

**Comment by mablae** [comment]
For example the edit event passes the container as 2nd argument to `executeEvent` function. 
which then can be used to access to emitting container in the listener. 


https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/src/Kunstmaan/AdminBundle/Resources/ui/js/_pagepart-editor.js#L209
