### ISSUE TITLE
[Website] Menu items hidden by fixed height

### ISSUE THREAD

**Issue by svenluijten** [Kunstmaan/KunstmaanBundlesCMS#1572]
On [the website](https://bundles.kunstmaan.be/documentation), opening the menu items `Bundles` -> `Adminlist bundle` and `Bundles` -> `Node bundle`, some items are hidden behind the "Questions"-guy: 

![screenshot](http://i.imgur.com/3VHskZ7.png)

**Comment by jockri** [comment]
Closing this, we are now using Read The Docs: http://kunstmaanbundlescms.readthedocs.io/en/latest/
