### ISSUE TITLE
Sorting pages in the admin doesn't work as expected

### ISSUE THREAD

**Issue by deZinc** [Kunstmaan/KunstmaanBundlesCMS#1576]
When sorting pages with drag & drop in the tree, the reorder is triggered but the pages are reordered wrong.

When debugging, it's clear that this is due to node translations not being found for certain nodes. Hence, the node(translation) does not get the correct new weight. I haven't had the time to delve further into the issue.

**Comment by Numkil** [comment]
Issue non reproducable and hasn't been seen since.
