### ISSUE TITLE
MediaType, mediatype restriction not working properly

### ISSUE THREAD

**Issue by deZinc** [Kunstmaan/KunstmaanBundlesCMS#1577]
If, in a form type, you add a MediaType to the form, with the mediatype property set to "image", it's still possible to upload another file type to the media-chooser (eg. .js, .php,...). This file will appear in the media-chooser (as well as previously hidden files from other types) and become selectable. It's then possible to save this file into the object you were editing with the form.

**Comment by delboy1978uk** [comment]
Appears to have been fixed, No Fault Found

**Comment by sandergo90** [comment]
@deZinc can you check if this issue still occurs?
