### ISSUE TITLE
Fatal error when using Symfony 3.3

### ISSUE THREAD

**Issue by iknowfoobar** [Kunstmaan/KunstmaanBundlesCMS#1578]
Hi, if I try to use Symfony 3.3 with Kunstmaan I get the following Fatal error when using any console commands:

```
[RuntimeException]                                                                                                                       
  An error occurred when executing the "'cache:clear --no-warmup'" command:                                                                
  Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\InvalidArgumentException: Invalid key "logger" found in arguments  
   of method "__construct()" for service "kunstmaan_admin.consolelogger.listener": only integer or $named arguments are allowed. in /kuma/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/ResolveNamedArgumentsPass.php  
  :47  
```
It is easy to replicate this by installing Kunstmaan using 

```
$ composer create-project kunstmaan/bundles-standard-edition project
```
and then immediately running a composer update, which will cause it to install Symfony 3.3.
Limiting back to Symfony 3.2 resolves the problem.

This happens in both PHP 7.0 and 7.1.

Thanks
Giles

**Comment by sandergo90** [comment]
Hi @iknowfoobar ,

It's indeed a bug in the bundles.

I've created a PR for this.

https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/1579

Cheers
