### ISSUE TITLE
Doctrine extensions not fully installed?

### ISSUE THREAD

**Issue by JoakimLofgren** [Kunstmaan/KunstmaanBundlesCMS#158]
Hey,

You use a few `@Gedmo\Translatable` entity columns in the CMS, for instance on `Kunstmaan\MediaBundle\Entity\Folder`.

This doctrine extension does not seem to be properly _"installed"_ though, if you look at the instructions here:
https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/symfony2.md#ext-mapping

E.g. missing services for the listeners and the DoctrineExtensionsListener class.

I'd like to use the `@Gedmo\Translatable` functionality on some of my entities.
Only the tree listener is installed with the node bundle, but the rest aren't.

If you want I could make a pull request to install the ones defined in the [config](https://github.com/Kunstmaan/KunstmaanBundlesStandardEdition/blob/master/app/config/config.yml)

**Comment by wimvds** [comment]
They should be properly installed if you started from the standard edition...

https://github.com/Kunstmaan/KunstmaanBundlesStandardEdition/blob/master/app/config/config.yml#L49-L78

**Comment by JoakimLofgren** [comment]
Ah right, you use the StofDoctrineExtensionsBundle..
https://github.com/stof/StofDoctrineExtensionsBundle/blob/master/Resources/doc/index.rst

Do I need to do something special to have it work in my admin list ?

**Comment by JoakimLofgren** [comment]
Aha, figured it out.. You just need to change language in the backend.

Not very apparent that the field is translatable in the admin list. :(
