### ISSUE TITLE
Possibility to extend / override AbstractFormPagePart

### ISSUE THREAD

**Issue by KevinSleegers** [Kunstmaan/KunstmaanBundlesCMS#1580]
Hi,

I would like to know if it is possible to extend / override the default AbstractFormPagePart. 
By default this provides the option to set a label, but I would also like to be able to define a info text.

Normally I would just create a custom Entity and use my own pageparts to extend that, but this is an existing website. So that's not really an option as I don't want to update the entire database to fix existing pageparts.

Would love to know what is possible, I'm using Kunstmaan 3.6. 

Thanks in advance,
Kevin

**Comment by sandergo90** [comment]
Hi @KevinSleegers ,

When you would change the default AbstractFormPagePart, you will also have to update the entire database for your existing pagepart. The best solution here is to add a custom abstract class like you said and let your pageparts extend this one. 

Cheers
