### ISSUE TITLE
Required fields aren't checked when publishing a node

### ISSUE THREAD

**Issue by svenluijten** [Kunstmaan/KunstmaanBundlesCMS#1581]
When adding a subpage to a node, it creates an unpublished node entity which the user is then redirected to to edit. When I then click on "Publish", the page is published without further questions, while I expected it to check if the required fields are met (`@Assert\NotBlank()`'s on the entity).

A good solution for this would be to make the "publish" action also "save" the entity, so that the validation fires and the user gets an error message if they haven't filled in all required fields.

**Comment by Numkil** [comment]
@svenluijten This is indeed a problem. I have added it to our roadmap to be fixed. I will keep you up to date with progress when we have some time to start working on it.

**Comment by Devolicious** [comment]
Not really a roadmap kind of issue, it's more bugfix imho.
