### ISSUE TITLE
Hardcoded validation message domain in the AdminBundle

### ISSUE THREAD

**Issue by deZinc** [Kunstmaan/KunstmaanBundlesCMS#1584]
The file KunstmaanAdminBundle/views/Form/fields.html.twig sets the translation domain for the validation messages hardcoded to "validators" while symfony allows the use of a custom domain for these messages.

**Comment by delboy1978uk** [comment]
According to Kevin, the second argument was no longer necessary, so I tested by taking both the args out, and we still get our correct validation messages, so I will push up the changes!

**Comment by deZinc** [comment]
It's not about getting our correct validation messages in the regular way Kevin, it's about being able to overrule the regular validation domain with your own domain. For this you need the second parameter.

**Comment by delboy1978uk** [comment]
@Numkil ^

**Comment by Numkil** [comment]
Why not just override the file when you want custom behaviour? Putting extra configuration and controller logic in the bundles for a file that so easily can just be overwritten in projects seems unnecessary. I prefer removing it altogether and when you want to use a custom validator domain you just override the fields.html.twig file.

**Comment by delboy1978uk** [comment]
makes sense?

**Comment by deZinc** [comment]
True enough but I just found it a little strange that our bundles block off custom symfony behaviour. So you can easily set the validation messages domain in symfony, by default, but our bundles can't use it. Just doesn't feel right. All you have to do, to make it work, is use that default symfony parameter.

**Comment by Numkil** [comment]
@deZinc whats that default parameter you need to use? I thought just not passing a domain explicitly to trans method would also make it use the default symfony configured domain.

**Comment by deZinc** [comment]
@Numkil, most probably that's the case. If you remove the hardcoded part, the default parameter could work.

**Comment by delboy1978uk** [comment]
In app/config/parameters.yml 
```
parameters:    
    validator.translation_domain: messages
```
I don't think we need to add anything in the twig file, setting this should be enough, and that's the end user's concern, not ours 😊

**Comment by delboy1978uk** [comment]
I can confirm that we don't need to pass the domain in, I overrode the `fos_user.username.already_used ` translation, and tried to add myself again as a new user.  :-D
![image](https://user-images.githubusercontent.com/2684575/33559435-0737b62c-d90d-11e7-84ae-63eff25c33cb.png)
Also, I love the fact we can add smileys! 😛
Looks like this is good to merge then!

**Comment by dannyvw** [comment]
Removing the `validators` translation domain from the template breaks our code. We have already set an custom translation domain. Removing the translation domain doesn't work either.

```
            'constraints' => array(
                new Constraints\Callback(function($object, ExecutionContextInterface $context) use($data) {
                        $context->buildViolation('sort.invalid_combination')
                            ->setTranslationDomain('validators')
                            ->addViolation();
                }),
            ),
```

Please document this change in the upgrade file.
