### ISSUE TITLE
With the generator, it's not possible to create pageparts with fields "case" or "label"

### ISSUE THREAD

**Issue by krispypen** [Kunstmaan/KunstmaanBundlesCMS#159]
The reserved word list is wrong.

**Comment by denbatte** [comment]
I will pick this up ... just going to paste the file reference here so I can find things quickly later.

Line:
Kunstmaan/GeneratorBundle/Generator/KunstmaanGenerator.php:79

**Comment by woutervandamme** [comment]
when creating fields with name case or label you get a syntaxErrorException, so the reserved keyword list is right.

     [Doctrine\DBAL\Driver      \PDOException]                                                                                                                                                                                                                               
       SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax;     check the manual that corresponds to your MySQL server version for the right syntax to use near 'case VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTE  
       R SET utf8 COLL' at line 1

**Comment by krispypen** [comment]
I can create a test database myself with this query:
```
CREATE TABLE `tests` ( `label` varchar(30) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8
```

So it should be possible, but doctrine doesn't do quoting :( stupid...

http://doctrine-orm.readthedocs.org/en/latest/reference/basic-mapping.html#quoting-reserved-words
