### ISSUE TITLE
[Admin][Pageparts Consecutive urlchoosers in page

### ISSUE THREAD

**Issue by Numkil** [Kunstmaan/KunstmaanBundlesCMS#1594]
Best way to reproduce ->

add ButtonPagePart
add second  ButtonPagePart.
adding a third, fourth... all will trigger the same bug on the pagepart before it in the list.
try and change the link_type on either one of the ButtonPageParts except for the last one and the url field will dissapear in the pagepart you chose to change the link_type.

**Comment by Numkil** [comment]
@sandergo90 

I seem to be stuck on this issue. I just can not seem to figure out why this behaviour is happening. Do you think you could take a look at the bug when you have time?

**Comment by sandergo90** [comment]
Sure I will 😉

**Comment by delboy1978uk** [comment]
issue doesn't occur if both buttons are already saved, continuing analysis

**Comment by delboy1978uk** [comment]
or if at least one is saved, it only appears to be when both are new

**Comment by delboy1978uk** [comment]
![image](https://user-images.githubusercontent.com/2684575/33332092-9dfd3e32-d463-11e7-80c9-ea499ed6bbf8.png)
This is the culprit. Looks like JavaScript isn't sending sufficient keys. Both are new, so the array needs both values! Changing the key to the other one seemed to fix it, both rendered correctly!

**Comment by delboy1978uk** [comment]
think we should add the frontend tag to this

**Comment by acrobat** [comment]
Fixed in #2376
