### ISSUE TITLE
Symfony bundle inheritance will be deprecated in 3.4

### ISSUE THREAD

**Issue by dannyvw** [Kunstmaan/KunstmaanBundlesCMS#1599]
See https://github.com/symfony/symfony/issues/24048 for more information

**Comment by Numkil** [comment]
@dannyvw This will have no impact on how to use the bundles since we do not use that functionality. Basically if you are doing this in one of your custom code you can just drop the getParent() method since its not necessary anymore.

**Comment by dannyvw** [comment]
@Numkil This is used in Kunstmaan, see https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/src/Kunstmaan/AdminBundle/KunstmaanAdminBundle.php

**Comment by Numkil** [comment]
@dannyvw For now everything still works as originally designed. Its only from Symfony 4 that it will be removed. Therefore we will make sure that in Bundles 6.0 we will rewrite this code.
