### ISSUE TITLE
Rename of ActionsMenuBuilder setIsEditableNode broke backward compatibility between 3.0.0 and 3.0.1

### ISSUE THREAD

**Issue by mwoynarski** [Kunstmaan/KunstmaanBundlesCMS#160]
In NodeBundle/Helper/Menu/ActionsMenuBuilder.php:201, the function setIsEditableNode was renamed between 3.0.0 and 3.0.1; as this *should be* a minor patch release, I feel this was in error.

The end result is that anyone who has written code against the 3.0.0 version of the bundle now has to create a new branch to support 3.0.1; in my opinion, a developer shouldn't be required to do that for anything less than minor version increment of 3.0 -> 3.1.

Patch releases should never introduce a change that breaks existing code.

**Comment by roderik** [comment]
yeah, this was my bad. Will take better care.
