### ISSUE TITLE
The links in the contributing.md file are dead

### ISSUE THREAD

**Issue by NindroidX** [Kunstmaan/KunstmaanBundlesCMS#1601]
https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/.github/CONTRIBUTING.md

**Comment by delboy1978uk** [comment]
Does this still need updating? I see a closed pull request that wasn't merged, I can fix it right now if you like https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/1603

**Comment by NindroidX** [comment]
Nope, it should be fixed now ( created a new PR which targeted the right branch).
