### ISSUE TITLE
[AdminBundle] Something goes wrong when minimizing a region in the admin interface

### ISSUE THREAD

**Issue by NindroidX** [Kunstmaan/KunstmaanBundlesCMS#1602]
The region does not collapse properly:

![screen shot 2017-09-26 at 6 46 05 pm](https://user-images.githubusercontent.com/3533236/30876943-60026d7e-a2f8-11e7-9f6b-2ecb5395aa5a.png)

**Comment by mtnorthrop** [comment]
@NindroidX This is actually the way "minimize" is programmed to work; it sets the section height to `height: 11.8rem;`.

I think, if you'd like a different behavior, you would have to open a new feature request and see if Kunstmaan is interested in changing this.

Hope that helps.

**Comment by jockri** [comment]
Indeed, it was developed like this.

@NindroidX If you want to propose something else, please do a PR.

Closing this for now.
