### ISSUE TITLE
Move scripts to the head and use async / defer

### ISSUE THREAD

**Issue by Windvis** [Kunstmaan/KunstmaanBundlesCMS#1617]
Async / defer attributes on script elements are widely supported now (do we even support < IE11?). We can replace the oldschool 'load scripts at the bottom of the body' style of script loading by adding the scripts to the head and using the appropriate attribute.

More info: 
https://www.html5rocks.com/en/tutorials/speed/script-loading
http://www.growingwiththeweb.com/2014/02/async-vs-defer-attributes.html

**Comment by sandergo90** [comment]
@dbeerten do we still need have work on this?
