### ISSUE TITLE
Getting 503 Service Unavailable when logging in.

### ISSUE THREAD

**Issue by philmmoore** [Kunstmaan/KunstmaanBundlesCMS#1619]
What would cause a 503 error when logging in. The login page loads as expected but as soon as I hit submit and the browser gets routed through admin/login_check I get the 503 and the errors don't appear to be being logged. 

Have you seen this error before at all?

**Comment by Devolicious** [comment]
Hi @philmmoore, 

Mostly when you get an error during login it has something to do with your app that is not able to write you sessions to the filesystem.

**Comment by philmmoore** [comment]
Thanks for the quick response. I'm not actually familiar with Symfony which doesn't help, nor the CMS. I'm actually picking up the project, everything runs locally so that sounds like a plausible explanation. Does symfony write to a file based session driver by default and if it does where can I find it?

**Comment by Devolicious** [comment]
Yes the native session handler will use the filesystem. Here you can find the documentation to configure it with other handlers https://symfony.com/doc/current/reference/configuration/framework.html#session

**Comment by philmmoore** [comment]
Turns out that it was actually caused by the logs directory that was a symbolic link and not writable.

Thanks for your help @Devolicious
