### ISSUE TITLE
$this->setListTemplate() is useless

### ISSUE THREAD

**Issue by delboy1978uk** [Kunstmaan/KunstmaanBundlesCMS#1636]
The AbstractPageAdminListConfigurator has a hard-coded view, so using setListTemplate() is useless and the only way to get around it is to override the method in the child class.

The solution is to set that as a default in a property, and get the abstract classes method to return that instead.

I'll code the fix and send a pull request, but which branch shall I do that from, 4.0, or 5.0 ?

**Comment by sandergo90** [comment]
@delboy1978uk I think this is just the way that our abstract classes our working at the moment. If you want to change the template, you should override the getListTemplate method.

**Comment by delboy1978uk** [comment]
Well yes, which is why the`setListTemplate()` method is useless! 
We either fix it or remove it then? Fixing it wont break anything, it will behave exactly the same.

**Comment by sandergo90** [comment]
Oh I see ;) Maybe it's a better way to remove the setListTemplate function then. But we have to make some changes then to the PopupAdminListConfigurator for example. And then it will be a breaking change so we have to make the PR on the 5.0 branch. What do you think?

**Comment by delboy1978uk** [comment]
I'd be wary of removing it, despite its apparent non-functionality, but the fix is really simple, to move the string returned in the getListTemplate() method to a property. Then the setter would work, and any classes overriding etc would behave as normal.

**Comment by sandergo90** [comment]
@delboy1978uk Super, if you have the time for it, please do ;)

**Comment by delboy1978uk** [comment]
Ok I'll sort it when I get the chance! :-D

**Comment by delboy1978uk** [comment]
https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/1642

**Comment by Numkil** [comment]
Closing because PR merged.
