### ISSUE TITLE
Lockable entity check is broken

### ISSUE THREAD

**Issue by delboy1978uk** [Kunstmaan/KunstmaanBundlesCMS#1640]
https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/src/Kunstmaan/AdminListBundle/Controller/AdminListController.php#L501

This should be &&, not ||.

**Comment by Numkil** [comment]
Pull request is already waiting review
#1631

**Comment by Numkil** [comment]
Fix is merged :)
