### ISSUE TITLE
Indices has to be unique in SQLite

### ISSUE THREAD

**Issue by WouterJ** [Kunstmaan/KunstmaanBundlesCMS#166]
In MySQL, indices have to be unique for each table. However, for SQLite, it is required to have unique indices for the whole database.

As both the [`Folder`][1] and [`Node`][2] entities have an index called `idx_internal_name`. This causes SQLite to fail creating the schemas.

I would propose to use the entity name as a prefix: `idx_folder_internal_name`, `idx_node_internal_name`, etc.

 [1]: https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/5e3d7b7832426b09dc79f792ddd1d8bfd79213dc/src/Kunstmaan/MediaBundle/Entity/Folder.php#L17
 [2]: https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/01263b11e48f52b413a77038b092bd5e41566482/src/Kunstmaan/NodeBundle/Entity/Node.php#L17

**Comment by WouterJ** [comment]
Same applies to:

 * `idx_name` ([`Media`](https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/d7dd6bc7f90a28bd4f507db096f5597aca95912e/src/Kunstmaan/MediaBundle/Entity/Media.php#L14), [`Folder`](https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/5e3d7b7832426b09dc79f792ddd1d8bfd79213dc/src/Kunstmaan/MediaBundle/Entity/Folder.php#L18))
* `idx_deleted` ([`Media`](https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/d7dd6bc7f90a28bd4f507db096f5597aca95912e/src/Kunstmaan/MediaBundle/Entity/Media.php#L15), [`Folder`](https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/5e3d7b7832426b09dc79f792ddd1d8bfd79213dc/src/Kunstmaan/MediaBundle/Entity/Folder.php#L19))
* `idx_kuma_search` ([`PageTemplateConfiguration`](https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/e7db693c79ac7e2d073b60655633ae2ef7931967/src/Kunstmaan/PagePartBundle/Entity/PageTemplateConfiguration.php#L13), [`PagePartRef`](https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/e7db693c79ac7e2d073b60655633ae2ef7931967/src/Kunstmaan/PagePartBundle/Entity/PagePartRef.php#L12))

**Comment by roderik** [comment]
ok for me, will you send a pull request?
