### ISSUE TITLE
GraphQL instead of simple API

### ISSUE THREAD

**Issue by cv65kr** [Kunstmaan/KunstmaanBundlesCMS#1676]
I talking with @Numkil and he gave me a advice to create this ticket.

To the heart of the matter.
I am working on GraphQL instead of simple API. I maked some [todo](https://github.com/cv65kr/KunstmaanBundlesCMS/blob/feature-api/src/Kunstmaan/ApiBundle/readme.md) list, but I need some help to ending this feature.

The main assumption is create types, resolvers and mutations on compiller pass level. In some case we need some advanced mutations eg. to create nodes, so it is worth to consider and overriding them.

My branch: https://github.com/cv65kr/KunstmaanBundlesCMS/tree/feature-api

What do you think of my idea? The GraphQL is more flexible and gave us breath of freshness and maybe some kind of prestige :)

@Devolicious, i think is intresting solution and maybe should find in roadmap.

**Comment by sandergo90** [comment]
@cv65kr We have tried to implement the GraphQL API ourselves but we were struggling with the relations between nodes, node translations, ... and pageparts. The mutation that needs to be done with the GraphQL API will be to difficult and not dynamically.  Therefore we choose to make everything with the Rest API (but GraphQL is awesome 😉 )

I've created a feature branch myself for this so you can take a look at what I've done already. https://github.com/sandergo90/KunstmaanBundlesCMS/tree/feature/graphql-api

**Comment by mlebkowski** [comment]
> What do you think of my idea? The GraphQL is more flexible and gave us breath of freshness and maybe some kind of prestige :)

It’s a hype alright ;) What’s the benefit of keeping this in the core instead of a separate bundle?

**Comment by cv65kr** [comment]
@mlebkowski, maybe you have a right about hype but still i think i has a huge potential. Creating the API was one of the assumptions of version 5.0. Is located in Roadmap as integral part of the core - [https://github.com/Kunstmaan/KunstmaanBundlesCMS/issues/1330](https://github.com/Kunstmaan/KunstmaanBundlesCMS/issues/1330) :)

@sandergo90, later check your branch and propably appears some questions :+1:
