### ISSUE TITLE
[Insight] Symfony controller action method should not be too long

### ISSUE THREAD

**Issue by delboy1978uk** [Kunstmaan/KunstmaanBundlesCMS#1691]
> 17% of all actions have more than 20 lines. This violation is raised when more than 10% actions are too long.

- 91 lines for NodeAdminController::editAction() in [**src/Kunstmaan/NodeBundle/Controller/NodeAdminController.php**](https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/0bd1ed48f01d758a9b4da13d3bb177ce8f1fed3e/src/Kunstmaan/NodeBundle/Controller/NodeAdminController.php#L833), line 833
- 88 lines for MediaController::bulkUploadSubmitAction() in [**src/Kunstmaan/MediaBundle/Controller/MediaController.php**](https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/0bd1ed48f01d758a9b4da13d3bb177ce8f1fed3e/src/Kunstmaan/MediaBundle/Controller/MediaController.php#L140), line 140
- 60 lines for AdminListController::doEditAction() in [**src/Kunstmaan/AdminListBundle/Controller/AdminListController.php**](https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/0bd1ed48f01d758a9b4da13d3bb177ce8f1fed3e/src/Kunstmaan/AdminListBundle/Controller/AdminListController.php#L207), line 207
- 52 lines for AdminListController::doAddAction() in [**src/Kunstmaan/AdminListBundle/Controller/AdminListController.php**](https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/0bd1ed48f01d758a9b4da13d3bb177ce8f1fed3e/src/Kunstmaan/AdminListBundle/Controller/AdminListController.php#L103), line 103
- 43 lines for ChooserController::chooserShowFolderAction() in [**src/Kunstmaan/MediaBundle/Controller/ChooserController.php**](https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/0bd1ed48f01d758a9b4da13d3bb177ce8f1fed3e/src/Kunstmaan/MediaBundle/Controller/ChooserController.php#L77), line 77
- 42 lines for UsersController::editAction() in [**src/Kunstmaan/UserManagementBundle/Controller/UsersController.php**](https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/0bd1ed48f01d758a9b4da13d3bb177ce8f1fed3e/src/Kunstmaan/UserManagementBundle/Controller/UsersController.php#L142), line 142
- 41 lines for PagePartAdminController::newPagePartAction() in [**src/Kunstmaan/PagePartBundle/Controller/PagePar

**Comment by jockri** [comment]
Closing this, all SymfonyInsights issues are managed on their interface.
