### ISSUE TITLE
[SearchBundle] SetupIndex command failing

### ISSUE THREAD

**Issue by treeleaf** [Kunstmaan/KunstmaanBundlesCMS#1707]
When you create your own class that implements the Kunstmaan\SearchBundle\Command\SearchConfigurationInterface 

Then you see an error in the console for the setup index and/or populate command with option full

[Symfony\Component\Debug\Exception\UndefinedMethodException]
Attempted to call an undefined method named "checkAnalyzerLanguages" of class X

This is because the checkAnalyzerLanguages method is not part of the interface and this method is called in the command.

**Comment by Numkil** [comment]
references #1708
