### ISSUE TITLE
MultiDomainAdminTwigExtension::switchedHostIsCurrent() always false

### ISSUE THREAD

**Issue by delboy1978uk** [Kunstmaan/KunstmaanBundlesCMS#1714]
```php
return $this->domainConfiguration->getHost() == $this->getSwitchedHost()['host'];
```

`getSwitchedHost()` returns a string:
```php
return $this->domainConfiguration->getHostSwitched();
```

The domain configuration interface returns a string. All we need to do is remove the array part from the end for this to start working.

**Comment by Numkil** [comment]
Closing because PR merged.
