### ISSUE TITLE
There hasn't been much news about the project in bundles.kunstmaan.be.

### ISSUE THREAD

**Issue by henrypenny** [Kunstmaan/KunstmaanBundlesCMS#1719]
I've read that Kunstmaan has been bought out by Accenture. Congratulations!
I've used Kunatmaan Bundles for numerous successful projects and hope that it will continue to be maintained and developed.
It would be great to get some news about the future plans for this awesome project.

**Comment by Devolicious** [comment]
Thanks @henrypenny, we're glad to hear that you like to work with our KunstmaanBundlesCMS. 

Short answer to your question, YES! Most of the communication happens on github itself. If you take a look at the PR list you can see that a lot is happening. You can also follow our roadmap on https://github.com/Kunstmaan/KunstmaanBundlesCMS/projects/2 or you can filter in the issues list with the label roadmap. But you're right, we will also pickup our communication and write more stuff about it on bundles.kunstmaan.be

We want to keep our community alive and kicking so suggestions, feature requests or PR's are always welcome! :)
