### ISSUE TITLE
Untranslated strings in admin and pagepart bundles

### ISSUE THREAD

**Issue by mwoynarski** [Kunstmaan/KunstmaanBundlesCMS#172]
There are numerous instances of untranslated text throughout the backend bundles, either because the English text is hard-coded directly in the template (see ["Add a pagepart"](https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/src/Kunstmaan/PagePartBundle/Resources/views/PagePartAdminTwigExtension/pagepart.html.twig) and the deletion modal in PagePartBundle, or ["Show all"](https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/src/Kunstmaan/AdminListBundle/Resources/views/AdminListTwigExtension/filters.html.twig) in AdminListBundle); or because the text is defined via a configuration file or event listener, and then not translated in the template (see [ tab.title ](https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/src/Kunstmaan/AdminBundle/Resources/views/TabsTwigExtension/widget.html.twig) in AdminBundle).

As it stands, the only way to make a fully bilingual backend is to override the affected files and risk breaking newer versions of the bundles.

**Comment by krispypen** [comment]
Do you think you can create a PR for it yourself?

**Comment by jockri** [comment]
This is already fixed in the latest version of the bundles.
