### ISSUE TITLE
Remove fluent interfaces 

### ISSUE THREAD

**Issue by cv65kr** [Kunstmaan/KunstmaanBundlesCMS#1720]
Based on article [http://ocramius.github.io/blog/fluent-interfaces-are-evil/](http://ocramius.github.io/blog/fluent-interfaces-are-evil/) 
I think we should removed fluent interfaces.

If I am right, from what branch to start?

**Comment by sandergo90** [comment]
Nice article ! Can you give some examples of fluent interfaces that you would want to change ?

**Comment by cv65kr** [comment]
All entities, models, events for start.

**Comment by delboy1978uk** [comment]
Good article!

**Comment by sandergo90** [comment]
@cv65kr After a short discussion we don't see the main advantage for entities and models. We understand that for testing purposes you will have to create multiple mocks, but e don't see that as an issue. Can you give some examples about events where you would change this ?
