### ISSUE TITLE
[Insight] Form types should be in Form/Type folders - in src/Kunstmaan/AdminBundle/Form, line 0

### ISSUE THREAD

**Issue by delboy1978uk** [Kunstmaan/KunstmaanBundlesCMS#1722]
**[in src/Kunstmaan/AdminBundle/Form](https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/918f344a11cb270dd559ffc6574ce6ad750a701b/src/Kunstmaan/AdminBundle/Form#L0)**

> A form type has been found outside Form/Type folder

```

src/Kunstmaan/AdminBundle/Form/
├── ColorType.php
├── DashboardConfigurationType.php
├── GroupType.php
├── MediaTokenTransformer.php
├── RangeType.php
├── RoleDependentUserFormInterface.php
├── RoleType.php
├── UserType.php
└── WysiwygType.php
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/34aece18-3640-47ea-8e9f-96b79919905b/analyses/493)_

**Comment by delboy1978uk** [comment]
Moving the classes into a Type folder would break BC. However, what we can do as a non-BC breaking solution is to create copies of the classes into the Type subdirectory, fix the namespaces on them, take all the logic out of the original classes, make them extend the new ones, and put a `@deprecated` doc block on the class.

**Comment by delboy1978uk** [comment]
Hi Sander, how are you? I take it shifting everything into a folder just to shut up Sensio Insights isn't happening now? :-P Also, say hello to everyone from me please!

**Comment by sandergo90** [comment]
Hi @delboy1978uk, indeed 😄 Everything fine here! I will say hello to the team 😉 ! Cheers!
