### ISSUE TITLE
[Insight] Code should not be duplicated - in …/AbstractArticleAuthorAdminListController.php, line 15

### ISSUE THREAD

**Issue by delboy1978uk** [Kunstmaan/KunstmaanBundlesCMS#1725]
**[in src/Kunstmaan/ArticleBundle/Controller/AbstractArticleAuthorAdminListController.php, line 15](https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/90e14d3f4f4f3078f0388537380cce17e7c0a406/src/Kunstmaan/ArticleBundle/Controller/AbstractArticleAuthorAdminListController.php#L15)**

> The next 91 lines appear both in `src/Kunstmaan/ArticleBundle/Controller/AbstractArticleAuthorAdminListController.php:15` and `src/Kunstmaan/ArticleBundle/Controller/AbstractArticlePageAdminListController.php:16`.

```php
use Symfony\Component\HttpFoundation\Request;

/**
 * The AdminList controller for the AbstractArticleAuthor
 */
abstract class AbstractArticleAuthorAdminListController extends AdminListController
{
    /**
     * @var AdminListConfiguratorInterface
     */
    protected $configurator;
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/34aece18-3640-47ea-8e9f-96b79919905b/analyses/508)_

**Comment by jockri** [comment]
Closing this, all SymfonyInsights issues are managed on their interface.
