### ISSUE TITLE
moving pageparts in another region gives Internal Server error when saving

### ISSUE THREAD

**Issue by samuele-mrapps** [Kunstmaan/KunstmaanBundlesCMS#173]
When I drag and drop a pagepart in a page changing the region I and try to save I get the error in the screenshot.

![error](https://cloud.githubusercontent.com/assets/3425734/6389550/26cd5608-bda5-11e4-9970-3251b4035700.jpg)

**Comment by IbeVanmeenen** [comment]
Also have this...

**Comment by roderik** [comment]
Will be fixed in 3.1
