### ISSUE TITLE
Expansion for the Exception list

### ISSUE THREAD

**Issue by sandergo90** [Kunstmaan/KunstmaanBundlesCMS#1762]
With the new Exception list, we now have a nice overview with all the exceptions.

I would suggest following features:

- [x] Add resolve all button

- [x] Add possibility to exclude certain stuff from the exception list. For example I want to exclude missing images from the list. 

Maybe someone has some more suggestions ?

**Comment by cv65kr** [comment]
@sandergo90, I made the first point :)

**Comment by sandergo90** [comment]
@cv65kr 

![Wow](https://media3.giphy.com/media/xUPGcFiPKVnXmzEU2Q/200w.gif?cid=c94812d05a326b1337396933451aa2de)

**Comment by cv65kr** [comment]
@sandergo90, How you see excluding exceptions? Simple blacklist keys, regexp?

**Comment by cv65kr** [comment]
@sandergo90, second improvment #1765 :)
