### ISSUE TITLE
roadmap: Symfony4/Flex plans/status?

### ISSUE THREAD

**Issue by pgnd** [Kunstmaan/KunstmaanBundlesCMS#1783]
at roadmap

    https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/docs/99-05-roadmap.md

I don't read mention of compat with Symfony4, Flex (Recipe), etc.

Is there a doc with current statement of, or plans 4, status?

**Comment by Devolicious** [comment]
Hi @pgnd,

We're busy updating our roadmap and yes we certainly will support Symfon4 in V6. We will need to do some refactoring before we can make it compatible with SF4 hence the new major version. We are also working on flex skeletons/packs to make it an easy install as it has always been. Unfortunally I cannot give you a specific timeframe on when this all will be ready. But keep checking the repo and the [website](https://bundles.kunstmaan.be) for more updates about it.
