### ISSUE TITLE
[AllBundles] Find and refactor flushes on the postFlush event

### ISSUE THREAD

**Issue by Devolicious** [Kunstmaan/KunstmaanBundlesCMS#1795]
We recently discovered that we can do some optimizations regarding the doctrine events. When you flush the entity manager on a `onPostFlush` event you basically create a loop and things can go ugly fast. So the goal of this issue is to hunt down those pieces of code and try to refactor it to a preFlush event so that you don't create these kind of loops with the benefit of improved performance.

**Comment by deZinc** [comment]
Doesn't seem to be an issue anymore. Fixed in previous release?
