### ISSUE TITLE
Code/ Syntax highlighting for the raw-html pagepart

### ISSUE THREAD

**Issue by well-made** [Kunstmaan/KunstmaanBundlesCMS#1847]
I couldn't find a request for this yet so here it is.

It would be helpful to have something similar to the WYSIWYG editor for the raw-html pagepart.
Now it is just a textarea and it is hard to do small changes without copying the text back to a code editor. This is useful for the group of users that don't have a code editor installed by default because they don't do a lot of coding, but still require to use embed codes and might want to do some changes or add classes to code.

Possible solutions are: [CodeMirror](http://codemirror.net/) and [Ace](https://ace.c9.io/).

**Comment by Devolicious** [comment]
Hi @well-made,

Thanks for the suggestion. We will take this up for debate to add it as a roadmap feature. If you can't help yourself and want to contribute, a PR for this is always welcome.
