### ISSUE TITLE
[AdminBundle] Unable to delete Page Part

### ISSUE THREAD

**Issue by iknowfoobar** [Kunstmaan/KunstmaanBundlesCMS#1848]
We have recently upgraded several of our sites from Kunstmaan 4 to 5 and have started receiving reports from clients that they can't delete page parts.

We have been able to replicate the problem. When you click the delete button on a page part a pop up appears asking are you sure. If you select yes the black opacity overlay is not removed meaning that the page become un usable. I can see that the page part is removed from the form and if I manually remove the overlay I can still save the page and the page part is removed so this appears to be a front end issue.

We have seen this in Kunstmaan v5.0.2 and v5.0.3 in the latest versions of Chrome and Safari.

**Comment by Devolicious** [comment]
@iknowfoobar, yes we noticed aswell. A patch release is in the making. I'll keep you posted.

**Comment by Devolicious** [comment]
Hi @iknowfoobar,

v5.0.4 has been released. It only contains bugfixes so upgrading will be no hassle at all. Just be sure to run `assets:install` command and the problem should be fixed.

Happy coding!

**Comment by iknowfoobar** [comment]
Hi @Devolicious This is all working now, thanks!
