### ISSUE TITLE
[AdminBundle] Issue with using jQuery in CMS

### ISSUE THREAD

**Issue by Nightwhistle** [Kunstmaan/KunstmaanBundlesCMS#1861]
I have few jQuery scripts that I'd like to use on forms in the CMS. After upgrading to 5.x they don't work anymore.

I extended `/AdminBundle/Resources/views/Default/_js_footer_extra.html.twig`
and added code
```
{% javascript
    "@WebsiteBundle/Resources/ui/admin/formFieldsVisibilityToggle.js"
    "@WebsiteBundle/Resources/ui/admin/formBannerDurationVisibilityToggle.js"
    output="assets/admin/js/footer/footer.min.js" filter="?uglifyjs2" %}

    <script src="{{ asset_url }}"></script>
{% endjavascripts %}
```
The code works, but almost every time page is refreshed i get following error and jQuery fails to execute. This piece of code worked perfectly with previous version of KunstmaanAdminBundle where jQuery was loaded inside `js_footer.html.twig`
```
footer.min_formFieldsVisibilityToggle_1.js:1 Uncaught ReferenceError: $ is not defined
    at footer.min_formFieldsVisibilityToggle_1.js:1
```

**Comment by deZinc** [comment]
Hi @Nightwhistle ,
you haven't overwritten the /AdminBundle/Resources/views/Default/_js_footer.html.twig by any chance? That file has changed in the 5.x.

Have a look at this [pull request](https://github.com/Kunstmaan/KunstmaanBundlesCMS/commit/f87c02df1d66a1903f731c6e0228dc8a1fad4715#diff-93b41ec8241882420ad65885a9a7abc4)

**Comment by Nightwhistle** [comment]
Hi @deZinc.
Yes, I have noticed the file changed, this is why I'm wondering how to use jQuery now.
The `_js_footer.html.twig` is not overwritten, only `_js_footer_extra.html.twig`

**Comment by deZinc** [comment]
Well @Nightwhistle, I just did some tests, trying to reproduce the error in a recent project by overwriting the _js_footer_extra.html.twig. I checked if jquery was up and ready and added a jquery function, but I was unable to reproduce the error.

**Comment by Nightwhistle** [comment]
Can you please give me the code snippet you used in `_js_footer_extra.html.twig` for testing?

**Comment by deZinc** [comment]
I already deleted it again, but I used this [small script](https://stackoverflow.com/questions/7341865/checking-if-jquery-is-loaded-using-javascript) and then added some random jquery function, anything that uses the $ will do I guess. I also did this directly in the _js_footer_extra.html.twig.

**Comment by Nightwhistle** [comment]
Ok, so the bottom line is: jQuery should be available in Kunstmaan just by simply overriding `_js_footer_extra.html.twig`.

There must be some other problems I'm not aware of with my project.
Thanks for investigating this for me @deZinc.

**Comment by deZinc** [comment]
Let me know when you find it, I'm curious now.... ;)

**Comment by Nightwhistle** [comment]
I will. It's strange to me that sometimes it works, sometimes it doesn't so I thought there might be some changes regarding when or how Kunstmaan is actually loading jquery and if something changed there.

**Comment by deZinc** [comment]
Did you check out [this file](https://github.com/Kunstmaan/KunstmaanBundlesCMS/blame/5.0/groundcontrol/admin-bundle.tasks.js) already? The way jquery is loaded was changed 11 months ago.

**Comment by Nightwhistle** [comment]
Yes, I have but I should expect to have jquery working when I add the script in `_js_footer_extra.html.twig` as it works for you.

**Comment by Nightwhistle** [comment]
@deZinc I managed to fix this by mimicking the way _js_footer.html.twig load scripts:

```twig
{% javascripts
    "@WebsiteBundle/Resources/ui/admin/formFieldsVisibilityToggle.js"
    "@WebsiteBundle/Resources/ui/admin/formBannerDurationVisibilityToggle.js"
    output="assets/admin/js/footer/footer.min.js" filter="?uglifyjs2" %}

    <script>
        var scriptEl = document.createElement('script');
        scriptEl.src = '{{ asset_url }}';
        scriptEl.async = false;
        document.body.appendChild(scriptEl);
    </script>

{% endjavascripts %}
```

**Comment by dannyvw** [comment]
I have the same issue as @Nightwhistle and his fix works but it feels like a workaround.

**Comment by dbeerten** [comment]
Hi @Nightwhistle & @dannyvw,
This is caused by this PR:
https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/1615/files#diff-93b41ec8241882420ad65885a9a7abc4R8.

The JS file which includes jQuery is loaded dynamically, so the moment when your code is initialised in the body, jQuery might not be available yet. That explains also why the workaround of @Nightwhistle works.

Another possible workaround is to overwrite the default _js.footer.html.twig and don't load the admin-bundle javascript dynamically:
```
{% include "@KunstmaanAdmin/Default/_ckeditor_configs.html.twig" %}

<script>
    CKEDITOR_BASEPATH = '/bundles/kunstmaanadmin/default-theme/ckeditor/';
    MORE_BUTTON_LABEL = '{{ 'kuma_js.auto_collapse.more_button_label' | trans | e('js') }}';
</script>

{# Don't load admin JS dynamically #}
<script src="{{ asset('bundles/kunstmaanadmin/js/admin-bundle.min.js') }}"></script>
<script src="{{ asset('bundles/kunstmaanadmin/js/admin-bundle.next.js') }}"></script>

{# Load your custom JS AFTER default admin JS #}
{% javascript
    "@WebsiteBundle/Resources/ui/admin/formFieldsVisibilityToggle.js"
    "@WebsiteBundle/Resources/ui/admin/formBannerDurationVisibilityToggle.js"
    output="assets/admin/js/footer/footer.min.js" filter="?uglifyjs2" %}

    <script src="{{ asset_url }}"></script>
{% endjavascripts %}

{# Dynamically load the scripts, and only add the Polyfills when they are necessary #}
<script>
    {# scripts without polyfills #}
    var scripts = [
        {%- block extra_async_javascripts %}{% endblock -%}
    ];
    if (!('fetch' in window &&
            'Promise' in window &&
            'assign' in Object &&
            'keys' in Object
        )) {
        scripts.unshift('{{ asset('bundles/kunstmaanadmin/js/admin-bundle-polyfills.js') }}');
    }
    scripts.forEach(function(src) {
        var scriptEl = document.createElement('script');
        scriptEl.src = src;
        scriptEl.async = false;
        document.head.appendChild(scriptEl);
    });
</script>

{% include "@KunstmaanAdmin/Default/_js_footer_extra.html.twig" %}
```
