### ISSUE TITLE
Custom Media Handler - Priority in MediaManager#addHandler

### ISSUE THREAD

**Issue by tentwofour** [Kunstmaan/KunstmaanBundlesCMS#188]
I've created a new Media Handler (Music, locally stored, to be streamed using .htaccess for pseudo-secured streaming to MEJS player).

It's working...almost; here's the issue:

MediaHandlerCompilerPass#process looks for all services tagged with 'kunstmaan_media.media_handler', and registers them as handlers using MediaManager#addHandler.

That works, but my handler is always last in the chain, so when a Media is created, the FileHandler (default) will always be called before my MusicHandler.

Is there a way to set the priority/positioning of my handler? Maybe using the 'priority' key in the service definition, like any kernel event tagged service, and having the MediaHandlerCompilerPass#process respect that?

**Comment by tentwofour** [comment]
Edit: I can put my bundle *before* Kunstmaan's in AppKernel, and my service will be found before, and injected first, so that's a temporary fix I guess ;)

**Comment by krispypen** [comment]
That can indeed be a temporary fix, but we need a priority there indeed.
