### ISSUE TITLE
[ALL] Upgrade steps form types

### ISSUE THREAD

**Issue by dannyvw** [Kunstmaan/KunstmaanBundlesCMS#1892]
This upgrade step is not for all bundles? As example the admin bundle does not have this new structure.

All existing form types have been deprecated in order to satisfy Sensio Insight requirements that form type classes go in a Form/Type folder instead of justr Form. Existing projects will not break, the old classes are still there, but the logic has been moved into the new classes in the correct folder, and the old classes now extend the new one, and have a @deprecated tag.
https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/5.0.5/UPGRADE-5.0.md

**Comment by Numkil** [comment]
I think this addition to the upgrade guide has been merged too quickly. Because the actual PR for it is still open.

https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/1723
