### ISSUE TITLE
[Node] Node online filter translations

### ISSUE THREAD

**Issue by dannyvw** [Kunstmaan/KunstmaanBundlesCMS#1899]
Kunstmaan 5.0.5
Twig 2.4.8

With the latest twig version, the "true", "false" boolean is converted to 1. See screenshot

![image](https://user-images.githubusercontent.com/1218389/38611412-e443b5d6-3d83-11e8-86a3-74c4c393a230.png)

**Comment by Numkil** [comment]
Very strange behaviour indeed. It looks like it has something to do with the translation yml having the word true and false in it.

**Comment by Numkil** [comment]
If you need an immediate fix you can in the translations tab of the settings overwrite the following keys.

filter.true
and filter.false
if they come from the database the error does not happen either.
