### ISSUE TITLE
Update the social tab to deal with the new options

### ISSUE THREAD

**Issue by roderik** [Kunstmaan/KunstmaanBundlesCMS#190]
MAKE SURE ITS BC COMPATIBLE! we don't want to redo all existing sites...

* https://developers.facebook.com/docs/sharing/markup
* https://dev.twitter.com/cards/markup
* https://developer.linkedin.com/docs/share-on-linkedin
* https://developers.pinterest.com/rich_pins_overview/
* https://developers.google.com/+/web/snippet/

Make sure to add help texts in regards to image size, optimal lengths etc etc
Maybe make different groups per social network
Work on the labelling: OG title is not very clear

**Comment by roderik** [comment]
https://blog.bufferapp.com/ideal-image-sizes-social-media-posts

**Comment by roderik** [comment]
https://blog.bufferapp.com/ideal-image-sizes-social-media-posts

**Comment by roderik** [comment]
Some size info: https://blog.bufferapp.com/ideal-image-sizes-social-media-posts

**Comment by jockri** [comment]
We have twitter cards, advanced facebook settings, linkedin use og tags, google+ is dead :)
