### ISSUE TITLE
Export pagetemplate

### ISSUE THREAD

**Issue by dannyvw** [Kunstmaan/KunstmaanBundlesCMS#1904]
Can you explain what the option "Export pagetemplate" does. It gives an modal with some html, but not sure what we can do with this.

Is it possible to disable this for the whole installation?

**Comment by Numkil** [comment]
The only way to remove that button for now is to overwrite this file.
src/Kunstmaan/NodeBundle/Resources/views/NodeAdmin/_modals.html.twig
And remove the include line for the export pagetemplate twig.

**Comment by dannyvw** [comment]
Is it possible to create an option to enable this button? Instead of only based on interface and superadmin. 

https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/59097b1501cfd670da0e936b35347344a097d147/src/Kunstmaan/NodeBundle/Helper/Menu/ActionsMenuBuilder.php#L184

**Comment by Numkil** [comment]
i am sure it would not be too difficult to do. I will add it to the roadmap.
