### ISSUE TITLE
[Seo] Title and description are "required"

### ISSUE THREAD

**Issue by dannyvw** [Kunstmaan/KunstmaanBundlesCMS#1906]
Seo title and description are shown as required, but these fields are optional.

**Comment by sandergo90** [comment]
Already done ;) 

https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/1851

**Comment by dannyvw** [comment]
@sandergo90 Ah this is not yet available in 5.0.5. Thanks!

**Comment by sandergo90** [comment]
No indeed! We will make a new release soon!
