### ISSUE TITLE
[Admin] Update add new translations

### ISSUE THREAD

**Issue by dannyvw** [Kunstmaan/KunstmaanBundlesCMS#1907]
Update translation "Add New" to "Add new". Same for "Add New %subject%"

https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/src/Kunstmaan/AdminBundle/Resources/translations/messages.en.yml#L59

**Comment by sandergo90** [comment]
@dannyvw please go ahead at crowdin 😉 

http://translatebundles.kunstmaan.be/

**Comment by dannyvw** [comment]
@sandergo90 I will only create tickets for now, so we can later fix this.
