### ISSUE TITLE
[GeneratorBundle] kuma:generate:default-site throws exception with twig 2

### ISSUE THREAD

**Issue by treeleaf** [Kunstmaan/KunstmaanBundlesCMS#1926]
When you generate a default site with kuma:generate:default-site and you have twig 2 installed (tested with 2.4.8 and php 7.1), then it will throw an exception.

Twig_Error_Syntax: Unclosed comment. (uncaught exception) at .../vendor/kunstmaan/bundles-cms/src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/ui/scss/config/general/_colors.scss line 71 while running console command `kuma:generate:default-site`

**Comment by hackzilla** [comment]
I've just run into this issue.

How can I work around it?

**Comment by hackzilla** [comment]
@Devolicious The answer is to replace ```raw``` with ```verbatim```

**Comment by acrobat** [comment]
@hackzilla I came also across this issue while testing #1200. The raw tag is deprecated in twig 1.x but does still work, so a temporary workaround can be to revert to twig 1. But this should indeed be fixed by switching to the `verbatim` tag

**Comment by hackzilla** [comment]
@acrobat makes sense.

I've just checked and I had twig v2.4.5

This project is very new to me, and I encountered the issue following the [getting started guide](http://kunstmaanbundlescms.readthedocs.io/en/latest/installation/#installation).

**Comment by acrobat** [comment]
@hackzilla I've create a pr to fix this issue. If you want you can test the patch in #1987 until it's merged and released.
