### ISSUE TITLE
[Menu] New window menu item is required

### ISSUE THREAD

**Issue by dannyvw** [Kunstmaan/KunstmaanBundlesCMS#1928]
New window field is displayed as required, but it is not required.

![image](https://user-images.githubusercontent.com/1218389/38995949-6025b4c6-43ea-11e8-9a48-0a61b89b012d.png)

**Comment by Devolicious** [comment]
@dannyvw, great catch, if you would have time for a small bug fix PR that would be great and much appreciated!

**Comment by dannyvw** [comment]
@Devolicious Done

**Comment by Devolicious** [comment]
@dannyvw Thx!
