### ISSUE TITLE
[Form] Regex label must start with a capital

### ISSUE THREAD

**Issue by dannyvw** [Kunstmaan/KunstmaanBundlesCMS#1931]
![image](https://user-images.githubusercontent.com/1218389/39037505-fd8d139e-4480-11e8-837c-52e734431d2c.png)

**Comment by Devolicious** [comment]
@dannyvw, great catch, if you would have time for a small bug fix PR that would be great and much appreciated!

**Comment by dannyvw** [comment]
@Devolicious Done
