### ISSUE TITLE
Remove hardcoded default admin / admin

### ISSUE THREAD

**Issue by wimvds** [Kunstmaan/KunstmaanBundlesCMS#194]
To get rid of the hardcoded admin / admin combo, we will have to change the user entities.

An extra flag ("change password on next login") will be added. When it is set, the user should be redirected to the FOS change password page next time he logs in (the flag should only be reset when the password has actually been changed).

The UserFixtures should be moved to the generator bundle (and removed from the admin bundle) - they should be generated with a random password. This password should be echoed on screen.

And last but not least, the documentation should be updated ...

**Comment by Lisje** [comment]
Don't forget to update the generated behat tests with this generated password!
