### ISSUE TITLE
Allow to pass options to the advanced select - select2

### ISSUE THREAD

**Issue by acrobat** [Kunstmaan/KunstmaanBundlesCMS#1957]
The select2 is initialized without the possibility to pass extra options to it.

https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/da86b5b221a265333c3efbb476e718862495e3f8/src/Kunstmaan/AdminBundle/Resources/ui/js/_advanced-select.js#L7..L9

For example the [`allowClear`](https://select2.org/selections#clearable-selections) option

**Comment by sandergo90** [comment]
@acrobat Select2 supports data-attributes. So this is actually already supported.

Example:

```
$builder->add(
            'type',
            EntityType::class,
            [
                'required' => true,
                'label' => 'kuma.cookie.adminlists.cookie.type',
                'class' => CookieType::class,
                'choice_label' => 'name',
                'attr' => [
                    'class' => 'js-advanced-select',
                    'data-allow-clear' => 'true',
                    'data-placeholder' => 'Select an option'
                ]
            ]
        );
```
