### ISSUE TITLE
KunstmaanFormBundle Form pages send form to email

### ISSUE THREAD

**Issue by konstantinsp** [Kunstmaan/KunstmaanBundlesCMS#1984]
Hello,
i there a way to send also an email upon form submission generated via KunstmaanFormBundle(Form Page)?

**Comment by sandergo90** [comment]
@konstantinsp sure, this is already implemented in the FormBundle. When you create a new form page in the CMS, there is an option to set the subject and from e-mail. This will send the form submission to the e-mailaddress provided. If you also want to send an e-mail to the user, you can create an event listener on form submission 😉
