### ISSUE TITLE
Use the behat transliterator for slugifiying

### ISSUE THREAD

**Issue by krispypen** [Kunstmaan/KunstmaanBundlesCMS#199]
We should use https://github.com/Behat/Transliterator/ for slugifiying, and also make it a service that can be overridden. We should not reïnvent the wheel or use static php methods with @ signs

So we should get rid of https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/src/Kunstmaan/UtilitiesBundle/Helper/Slugifier.php

**Comment by woutervandamme** [comment]
Should I also make this a service?  -> https://github.com/Kunstmaan/KunstmaanBundlesCMS/issues/84

**Comment by jockri** [comment]
Yes

**Comment by markmedia** [comment]
since this update, cyrillic characters are not being converted and we still need to use additional methods.
