### ISSUE TITLE
Uploading an (xls|doc|ppt)x file in media results in a zip download

### ISSUE THREAD

**Issue by krispypen** [Kunstmaan/KunstmaanBundlesCMS#200]
When you upload an (xls|doc|ppt)x file in media, and then try to download it, it's shown as a zip download. The main problem is that the download link should use the same extension as the uploaded file. now it's converted by checking the mimetype

**Comment by bakie** [comment]
@kimausloos said we can't use the extension of the uploaded file because of security issues. Maybe he can explain here why that is :)

**Comment by kimausloos** [comment]
Basically just owasp recomendations: https://owasp.org/index.php/Unrestricted_File_Upload

Some risks here: http://www.acunetix.com/websitesecurity/upload-forms-threat/

**Comment by krispypen** [comment]
ok, we need to make sure if you upload a .php file, that it's not "executed", but for all the other extensions I don't see a problem. overriding the extension based on mimetype is wrong

**Comment by krispypen** [comment]
also if I upload a file composer.json to use in a cool blog post, the name should stay composer.json, and not **5502b53e9830b**.txt

**Comment by roderik** [comment]
Yes please :)

**Comment by Devolicious** [comment]
https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/236
