### ISSUE TITLE
Difference between AbstractPage.title and AbstractPage.pageTitle

### ISSUE THREAD

**Issue by Perni1984** [Kunstmaan/KunstmaanBundlesCMS#2032]
Could somebody shed some light on what's the difference - or better explain to me the reason why `AbstractPage.pageTitle` exists?

**Comment by Slurp** [comment]
@Perni1984 the navigation title could be different from the title on your page.
So for fallback purpose the pageTitle returns the navigation title when it is not set.

**Comment by Perni1984** [comment]
@Slurp 

just for me to understand - when I link to a page from e.g. a Menu - NavigationTitle should be used. The PageTitle is basically used for the title tag - correct?

**Comment by Devolicious** [comment]
@Perni1984 

you can use it like you want, but yes, that is the main purpose of it.
