### ISSUE TITLE
[AdminBundle] Add ConsoleExceptionListener

### ISSUE THREAD

**Issue by jockri** [Kunstmaan/KunstmaanBundlesCMS#205]
Exceptions in console commands are NOT logged by default. If we want get them in the logs (+sentry) we need to add an eventlistener. Instead of adding the same eventlistener in each project, we should add it in the Bundles. We need to make it possible via a parameter to disable this.

**Comment by krispypen** [comment]
#213

**Comment by krispypen** [comment]
merged
