### ISSUE TITLE
[AdminBundle] using WysiwygType in a nested form in a page part does not work

### ISSUE THREAD

**Issue by SpadXIII** [Kunstmaan/KunstmaanBundlesCMS#2050]
I have a page part 'FAQ items' which has a CollectionType with an entity (QuestionsWithAnswers) which has TextType and WysiwygType fields.
The nested form is set to add 1 item. (nested_form_min = 1)

When I try to add this page part to a page, it seems to add the page part but the overlay stays visible. There is a javascript error: `TypeError: this.filter is undefined` (seems to be inside a destroy-function)

I think it has to do with the ckeditor not being fully initialized just yet, because if I change the field type to TextareaType it works just fine.

A similar error has been reported (and fixed) before, see #1062. Though this was not in a page part.

When setting nested_form_min to 0, it works when adding the page part, but the error still shows up when adding an item to the page part.
When adding a second item to this page part, it does not have a ckeditor. And there is another error in the console: `uncaught exception: The editor instance "form_pagepartadmin_newpp_1531384081_questionsWithAnswers_0_answer" is already attached to the provided element`

**Comment by Devolicious** [comment]
Hey @SpadXIII,

Thanks for submitting this issue. Release should go out today.
