### ISSUE TITLE
[AdminBundle] sidebar.html.twig has hardcoded reference to KunstmaanNodeBundle

### ISSUE THREAD

**Issue by daanporon** [Kunstmaan/KunstmaanBundlesCMS#207]
When you want to use the AdminBundle without the NodeBundle this line will break it:

https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/src/Kunstmaan/AdminBundle/Resources/views/Default/sidebar.html.twig#L18

This line is part of the following PR:

https://github.com/Kunstmaan/KunstmaanBundlesCMS/commit/cab8713b8a37664876d960a946e3256cdf54b419

**Comment by krispypen** [comment]
There are currently a lot of changes in the PR #202, so be sure the changes are compatible.
I also think this should be configured in the PageMenuAdaptor.
