### ISSUE TITLE
Installation Experience [ improvement ]

### ISSUE THREAD

**Issue by xtrasmal** [Kunstmaan/KunstmaanBundlesCMS#209]
Hi there,

I'm getting error after error while getting this cms up and running.
Why isn't there a simple NON STRESS way to get things up and running?

![ungoing madness](https://sc-cdn.scaleengine.net/i/295b0892ed0c8b5fdf3660e3e1d71ef7.png)

**Comment by woutervandamme** [comment]
when you create the project with composer, make sure you get the latest version of the bundles,

composer create-project kunstmaan/bundles-standard-edition path/to/install -s dev

this will resolve the security.acl.permission.map errors. There is an open issue to fix all those warnings messages. Hopefully that won't take too long.

**Comment by xtrasmal** [comment]
Hi there Wouter,

```bash
composer create-project kunstmaan/bundles-standard-edition kunstmaan -s dev
php app/console kuma:generate:bundle
php app/console kuma:generate:default-site --demosite
php app/console doctrine:schema:create
php app/console doctrine:fixtures:load
php app/console kuma:generate:admin-tests
bower install
npm install
grunt build
php app/console assets:install web
php app/console assetic:dump
```

The above is what I run.

**Comment by woutervandamme** [comment]
I just created a new project, did those exact commands and received no errors. Are you sure you deleted the complete folder before retrying?

I had the same problem as you a couple of days ago, and I solved it by adding -s dev to the composer create project command.

**Comment by xtrasmal** [comment]
Yes before that I've done a 
```rm -rf kunstmaan```
to delete it completely.

**Comment by woutervandamme** [comment]
Can you tell me on which command it fails?

**Comment by xtrasmal** [comment]
After I run 
```composer create-project kunstmaan/bundles-standard-edition kunstmaan -s dev```
it guides me through the parameters.yml.

After that it ends with this:

![the error](https://sc-cdn.scaleengine.net/i/51765d32c2ea00801ee787d63878ff68.png)

**Comment by woutervandamme** [comment]
when the script ask to install the demo bundle, just don't install it, that will fix the error hopefully.

I'm guessing the demoBundle needs an update or something.

**Comment by xtrasmal** [comment]
succes!!

**Comment by woutervandamme** [comment]
glad I could help.
