### ISSUE TITLE
[docs] What is the relationship between the Admin frontend code and your own?

### ISSUE THREAD

**Issue by tarjei** [Kunstmaan/KunstmaanBundlesCMS#2116]
Hi, since I'm maintaining a number of projects that have been around for some time, it would be nice to know that is needed to ensure that the frontend code for the admin backend is correctly set up vs what in the sample app is thought of as startercode for whatever frontend is to be created on the site. 

I usually want to nuke the last, but need to keep the last and knowing what to keep and how to separate the two would be great esp when upgrading from older versions.

Kind regards,
Tarjei

**Comment by Devolicious** [comment]
Hi @tarjei, Not sure what you are referring to. Can you explain a bit more about your setup? You are talking about the "Admin frontend" vs "Own code", does this mean that you are replacing our Admin frontend with your own admin frontend?

**Comment by tarjei** [comment]
Sure :)

Admin frontend = This is the meat of Kunstmaan, basicly everything below the /admin/ url.

Own code = Any css and js I use on the pages and urls that are created outside of the admin area.

My point is that it is a bit hard to see what is helper code to get started building the "Own code" section and what is needed for the admin part of the site.

Regards,
Tarjei

**Comment by dbeerten** [comment]
Hi @tarjei, let me see if I could clear things up for you a little bit:

Basically, most of the assets of the "Admin frontend" are in `./vendor/kunstmaan/bundles-cms/src/Kunstmaan/*Bundle/Resources/public/`. These are the compiled assets. When you run `bin/console assets:install` these assets are copied to the project's web dir. That's all you need for the Admin frontend.

The "startercode" as you mentioned for the frontend of the website (non-admin) is generated when you run the `kuma:generate:layout` command. This generates 2 types of files: 
- `./src/Foo/BarBundle/Resources/ui/`: the basic assets (views, js, scss, ...)
- `groundcontrol`: our build tools (linters, compilers, ... -> webpack, gulp, ...)

If for some reason you don't like our startercode for your projects (We are open to suggestions/improvements), you can delete these files/folders (without breaking the Admin frontend):
- assets:
    - `./src/Foo/BarBundle/Resources/ui/`
- groundcontrol:
    - `./groundcontrol/`
    - `./.babelrc`
    - `./.eslintrc`
    - `./.nvmrc`
    - `./.stylelintrc`
    - `./buildUI.sh`
    - `./gulpfile.babel.js`
    - `./package.json`

**Comment by tarjei** [comment]
Great answer! Thanks :)

This is not a critique of your starter code. It is just easier / faster for me to start with a basic set of items that I know and then move from there. Then I do not have to understand the groundcontrol stuff :)

Also this is partly because I'm upgrading older projects to newer versions of Kunstmaan.

Kind regards!

**Comment by Warxcell** [comment]
Is it possible to swap gulp for Webpack Encore ? And what issues to expect?

**Comment by tarjei** [comment]
@Warxcell just follow the Webpack Encore documentation and you should be set :)
