### ISSUE TITLE
Add wysiwyg formtype

### ISSUE THREAD

**Issue by denbatte** [Kunstmaan/KunstmaanBundlesCMS#212]
At the moment a wysiwyg is done with:

```php
$builder->add(
        		'text1',
        		'textarea',
        		array(
        			'required' => false, 'attr' => array('rows' => 10, 'cols' => 600, 'class' => 'rich_editor'),
        		)
        );
```

This should be changed to something like this:
```php
$builder->add(
        		'text1',
        		'wysiwyg',
        		array(
        			'required' => false),
        		)
        );
```
So we need a WysiwygType, like we already made a MediaType

Also make sure the generators that are generating this code are changed.

**Comment by woutervandamme** [comment]
https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/222
