### ISSUE TITLE
[AdminBundle] Ordering of page part sub entities has stopped working in v5

### ISSUE THREAD

**Issue by iknowfoobar** [Kunstmaan/KunstmaanBundlesCMS#2157]
We have upgraded several of our client sites over the last few months from v4 to v5. A couple of them use custom page parts that have sub entities, and we followed this news article to build them: https://bundles.kunstmaan.be/news/using-sub-entities-in-pageparts

However since upgrading to v5 the Up/Down arrows for the sub entities in the Page Part are no longer working. There is no error either it just appears that the click event no longer exists. Dragging and dropping the sub entities still works.

**Comment by acrobat** [comment]
@iknowfoobar is it possible that it's related to the changes in PR #2049?

**Comment by iknowfoobar** [comment]
@acrobat Thanks, it appears that it is.

**Comment by iknowfoobar** [comment]
Hi @Devolicious, has this been resolved in an unreleased version? The conversation on the related pull request wasn't resolved as far as I can see. Thanks

**Comment by Devolicious** [comment]
@iknowfoobar conversation will be continued in #2282
