### ISSUE TITLE
Slack Invite Url is invalid

### ISSUE THREAD

**Issue by mablae** [Kunstmaan/KunstmaanBundlesCMS#2181]
Hi there, 

Are you still using that slack channel for direct communications? The invite link in `README.md` is outdated.

**Comment by acrobat** [comment]
Hi @mablae,

Thanks for reporting this issue, we've already updated the link and this fix will soon be upmerged into master. You can find the new link in the [5.0 readme](https://github.com/Kunstmaan/KunstmaanBundlesCMS/tree/4ed8c7b12183e58239f67fa3fa7e39f863a21941#community) or in PR #2178
