### ISSUE TITLE
Refactor AdminLists

### ISSUE THREAD

**Issue by wimvds** [Kunstmaan/KunstmaanBundlesCMS#219]
I think we should refactor the AdminLists. Now there's tight coupling between the data providers (currently Doctrine DBAL & ORM) and the list itself. IMHO it would be better if we create a generic data provider interface, and inject this in the adminlist. Then we could create concrete providers for DBAL & ORM and even add new providers for CSV, Excel and the like, making them very flexible.

We could also extend this to the admin list rendering part, and have renderers for screen, JSON, XML, CSV, Excel and the like (where screen is paginated, and the others ignore pagination?).

This will be a BC breaking change though ... So will need a major version bump.

**Comment by wimvds** [comment]
After reading https://github.com/Kunstmaan/KunstmaanBundlesCMS/issues/217, I think this is more or less what is suggested there as well, but with some added abstraction. We could look into the bundles mentioned there to see if they would fit our use case.

**Comment by sandergo90** [comment]
Closing because duplicate #1796
