### ISSUE TITLE
[AdminBundle] + [DashboardBundle] upgrade to 5.1.0 breaks templates

### ISSUE THREAD

**Issue by SpadXIII** [Kunstmaan/KunstmaanBundlesCMS#2194]
The error is: Unable to find template "@KunstmaanDashboard/google_analytics/widget.html.twig" (looked into: /../dataplace/vendor/kunstmaan/bundles-cms/src/Kunstmaan/DashboardBundle/Resources/views).

Looks like the latest sensio/framework-extra-bundle has a backwards incompatible change to how it generates template filenames

I'm sure it is happening everywhere in the project.

**Comment by acrobat** [comment]
@SpadXIII Thanks for reporting! I will create a PR to fix this BC break

**Comment by acrobat** [comment]
@SpadXIII I didn't have any issues with the settings page, but I've replace extra cases where the template was "guessed" to avoid issues and make the used template more explicit. Can you please test the patch provided in #2195. Thanks!

**Comment by acrobat** [comment]
PR #2195 is merged
