### ISSUE TITLE
[KunstmaanNodeSearchBundle] issue with version checker

### ISSUE THREAD

**Issue by sandergo90** [Kunstmaan/KunstmaanBundlesCMS#2208]
https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/d4921b060fc42b5fdda7263896ffdf03aaa7c3e6/src/Kunstmaan/NodeSearchBundle/DependencyInjection/KunstmaanNodeSearchExtension.php#L58

When setting up a new index with php bin/console kuma:search:setup on elasticsearch version 6.5, following issue is raised:

" [include_in_all] is not allowed for indices created on or after version 6.0.0 as [_all] is deprecated. As a replace
  ment, you can use an [copy_to] on mapping fields to create your own catch all field."

The kunstmaan_search.hostname and kunstmaan_search.port parameters are filled from the KunstmaanSearchBundle, but when compiling the container at this point, the parameters are still empty. Maybe this should be moved to a compiler pass?

**Comment by acrobat** [comment]
This check will actually be removed in v6 and since #2695 you can workaround this check by setting the `kunstmaan_search.elasticsearch_version: 6` parameter with the correct major version (or full version like 6.1.2).
