### ISSUE TITLE
Admin login single lang

### ISSUE THREAD

**Issue by konstantinsp** [Kunstmaan/KunstmaanBundlesCMS#221]
When im trying to login as admin with url /admin i get redirected to admin/dashboard/ with this error:

     Impossible to access an attribute ("id") on a NULL variable ("") in KunstmaanAdminBundle:Default:layout.html.twig at line 130 

this error occures only in single lang project

**Comment by roderik** [comment]
Did you use the two single lang config alternatives and changed the cache setting in https://github.com/Kunstmaan/KunstmaanBundlesStandardEdition/blob/master/app/config/config_prod.yml#L37 ?

**Comment by konstantinsp** [comment]
im using 
<pre>
parameters:
    multilanguage: false

framework:
    router:
        resource: "%kernel.root_dir%/config/routing.singlelang.yml"

fos_http_cache:
    cache_control:
        rules:
            # match admin area
            -
                match:
                    path: ^/admin
                headers:
                    cache_control:
                        public: false
                        max_age: 0
                        s_maxage: 0
                    last_modified: "-1 hour"
</pre>

if i go to straight to  /admin/login and log in there the error would be gone 
it only happens when im not log in

**Comment by roderik** [comment]
* https://github.com/Kunstmaan/KunstmaanBundlesStandardEdition/blob/master/app/config/routing.singlelang.yml
* https://github.com/Kunstmaan/KunstmaanBundlesStandardEdition/blob/master/app/config/security.singlelang.yml

**Comment by konstantinsp** [comment]
thanks thats helped)
