### ISSUE TITLE
Cache behaviour

### ISSUE THREAD

**Issue by konstantinsp** [Kunstmaan/KunstmaanBundlesCMS#223]
when editing content from admin page. often pages on front end does not update until you clear a cache in symfony.

**Comment by roderik** [comment]
There is a frontend cache in production. https://github.com/Kunstmaan/KunstmaanBundlesStandardEdition/blob/master/app/config/config_prod.yml#L57

**Comment by konstantinsp** [comment]
based on your experience - what is the best solution to use cache with dynamic data?
we are implementing cart and user sections and this cache does not allow pages to show updated data.

**Comment by roderik** [comment]
You should put the dynamic parts in uncached (or with a custom cache invalidation) ESI. More info: http://symfony.com/doc/current/book/http_cache.html#edge-side-includes
