### ISSUE TITLE
5.0 to 5.1 missing template

### ISSUE THREAD

**Issue by rmikalkenas** [Kunstmaan/KunstmaanBundlesCMS#2234]
Recently updated kunstmaan from 5.0 to 5.1 and when going to admin settings I get "Unable to find template "@KunstmaanAdmin/settings/index.html.twig" (looked into: /var/www/cms/vendor/kunstmaan/bundles-cms/src/Kunstmaan/AdminBundle/Resources/views)."

It relates to #2194 and the fix is already merged, but 5.1 tag misses these changes

**Comment by Devolicious** [comment]
Hi @rmikalkenas, we just release a patch version for both 5.0 and 5.1 to address the issue.

Enjoy!
