### ISSUE TITLE
Can't define new locale

### ISSUE THREAD

**Issue by bmeloski** [Kunstmaan/KunstmaanBundlesCMS#2237]
Hi.

I was trying to add new custom locale(not defined at the instalation wizard) by editing 'managed_locales' array under config.yml and requiredlocales under parameters.yml but it seems not to work. How can i accomplish that?

**Comment by deZinc** [comment]
Hi @bmeloski ,

this sort of question can better be asked in our slack, so, feel free to join us [overthere](https://join.slack.com/t/kunstmaancms/shared_invite/enQtNDg0MzE0NDQ3MjU0LTIxMmY4YTRkMDBmYzE5MjFiMzBjOGI5NjczMjEyNDdlNDlmYjBiZDA3OWRjM2NhZjRjZjBlYmM0OWJhNWU2ZGM).

As for your question, did you choose a single or multi-language setup during the wizard?

**Comment by bmeloski** [comment]
Thank you for your quick response. I have multi-language defined as true in
my config

śr., 16 sty 2019 o 15:11 Peter Zentjens <notifications@github.com>
napisał(a):

**Comment by deZinc** [comment]
Can you define "does not seem to work"?
Are you using the multi-language routing?
