### ISSUE TITLE
[Admin Bundle] Sub Entity arrows don't work

### ISSUE THREAD

**Issue by jordanmoon** [Kunstmaan/KunstmaanBundlesCMS#2282]
Look similar to this issue #2157.

As of v5 Page Parts can be reordered using the arrows, but Sub Entities cannot. It looks like an issue with the data attribute `draggable` being at an incorrect level.

**Comment by Devolicious** [comment]
Hi @jordanmoon & @iknowfoobar.

On version 5.0.13 we do not have this bug as described. Which version are you guys using?

**Comment by jordanmoon** [comment]
Hi @Devolicious 
This is in 5.1.1

**Comment by Devolicious** [comment]
@jordanmoon Thx for the quick response. We will investigate this. TBC

**Comment by acrobat** [comment]
The change in PR #2049 breaks this behaviour. I will create a pr to revert the change and then we can discuss further changes there to fix the issue pr #2049 fixed before.
