### ISSUE TITLE
[GeneratorBundle] wrong use in the pagepart generator

### ISSUE THREAD

**Issue by deZinc** [Kunstmaan/KunstmaanBundlesCMS#2371]
When generating a pagepart, In the newly generated xxxPagePartAdminType, an 
`use Kunstmaan\MediaBundle\Validator\Constraints as Assert;` can be found which isn't used in this file.

**Comment by JoppeDC** [comment]
It appears that the import is in fact used when there's a media field with specfic mimetypes.

**Comment by acrobat** [comment]
Closing this for now as indeed the use statement is in some cases used and otherwise unused, but there is no easy way to check this in the current setup.
