### ISSUE TITLE
[NodeBundle] Fixtures throws fatal error @ PageCreatorService.php on line 149

### ISSUE THREAD

**Issue by devigner** [Kunstmaan/KunstmaanBundlesCMS#2401]
When running `bin/console doctrine:fixtures:load -n` The following error is thrown:

```
In NodeRepository.php line 199:

  Argument 3 passed to Kunstmaan\NodeBundle\Repository\NodeRepository::createNodeFor() must be an instance of Kunstmaan\AdminBundle\Entity\BaseUser, null given, called in /app/ve
  ndor/kunstmaan/bundles-cms/src/Kunstmaan/NodeBundle/Helper/Services/PageCreatorService.php on line 149
```

I'm running Kunstmaan 5.2., I have upgraded from 5.1

The fixtures that are loaded are:
```
  > loading [1] Kunstmaan\MediaBundle\DataFixtures\ORM\FolderFixtures
  > loading [1] Kunstmaan\TranslatorBundle\DataFixtures\ORM\TranslationFixtures
  > loading [51] AppBundle\DataFixtures\ORM\DefaultSiteGenerator\DefaultSiteFixtures
```

I'm missing fixtures from AdminBundle somehow (could be the reason).

**Comment by devigner** [comment]
The installation page shows fixtures load from the AdminBundle  [installation](https://kunstmaanbundlescms.readthedocs.io/en/latest/installation/) but the AdminBundle doesn't contain any Fixtures.

**Comment by Devolicious** [comment]
Hi @devigner, Did you do a SF3 to SF4 upgrade as well? I had kind of the same error when my security.yaml did not contain the correct user provider.

**Comment by devigner** [comment]
I redid the installation (removed vendor) and fixed it. I did an edit on the GeneratorBundle that caused the issue. Completely my bet. Closing issue, nothing to see here. 👍
