### ISSUE TITLE
Admin article edit form broken due to JS error in datepicker.js

### ISSUE THREAD

**Issue by virtualize** [Kunstmaan/KunstmaanBundlesCMS#2444]
In 5.2.5 and 5.3 the admin edit form of Article Pages are broken.
As it results in an JS error "minDate.clone() is not a function" thrown here: https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/a49db196478608bbe6d2e24b5f0d525e0dbd159d/src/Kunstmaan/AdminBundle/Resources/ui/js/_datepicker.js#L70

Adding ` data-min-date="today" data-default-date="true" ` here
https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/a49db196478608bbe6d2e24b5f0d525e0dbd159d/src/Kunstmaan/AdminBundle/Resources/views/Form/fields.html.twig#L261
and here
https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/a49db196478608bbe6d2e24b5f0d525e0dbd159d/src/Kunstmaan/AdminBundle/Resources/views/Form/fields.html.twig#L277
seem to fix it.

But I think it would be better to update the JS in question to have sensible default values.

FYI: this is the commit that introduced it: https://github.com/Kunstmaan/KunstmaanBundlesCMS/commit/1be8f83e372a6e2dc12fa34776f8daf32683745a

**Comment by acrobat** [comment]
Fixed in #2446
