### ISSUE TITLE
[DashboardBundle] Google Analytics Controller is incompatible with SF4

### ISSUE THREAD

**Issue by iknowfoobar** [Kunstmaan/KunstmaanBundlesCMS#2496]
```Kunstmaan\DashboardBundle\Controller\GoogleAnalyticsController``` loads several services from the container. These services are now all private in SF4 so causes fatal errors when accessing the ```setTokenAction``` action.

Needs to be refactored to use Dependency Injection.

**Comment by acrobat** [comment]
@iknowfoobar I've provided a fix in #2498 can you verify if this solves your problem? Thanks!

**Comment by iknowfoobar** [comment]
Hi @acrobat That looks like it should solve the problem, I hadn't realised it was a typo ;)
