### ISSUE TITLE
[ArticleBundle][SF4]Twig extensions not working in prod

### ISSUE THREAD

**Issue by bmeloski** [Kunstmaan/KunstmaanBundlesCMS#2505]
While everything runs smooth on dev, on prod enviroment you get following error after using twig functions:
`[2019-06-17 13:02:03] request.CRITICAL: Uncaught PHP Exception Twig\Error\SyntaxError: "Unknown "get_article_categories" function."`

Issue is caused by deprecated `\Twig_SimpleFunction` class in `Kunstmaan\ArticleBundle\Twig\ArticleTwigExtension`. To make it work it should be changed to `Twig\TwigFunction`.

**Comment by acrobat** [comment]
@bmeloski There is a [pr open to replace the deprecated twig classes](https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/2449). But I don't think a deprecated class will trigger this kind of error. It seems to me that the twig extension providing this function is not enabled.

Can you check if the `bin/console debug:twig` command shows this function? If it doesn't show it, the article bundle or the twig extension it self is not activated.

**Comment by iknowfoobar** [comment]
This is because the default install of the bundles only adds the Article Bundle in dev mode, as the bundle isn't loaded in prod mode the twig function isn't available. You can fix it by just setting the bundle to be available in all environments in `config/bundles.php`

The recipe probably needs to be updated.

**Comment by acrobat** [comment]
The fix for existing applications is to change the available environments for the article-bundle to `Kunstmaan\ArticleBundle\KunstmaanArticleBundle::class => ['all' => true],`. New applications will work correctly as soon as Kunstmaan/cms-skeleton#4 is merged.
