### ISSUE TITLE
Issues just after installation

### ISSUE THREAD

**Issue by bhyassine** [Kunstmaan/KunstmaanBundlesCMS#2508]
Hello Every body,
I am new user of Kunstmaan and I was struggling for installing it properly for the last entire week.
After the installation was finally completed without errors, I was surprised to see that my admin console is not working at all, let me show you some images from my console:
https://ibb.co/93LKkRm
https://ibb.co/0X3THC1
You can see that the buttons are not showing very well, and the content can not be edited...

Also, this is how my home page looks like:
https://ibb.co/YbGV29S
First, I thought I would be creating my css files by myself, but after noticing the problems with the console admin, I started to think that there is a bug in the home page also...

Can someone show me how it should look like after a correct first installation (without the demo)? Any clue what is going wrong?
Thanks a lot!

**Comment by sim2github** [comment]
To complete demo-quest you need to compile assets.
You can find `scripts` section in `package.json` for available options
`$ npm install` and `$ npm run build` - for production or `$ npm run start` to start development

**Comment by bhyassine** [comment]
Hello, Thanks for replying...

In fact, I don't want to install the demo website, I just need that the website (icons, templates, ...) is shown in a good way, I run the npm commands but nothing changed...

**Comment by acrobat** [comment]
@bhyassine This issue tracker is used to keep track of bugs/feature request. If you need help setting up the cms or other question please [join the slack channel](https://github.com/Kunstmaan/KunstmaanBundlesCMS#community)!
