### ISSUE TITLE
[AdminListBundle] DateTimeTypeFilter is broken

### ISSUE THREAD

**Issue by lkeijmel** [Kunstmaan/KunstmaanBundlesCMS#2513]
We've just upgraded the CMS bundles to 5.2.4 and noticed a bug when using the datetime filters. The values of date and time aren't given correctly to the ORM because of the change in the template on commit https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/2159/commits/554ab55140951a4e65bf716256e9f29a18d3f444.

In src/Kunstmaan/AdminListBundle/Resources/views/FilterType/dateTimeFilter.html.twig the [date] and [time] suffixes are deleted and therefore these aren't available anymore.

**Comment by acrobat** [comment]
Fixed in #2534
