### ISSUE TITLE
[KunstmaanAdminBundle] Remove filter not working 

### ISSUE THREAD

**Issue by devl-hop** [Kunstmaan/KunstmaanBundlesCMS#2541]
Filter remove button not work:

![image](https://user-images.githubusercontent.com/9337979/63761951-42b6d600-c8c2-11e9-8b23-867a087f3856.png)

There is a uncompatible instruction on js:
Resources/ui/js/_app-filter.js     line 175
![image](https://user-images.githubusercontent.com/9337979/63762260-ccff3a00-c8c2-11e9-8dd6-95e47f66cff0.png)
The .size() method is deprecated as of jQuery 1.8. Use the .length property instead.

**Comment by acrobat** [comment]
Fixed in #2547
