### ISSUE TITLE
Errors trying to install the clean cms bundles

### ISSUE THREAD

**Issue by WADStefan** [Kunstmaan/KunstmaanBundlesCMS#256]
Dear Kunstmaan,

I've run into some issues installing the Kunstmaan bundles.
First thing I did was try to composer install the latest version. The following error occurred when composer tried to install the assets
![error1](https://cloud.githubusercontent.com/assets/11782618/6979880/2e74134a-d9ea-11e4-9b42-96b6ac1d9c4a.png)

After adding 
```yaml
    # app/config/security.yml
    security:
        acl:
            provider: ~
```
to security.yml, this problem was solved. The assets installed as intended.

Then I tried to create the database (according to the [documentation](http://bundles.kunstmaan.be/getting-started/installation)) which gave me the following error.
![error2](https://cloud.githubusercontent.com/assets/11782618/6979830/9d3bcfc6-d9e9-11e4-98a8-10253c7c1749.png)

How do I go about solving this discriminator issue in the vendors?

Regards,

Stefan Van den Heuvel

**Comment by woutervandamme** [comment]
make sure you get the latest dev branch: 

    composer create-project kunstmaan/bundles-standard-edition <path> -s dev;

And when it asks to install the AcmeDemoBundle, just enter no, it has some problems with it.
Here is a little script that does a setup of the demo site for you. you just have to awnser some question. https://gist.github.com/woutervandamme/dfe0f6c181f6177d8f3e

Use it like this

    ./create_site <path>

**Comment by denbatte** [comment]
Hi Stefan,

We are also experiencing the same issue. And are working on it at the moment.

**Comment by WADStefan** [comment]
@woutervandamme 
I've cleaned the folder and reinstalled using the latest master. This took care of the first issue right away, thank you for the comment.

The second issue, however, is still very much present when trying to create the database scheme.
@denbatte 
Is there an ETA on when this issue will be fixed or could you point me in a direction to fix this issue?

Thank you guys for the quick responses.

**Comment by roderik** [comment]
We found the issue, a pull request will follow any minute. There was a minor BC break in doctrine 2.5

**Comment by roderik** [comment]
Pull request merged!
