### ISSUE TITLE
[Question] How can I show page to an anonymous user, but not to a logged in one?

### ISSUE THREAD

**Issue by OskarStark** [Kunstmaan/KunstmaanBundlesCMS#2562]
Hi,

If I want use ACLs and want to grant an action to a **not** logged in user but this action should **not** be allowed to an **logged** in user, how can I achieve that?

Thanks in advance
Oskar

**Comment by acrobat** [comment]
@OskarStark what you could do is implement the `\Kunstmaan\NodeBundle\Controller\SlugActionInterface` and create a controller action to check the current user and verify is he is not logged in yet, otherwise throw an exception.

**Comment by acrobat** [comment]
Closing this for now as the question should be answered. If you still have questions, please leave a comment.
