### ISSUE TITLE
[AdminBundle] cms menu is collapsed when cms is opened

### ISSUE THREAD

**Issue by KimVW79** [Kunstmaan/KunstmaanBundlesCMS#2563]
When I open the cms...
Then the menu is collapsed into hamburger menu
I opened it in full screen resolution chrome (Version 77.0.3865.90 (Official Build) (64-bit)) and safari (Version 13.0.1 (14608.2.11.1.11)) and both show the same problem

**Comment by dbeerten** [comment]
The only way I could reproduce it is with zooming in/out the page.

**Comment by acrobat** [comment]
See #2615
