### ISSUE TITLE
Slack invitiation no longer valid

### ISSUE THREAD

**Issue by JoppeDC** [Kunstmaan/KunstmaanBundlesCMS#2567]
The slack invitation in the README is no longer valid, and should be updated to a fresh one.

**Comment by acrobat** [comment]
Thanks for the reminder, we will look into updating the link!

**Comment by acrobat** [comment]
Sorry for the late answer but the slack invite link was updated. You can now always get the latest (working) invite link through https://cms.kunstmaan.be/slack-invite
