### ISSUE TITLE
[QUESTION] Recommended upgrade path

### ISSUE THREAD

**Issue by jseparovic1** [Kunstmaan/KunstmaanBundlesCMS#2619]
Hi,

I'm running `kunstmaan/bundles-cms` version `3.6.3`. I'm wondering which upgrade path would you suggest? From 3.6 straight to 5.0 or linear approach 3.6 -> 4.0 -> 4.1 or something else?

Thanks in advance
Jure

**Comment by acrobat** [comment]
Hi @jseparovic1 

I would suggest upgrading straight to v5, then check the upgrade docs of all versions and fix all these things. afterwrds go through your application to see if there are still things missing or errors.
 
From version 5.0+ we implemented the deprecation model, so you are safe to upgrade to the latest v5.x release and fix the deprecations along the way.
