### ISSUE TITLE
Notice: Trying to access array offset on value of type null when choosing Internal Link

### ISSUE THREAD

**Issue by Warxcell** [Kunstmaan/KunstmaanBundlesCMS#2628]
https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/src/Kunstmaan/NodeBundle/Controller/WidgetsController.php#L194-L195

https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/src/Kunstmaan/AdminBundle/Helper/DomainConfiguration.php#L177

?

**Comment by acrobat** [comment]
@Warxcell I've created #2629 for this issue, can you verify if it fixes the php 7.4 incompatibilities?

**Comment by Warxcell** [comment]
Yup, all good now.

**Comment by acrobat** [comment]
Thanks for the feedback @Warxcell. The next 5.4 release will contain this fix!
