### ISSUE TITLE
'console' failed to run

### ISSUE THREAD

**Issue by spruit-digital** [Kunstmaan/KunstmaanBundlesCMS#2631]
Hi,
I'm trying to get the CMS up and running following the exact installation instructions, but fail at "bin/console kuma:install" which states: Program "console" failed to run"

`At line:1 char:1`
`+ bin/console kuma:install`
`+ ~~~~~~~~~~~~~~~~~~~~~~~~.`
`At line:1 char:1`
`+ bin/console kuma:install`
`+ ~~~~~~~~~~~~~~~~~~~~~~~~`
`    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException`
`    + FullyQualifiedErrorId : NativeCommandFailed`

**Comment by acrobat** [comment]
@spruit-digital Can you run the command with verbose or provide the output of the command so we have a bit more info where this error occurs.

**Comment by spruit-digital** [comment]
Hi,
I don't quite get what you mean (sorry, fairly new to this). 
I receive the following error;
`bin/console : The term 'bin/console' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of t
he name, or if a path was included, verify that the path is correct and try again.`
