### ISSUE TITLE
Unable to override Kunstmaan template

### ISSUE THREAD

**Issue by KevinSleegers** [Kunstmaan/KunstmaanBundlesCMS#2655]
Hi,

In all of our Kunstmaan projects we override the default Kunstmaan login template to add our own branding to the page. We do this via app/resources/KunstmaanAdminBundle/views/Security/login.html.twig and it works fine for all our projects that are < Symfony 3.4. However for newer projects this does not seem to work anymore.

I've read in the Symfony docs that they've added a new directory to override bundle templates (templates/bundle), but that does not seem to make any difference.

Is there anyone else who has faced the same issue and found a way to solve this?
Please let me know.

Kind regards,
Kevin

**Comment by JoppeDC** [comment]
I can confirm this, we have the exact same issue since upgrading to SF 4.x

**Comment by acrobat** [comment]
Fixed in #2656
