### ISSUE TITLE
Error on loading DefaultSiteFixtures

### ISSUE THREAD

**Issue by igst** [Kunstmaan/KunstmaanBundlesCMS#2667]
When running 

`bin/console doctrine:fixtures:load`

I get error:

`Notice: Trying to access array offset on value of type bool In ImageHandler.php line 96`

I'm using PHP 7.4.3 with installed GD.

See attached screenshots.
![error1](https://user-images.githubusercontent.com/5346377/81058030-e3d44280-8ecd-11ea-87f4-728c416aa1ad.png)
![error2](https://user-images.githubusercontent.com/5346377/81058034-e6cf3300-8ecd-11ea-9ee8-3fc62b149e11.png)
![testscript](https://user-images.githubusercontent.com/5346377/81058037-e767c980-8ecd-11ea-8ecc-1c2c8516680a.png)
![testscript_output](https://user-images.githubusercontent.com/5346377/81058039-e8006000-8ecd-11ea-8e70-a450f093d049.png)
![php_modules](https://user-images.githubusercontent.com/5346377/81058094-06fef200-8ece-11ea-8181-be666caf0888.png)

**Comment by acrobat** [comment]
@igst I've created a PR to fix this issue, can you verify if the patch in #2671 fixes the problem? Thanks!

**Comment by acrobat** [comment]
Fixed in #2671
