### ISSUE TITLE
ruflin/elastica first 7.0.0 stable release

### ISSUE THREAD

**Issue by MaximGns** [Kunstmaan/KunstmaanBundlesCMS#2688]
Found out that there is a new release from ruflin/elastica for ES 7+
https://github.com/ruflin/Elastica/releases/tag/7.0.0

**Comment by FilipDeJonghe** [comment]
Hello, when can we expect a new version of CMS with this plugin included? ES is already in version 7.7 and we should migrate asap for internal end of support reasons.
