### ISSUE TITLE
[AdminListBundle] Modify EnumerationFilterType to use js-advanced-select

### ISSUE THREAD

**Issue by molovo** [Kunstmaan/KunstmaanBundlesCMS#2689]
The standard multi-select box used for filtering with the EnumerationFilterType is very unwieldy to use when there is a long list of options. It would be much more user-friendly to enable the JS Advanced Select to allow searching through the options.

Attempts at implementing this internally failed as when the relevant classes are added to the enumeration field, the JS which builds the field names skips over any fields using the advanced select.

**Comment by acrobat** [comment]
Fixed in #2707
