### ISSUE TITLE
[TranslationBundle] Import/Export issue for translations

### ISSUE THREAD

**Issue by Devolicious** [Kunstmaan/KunstmaanBundlesCMS#2694]
When you export your translations and you are navigating in a different language than EN (cms language) you will receive an export with tranlated headers. That's fine in itself but when you want to reupload that document, because you made some changes, it will not accept the file because it doesn't recognize the headers. They must be in english.

**Comment by acrobat** [comment]
Will this be fixed with the changes in #2692 (the changes in the exportservice)?
