### ISSUE TITLE
[NodeSearchBundle] Elastica upgrade

### ISSUE THREAD

**Issue by MaximGns** [Kunstmaan/KunstmaanBundlesCMS#2698]
Upgraded kunstmaan cms to 5.6.1 for the new elastica 7 support. When i want to run the command bin/console it outputs this error. 

    docker@7206b212d826:/var/www/...$ bin/console --env=docker -vvv

In ExprBuilder.php line 189:

  [InvalidArgumentException]
    index must be one of: true, false

Exception trace:
    at /var/www/.../vendor/symfony/config/Definition/Builder/ExprBuilder.php:189
    Symfony\Component\Config\Definition\Builder\ExprBuilder->Symfony\Component\Config\Definition\Builder\{closure}() at /var/www/.../vendor/symfony/config/Definition/Builder/ExprBuilder.php:241
    Symfony\Component\Config\Definition\Builder\ExprBuilder::Symfony\Component\Config\Definition\Builder\{closure}() at /var/www/.../vendor/symfony/config/Definition/BaseNode.php:354
    Symfony\Component\Config\Definition\BaseNode->normalize() at /var/www/.../vendor/symfony/config/Definition/ArrayNode.php:292
    Symfony\Component\Config\Definition\ArrayNode->normalizeValue() at /var/www/.../vendor/symfony/config/Definition/BaseNode.php:382
    Symfony\Component\Config\Definition\BaseNode->normalize() at /var/www/.../vendor/symfony/config/Definition/PrototypedArrayNode.php:271
    Symfony\Component\Config\Definition\PrototypedArrayNode->normalizeValue() at /var/www/.../vendor/symfony/config/Definition/BaseNode.php:382
    Symfony\Component\Config\Definition\BaseNode->normalize() at /var/www/.../vendor/symfony/config/Definition/ArrayNode.php:292
    Symfony\Component\Config\Definition\ArrayNode->normalizeValue() at /var/www/.../vendor/symfony/config/Definition/BaseNode.php:382
    Symfony\Component\Config\Definition\BaseNode->normalize() at /var/www/.../vendor/symfony/config/Definition/Processor.php:34
    Symfony\Component\Config\Definition\Processor->process() at /var/www/.../vendor/symfony/config/Definition/Processor.php:50
    Symfony\Component\Config\Definition\Processor->processConfiguration() at /var/www/.../vendor/symfony/dependency-injection/Compiler/ValidateEnvPlaceholdersPass.php:84
    Symfony\Component\DependencyInjection\Compiler\ValidateEnvPlaceholdersPass->process() at /var/www/.../vendor/symfony/dependency-injection/Compiler/Compiler.php:94
    Symfony\Component\DependencyInjection\Compiler\Compiler->compile() at /var/www/.../vendor/symfony/dependency-injection/ContainerBuilder.php:762
    Symfony\Component\DependencyInjection\ContainerBuilder->compile() at /var/www/.../vendor/symfony/http-kernel/Kernel.php:596
    Symfony\Component\HttpKernel\Kernel->initializeContainer() at /var/www/.../vendor/symfony/http-kernel/Kernel.php:136
    Symfony\Component\HttpKernel\Kernel->boot() at /var/www/.../vendor/symfony/framework-bundle/Console/Application.php:169
    Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands() at /var/www/.../vendor/symfony/framework-bundle/Console/Application.php:75
    Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/.../vendor/symfony/console/Application.php:148
    Symfony\Component\Console\Application->run() at /var/www/.../bin/console:42

Upgraded from es 5 to es 7. Current yaml settings:

kunstmaan_search:
    connection:
        host: 'elasticsearch'
        port: 9200

Do i need to change something in the settings to make it work?

Kind regards

Mg.

**Comment by acrobat** [comment]
Can you define the parameter `kunstmaan_search.elasticsearch_version: 7` so you are sure that the NodeSearchBundle uses the correct elasticsearch mapping. 

From which version did you start the upgrade? And is there custom mapping defined in `kunstmaan_node_search.mapping`?

**Comment by MaximGns** [comment]
After adding kunstmaan_search.elasticsearch_version: 7 bin/console worked. Output from bin/console debug:config kunstmaan_node_search --env=xxxx

Current configuration for extension with alias "kunstmaan_node_search"
======================================================================

kunstmaan_node_search:
    mapping:
        root_id:
            type: integer
        node_id:
            type: integer
        nodetranslation_id:
            type: integer
        nodeversion_id:
            type: integer
        title:
            type: text
        slug:
            type: text
        type:
            type: keyword
        page_class:
            type: keyword
        content:
            type: text
        view_roles:
            type: keyword
    enable_update_listener: true
    use_match_query_for_title: false
    contexts: {  }

**Comment by acrobat** [comment]
@MaximGns The version check is sometimes a but buggy, especially if the elasticsearch host can't be reached, so it does a fallback to the older v2 mapping. By passing the used elasticsearch version with the parameter, the need for an actual connection to elasticsearch is removed. So this is more stable and will mostlikely speed up cache warmups.

As the command works, I'm closing the issue. If you experience any other issues feel free to leave a comment or reopen the issue (or create a new issue)!
