### ISSUE TITLE
[AdminBundle] white-october/pagerfanta-bundle is abandoned

### ISSUE THREAD

**Issue by iknowfoobar** [Kunstmaan/KunstmaanBundlesCMS#2704]
I have noticed that `white-october/pagerfanta-bundle` has been abandoned.

`babdev/pagerfanta-bundle` has been suggested as the replacement.

**Comment by acrobat** [comment]
`babdev/pagerfanta-bundle` can indeed be used as a replacement for the deprecated pagerfanta bundle, this is also needed for symfony 5 support!

**Comment by acrobat** [comment]
Fixed in #2773
