### ISSUE TITLE
Error where proceeding with import translation when file is not selected

### ISSUE THREAD

**Issue by krewetka** [Kunstmaan/KunstmaanBundlesCMS#2710]
**Steps to reproduce:**

Go to `admin/settings/translations/upload`

Click `Add translation` without selecting file

**Excepted behaviour:**

As input field is marked as required there should be validation message and import should not proceed

**Current behaviour:**

Error:

`Argument 1 passed to Kunstmaan\TranslatorBundle\Service\Command\Importer\Importer::importFromSpreadsheet() must be of the type string, null given, called in /app/vendor/kunstmaan/bundles-cms/src/Kunstmaan/TranslatorBundle/Controller/TranslatorController.php on line 219`

**Comment by acrobat** [comment]
Fixed in #2712
