### ISSUE TITLE
Controller deprecations

### ISSUE THREAD

**Issue by dannyvw** [Kunstmaan/KunstmaanBundlesCMS#2721]
User Deprecated: The "Kunstmaan\*Bundle\Controller\*Controller" class extends "Symfony\Bundle\FrameworkBundle\Controller\Controller" that is deprecated since Symfony 4.2, use "Symfony\Bundle\FrameworkBundle\Controller\AbstractController" instead.

**Comment by acrobat** [comment]
Follow up will happen in #2938
