### ISSUE TITLE
EventDispatcher deprecation

### ISSUE THREAD

**Issue by dannyvw** [Kunstmaan/KunstmaanBundlesCMS#2724]
User Deprecated: Calling the "Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch()" method with the event name as the first argument is deprecated since Symfony 4.3, pass it as the second argument and provide the event object as the first argument instead.

**Comment by acrobat** [comment]
Closing as a duplicate of #2722

**Comment by dannyvw** [comment]
@acrobat sorry had not refreshed my page :(
