### ISSUE TITLE
transchoice twig filter deprecation

### ISSUE THREAD

**Issue by dannyvw** [Kunstmaan/KunstmaanBundlesCMS#2725]
User Deprecated: Twig Filter "transchoice" is deprecated since version 4.2. Use "trans" with parameter "%count%" instead in vendor/kunstmaan/bundles-cms/src/Kunstmaan/AdminBundle/Resources/views/Form/fields.html.twig at line 294.

**Comment by acrobat** [comment]
@dannyvw how do you trigger this deprecation? As there is no `transchoice` filter on that line or not even in that file.

https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/14abe7b8b3156f578746235a94a8fefbfcb7e61c/src/Kunstmaan/AdminBundle/Resources/views/Form/fields.html.twig#L294

**Comment by dannyvw** [comment]
@acrobat I see that we revert this commit https://github.com/Kunstmaan/KunstmaanBundlesCMS/commit/3952540e67c63bccbbb695ad098802319fea90ed where the transchoice filter is used. See comment in https://github.com/Kunstmaan/KunstmaanBundlesCMS/issues/1584#issuecomment-383073641. Not sure if this is still needed in our codebase. I need to check that.

**Comment by acrobat** [comment]
@dannyvw ok! Create an issue if the original issue still exists!
