### ISSUE TITLE
[UserManagementBundle] How to fix kunstmaan_user_management.user_admin_list_configurator.class deprecation?

### ISSUE THREAD

**Issue by dannyvw** [Kunstmaan/KunstmaanBundlesCMS#2729]
How can we fix the kunstmaan_user_management.user_admin_list_configurator.class deprecation? The message says that you can define a alias for the class. But there is a parameter call in the controller and that is not a service. https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/src/Kunstmaan/UserManagementBundle/Controller/UsersController.php#L42

**Comment by acrobat** [comment]
@dannyvw this deprecation was indeed wrong and I've removed it in #2731. We will deprecate it again in a next minor with the correct upgrade path!

**Comment by acrobat** [comment]
Fixed in #2731
