### ISSUE TITLE
[AdminBundle] Textarea fields are very wide

### ISSUE THREAD

**Issue by dannyvw** [Kunstmaan/KunstmaanBundlesCMS#2732]
Text field fields are now very wide, see screenshot. Is this correct? Previously it was the same size as the title field which looks cleaner. This is changed in https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/2199

![textarea-seo-tab](https://user-images.githubusercontent.com/1218389/92732909-59b65200-f377-11ea-8fd1-77bbad03464e.png)

**Comment by acrobat** [comment]
Fixed in #2808
