### ISSUE TITLE
[AdminBundle] Fontawesome brands is not imported

### ISSUE THREAD

**Issue by dannyvw** [Kunstmaan/KunstmaanBundlesCMS#2733]
Before (in 5.0) is the icon fa-twitter available. But in the new version the brands are not loaded. Is it ok to add "@import "../../../../../../../../../../node_modules/@fortawesome/fontawesome-free/scss/brands";" to the imports in "_font-awesome-imports.scss"?

**Comment by acrobat** [comment]
Fixed in #2759
