### ISSUE TITLE
Admin: radio button are misaligned

### ISSUE THREAD

**Issue by kimausloos** [Kunstmaan/KunstmaanBundlesCMS#276]
See screenshot:

![screen shot 2015-04-08 at 09 53 29](https://cloud.githubusercontent.com/assets/493233/7041007/78980e88-ddd5-11e4-9352-42efb377127a.png)

**Comment by FVKVN** [comment]
@diskwriter can be closed

![image](https://cloud.githubusercontent.com/assets/4497591/13077388/ae284a10-d4b8-11e5-829a-dd6a50b9324f.png)
