### ISSUE TITLE
[AdminBundle] password forgot email should have css styling.

### ISSUE THREAD

**Issue by Numkil** [Kunstmaan/KunstmaanBundlesCMS#2777]
It would be good if the password forgot email would be styled. See the symfony guide on how to do that.

https://symfony.com/doc/current/mailer.html#inlining-css-styles

**Comment by acrobat** [comment]
Emails are now correctly styled with the improved authentication system (see https://github.com/Kunstmaan/KunstmaanBundlesCMS/discussions/2990)
