### ISSUE TITLE
Admin tree: unable to open link in new tab with cmd+click

### ISSUE THREAD

**Issue by kimausloos** [Kunstmaan/KunstmaanBundlesCMS#280]
With the previous version of jstree you could open a node in a new tab by cmd+click (default browser behaviour), with the current version the link always opens in the current tab.

**Comment by kimausloos** [comment]
This always opens the link in a new tab + focuses the tab, while default browser behaviour is open in background (so new tab, no focus change). Is it possible to handle that?

**Comment by LiesbethVanaerschot** [comment]
I think this one can be closed.
