### ISSUE TITLE
Use only KunstmaanMediaBundle without KunstmaanAdminBundle

### ISSUE THREAD

**Issue by cbeyer** [Kunstmaan/KunstmaanBundlesCMS#2850]
Hi,

I use KunstmaanMediaBundle for manipulating/uploading images. I don't need other Kunstmaan bundles, how can I deactivate admin and other NodeBundle ?

On my /login URL I see a Kunstmaan login page instead of my FOSUserBundle login page.

Thanks,

composer.json : "kunstmaan/media-bundle": "5.6"

**Comment by cbeyer** [comment]
I specify: when I go to `/login` I have the Kunstmaan login page. I don't want this because I already override FOSUserBundle. How to deactivate the Kunstmaan override which seems to be more priority ?

**Comment by acrobat** [comment]
Hi @cbeyer, what part of the media bundle do you want to use as a standalone component/what is the usecase? As the media bundle is a "media library" implemenation for the Kunstmaan CMS admin interface, so using it without the admin bundle would be strange.

**Comment by cbeyer** [comment]
I use the MediaManager as a "standalone service", for creating medias and using the informations stored in the `kuma_media` MySql table. My project is large and use others bundles like FOSUser.

Up to here this worked fine with `"kunstmaan/bundles-cms": "^5.1"` (Symfony 3.4), now I have problems upgrading to Symfony 4

**Comment by acrobat** [comment]
I think the problem here is that (maybe with symfony flex) the routes of the admin bundle are automatically registered and overriding your app routes.

Can you check if anywhere in your app the KunstmaanAdminBundle routes are registered/imported? So I think the "solution" here is just to remove that config import/setup so no existing routes are changed.

**Comment by cbeyer** [comment]
I have found a solution :

Composer.json : `"kunstmaan/media-bundle": "^5.7"`

Then, in config/bundles.php, I have removed some Kunstmaan bundles, keeping only 2 lines :

```
    Kunstmaan\UtilitiesBundle\KunstmaanUtilitiesBundle::class => ['all' => true],
    Kunstmaan\MediaBundle\KunstmaanMediaBundle::class => ['all' => true],
```
