### ISSUE TITLE
Symfony 5 support

### ISSUE THREAD

**Issue by dannyvw** [Kunstmaan/KunstmaanBundlesCMS#2852]
Can we add support for Symfony 5?

**Comment by acrobat** [comment]
@dannyvw you can track the progress on [symfony 5 support here](https://github.com/Kunstmaan/KunstmaanBundlesCMS/projects/6). There is already a lot of work done (deprecations etc) so we can support symfony 5 in 6.1, with the biggest chunk being #2737. 

There is still some work left but we're getting there!

**Comment by acrobat** [comment]
Symfony 5 support [was added in 6.1.0](https://github.com/Kunstmaan/KunstmaanBundlesCMS/discussions/3032)
