### ISSUE TITLE
Doctrine 2.13 breaks standard install

### ISSUE THREAD

**Issue by tarjei** [Kunstmaan/KunstmaanBundlesCMS#2867]
This is a bit of an heads up. 

When testing the standard install it gets broken due to the changes outlined here [1]. There is a PR in Symfony (https://github.com/symfony/security-acl/pull/64) for fixing this.

I just thought I'd note this here so anyone who tries Kunstmaan can find a workaround. 

### Workaround
Add an explicit dependency to doctrine/dbal 2.12 until the PR is merged and released.

```
diff --git a/composer.json b/composer.json
index 6148e6a..f6c56a8 100644
--- a/composer.json
+++ b/composer.json
@@ -62,6 +62,7 @@
         "symfony/twig-bundle": "^4.4",
         "symfony/validator": "^4.4",
         "symfony/web-link": "^4.4",
+       "doctrine/dbal": "2.12",
         "symfony/yaml": "^4.4"
     },
     "require-dev": {
```

1. https://www.doctrine-project.org/2021/03/29/dbal-2.13.html

**Comment by acrobat** [comment]
@tarjei @iknowfoobar the incompatibility in `symfony/security-acl` is [fixed in 3.1.2](https://github.com/symfony/security-acl/releases/tag/v3.1.2), so if you re-run a `composer update` (and remove the locked version of doctrine dbal as a workaround) the application should work as expected again!
