### ISSUE TITLE
[AdminBundle] ckeditor issue with npm install

### ISSUE THREAD

**Issue by dannyvw** [Kunstmaan/KunstmaanBundlesCMS#2874]
When running npm install it produces the following error

> git clone -b full/4.5.3 --single-branch https://github.com/ckeditor/ckeditor-releases.git node_modules/ckeditor

Cloning into 'node_modules/ckeditor'...
remote: Enumerating objects: 3609, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 3609 (delta 0), reused 0 (delta 0), pack-reused 3605
Receiving objects: 100% (3609/3609), 5.29 MiB | 7.86 MiB/s, done.
Resolving deltas: 100% (2145/2145), done.
Note: switching to '4e42a6d77a8792b665b36835a39fa379ccde4015'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

**Comment by acrobat** [comment]
Is it actually an error? I know git procudes output for this case, but does the install finish successfully and does `npm run build` work afterwards?

**Comment by dannyvw** [comment]
`npm run build` does not work because of a missing ckeditor file.

**Comment by acrobat** [comment]
@dannyvw what is the exact error you get? I did a local `npm install` and `npm run build` did run fine afterwards. Otherwise can you try to remove the `node_modules` directory and run npm install and run build again?

**Comment by dannyvw** [comment]
@acrobat I already did that, but a few days ago i have updated node and now i dont see the error anymore.. But it had something to do with a missing ckeditor file. It look liked that ckeditor was not installed. So maybe it had something to do with an older version of node. I close this issue and if i see it again i will reopen.
