### ISSUE TITLE
[MediaBundle] Vimeo thumbnail url not working

### ISSUE THREAD

**Issue by dannyvw** [Kunstmaan/KunstmaanBundlesCMS#2889]
The url used in https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/src/Kunstmaan/MediaBundle/Helper/RemoteVideo/RemoteVideoHandler.php#L124 is deprecated and returns now an empty file. So the thumbnail url will not be set anymore.

There are two options:

- We can use the new API, but then we need authentication
- Or we use the oembed link https://vimeo.com/api/oembed.json?url=https://vimeo.com/<videoid>

I think the oembed option is fine for now.

**Comment by acrobat** [comment]
Hi @dannyvw, thanks for the bug report! I think the oEmbed option is indeed the way to go for now.

https://developer.vimeo.com/api/oembed/videos#embedding-a-video-with-oembed-step-1
