### ISSUE TITLE
Sidebar should not be shown when it has no content

### ISSUE THREAD

**Issue by jockri** [Kunstmaan/KunstmaanBundlesCMS#295]
When you extend the default admin layout, and overwrite the sidebar block to remove all contents, the sidebar should not be shown.

![screenshot 2015-04-09 16 20 55](https://cloud.githubusercontent.com/assets/517574/7068717/95d9f11e-ded4-11e4-8558-e77e446ff92d.png)

**Comment by IbeVanmeenen** [comment]
"overwriting the sidebar block to remove all contents, the sidebar should not be shown" is not entirely the way to go. We will think this one trough.

**Comment by diskwriter** [comment]
@jockri What was the final decision here?

**Comment by sandergo90** [comment]
@jockri is there already a decision for this issue?
