### ISSUE TITLE
Fix actions for mobile

### ISSUE THREAD

**Issue by IbeVanmeenen** [Kunstmaan/KunstmaanBundlesCMS#297]
Actions don't work on mobile (tested on android, chrome):
- Add PagePart
- Delete PagePart
- Add Image (modal)

**Comment by IbeVanmeenen** [comment]
- Add PagePart and image seems to work now, delete not...

**Comment by IbeVanmeenen** [comment]
(only for chrome on android for now)

**Comment by jockri** [comment]
Cosed in favor of #1328
