### ISSUE TITLE
Fix robots.txt logic

### ISSUE THREAD

**Issue by jockri** [Kunstmaan/KunstmaanBundlesCMS#302]
[ ] Include the KunstmaanSeoBundle `routing.yml` in the StandardEdition: https://github.com/Kunstmaan/KunstmaanBundlesStandardEdition/blob/master/app/config/routing.yml
https://github.com/Kunstmaan/KunstmaanBundlesStandardEdition/blob/master/app/config/routing.singlelang.yml
[ ] Add the `RobotsController.php` to a `routing.yml` file, because it is not included for the moment
[ ] Use `Content-type "text/plain"` instead of `"text/html"` when returning the robots.txt contents
[ ] Do not replace `new lines` into `<br>` tags
[ ] Add information into the upgrade file that a new `routing.yml` should be included from the project root `routing.yml`
[ ] Move `RobotsController.php` one directory up

**Comment by denbatte** [comment]
Done, will squash all previous commits into one.
Also @roderik asked to add a preview button so I will do that now.

**Comment by roderik** [comment]
@denbatte status?

**Comment by denbatte** [comment]
Klaar
