### ISSUE TITLE
kuma:generate:pagepart ReflectionException

### ISSUE THREAD

**Issue by bureaublauwgeel** [Kunstmaan/KunstmaanBundlesCMS#303]
With the updated Pagepart generator you get the following exception:

Class *\**\Entity\PageParts\AbstractPagePart does not exist

* vendor
** bundle

It seems it doesn't add the standard Kunstmaan\PagePartBundle\Entity\PageParts\AbstractPagePart 

Steps to repoduce:
run: app/console kuma:generate:pagepart

When done with filling the info you get the exception.

OS: OSX 10.10
PHP version: 5.6.6
Symfony version: 2.6
CMS version : 3.1.0 Development

**Comment by krispypen** [comment]
This is fixed in #374
