### ISSUE TITLE
Redirects are broken in v6+

### ISSUE THREAD

**Issue by iknowfoobar** [Kunstmaan/KunstmaanBundlesCMS#3041]
I've recently upgraded a few sites to v6.1 from version 5 and all redirects are no longer working.

They all fail with the following error:

`The controller for URI "/en/my-redirect-page" is not callable: Controller "FrameworkBundle:Redirect:urlRedirect" does neither exist as service nor as class.`

I have verified by installing a fresh copy of Kunstmaan and redirects fail there with the same error too so I don't think I have missed something when upgrading.

PHP v8.0.13

**Comment by acrobat** [comment]
@iknowfoobar Can you try the patch in #3042? Thanks!

**Comment by iknowfoobar** [comment]
Hi @acrobat sorry for the delay, that patch is all working for me thanks!
