### ISSUE TITLE
[DashboardBundle] ConfigHelper requires `kuma_analytics_config` table to be present on constuct

### ISSUE THREAD

**Issue by jazzzpor** [Kunstmaan/KunstmaanBundlesCMS#3044]
Steps to reproduce:

1. Create new checkout of project with KunstmaanDashboardBundle enabled
2. run `composer install`
3. run `bin/console`

Expected result: A list of commands that are available
Actual result: "SQLSTATE[42S02]: Base table or view not found: 1146 Table 'amarant.kuma_analytics_config' doesn't exist "

The problem lies within `\Kunstmaan\DashboardBundle\Helper\Google\Analytics\ConfigHelper`. 
This service calls an `init` method on constuct which in turn assumes the database is up and running. 

I'm working on a PR and will submit it when it's done.

**Comment by acrobat** [comment]
@jazzzpor can you check if #3056 fixes your problem? This should workaround the issue and allows us to really refactor that class in the future.

**Comment by jazzzpor** [comment]
@acrobat #3056 does indeed fix the problem :+1:

**Comment by acrobat** [comment]
Thanks for verifying!
