### ISSUE TITLE
Admin list of specific page type

### ISSUE THREAD

**Issue by konstantinsp** [Kunstmaan/KunstmaanBundlesCMS#306]
Hello,
I have a page type that is added to different pages in the node tree.
I want to be able to edit them in one place(e.g. from modules menu).
currently the app/console kuma:generate:article generates overview page and all the nodes are connected to that page.

could some one direct me on how to make such page in admin interface?

**Comment by krispypen** [comment]
At the moment it's not supported to have pages at multiple locations in the three. This is also not a good idea for SEO reasons.
