### ISSUE TITLE
Adding a space in a slug triggers a 500 error instead of validation error. 

### ISSUE THREAD

**Issue by Numkil** [Kunstmaan/KunstmaanBundlesCMS#3067]
Adding a space in a slug triggers a 500 error instead of validation error. 
This is exceptionally annoying if you added a lot of content as everything will be lost. 

[request] Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Parameter "url" for route "_slug" must match "[a-zA-Z0-9\-_\/]*" ("test url with spaces" given) to generate a corresponding URL.") in "KunstmaanNodeBundle:Form:formWidgets.html.twig"." at /opt/projects/mensura/data/builds/mensura-b56eb6b58/vendor/twig/twig/src/Template.php line 196

<img width="488" alt="image" src="https://user-images.githubusercontent.com/5604686/151000753-95b9c83d-e8cf-4af8-9beb-f1af594d2e6a.png">

I will make a PR shortly.

**Comment by acrobat** [comment]
Fixed in #3068
