### ISSUE TITLE
AdminListBundle is broken with Doctrine 2.5.

### ISSUE THREAD

**Issue by iknowfoobar** [Kunstmaan/KunstmaanBundlesCMS#307]
All of the my Admin Lists (All index pages under the Modules section in the admin area) are now broken after updating to Doctrine 2.5

They all throw the following error:

`An exception has been thrown during the rendering of a template ("Cannot select distinct identifiers from query with LIMIT and ORDER BY on a column from a fetch joined to-many association. Use output walkers.") in KunstmaanAdminListBundle:AdminListTwigExtension:widget.html.twig at line 43.`

Rolling back to Doctrine 2.4.7 is a temporary fix for me.

**Comment by roderik** [comment]
Is this in combination with the CMS at dev-master? Or with 3.0.3?

**Comment by iknowfoobar** [comment]
Hi, sorry this is with 3.0.3 on PHP 5.5.22


> On 11 Apr 2015, at 06:50, Roderik van der Veer <notifications@github.com> wrote:
> 
> Is this in combination with the CMS at dev-master? Or with 3.0.3?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/Kunstmaan/KunstmaanBundlesCMS/issues/307#issuecomment-91766985>.
> 

Giles Smith
Technical Director
Superrb Studio
------------------------------------------
Studio. +44(0) 20 3397 9784 <>
Mobile. +44(0) 7775 938391 <>
Twitter. @superrbstudio <http://twitter.com/superrbstudio>
Facebook. facebook.com/superrb <http://www.facebook.com/superrb>
------------------------------------------
Hayling Island
------------------------------------------
http://superrb.com <http://www.superrb.com/>
------------------------------------------

**Comment by roderik** [comment]
I just tagged 3.1.0 this morning, could you try that version? I can't reproduce it with that version

**Comment by iknowfoobar** [comment]
Hi Roderik

I still have the same problem with 3.1.0 and Doctrine 2.5, swapping back to 2.4.7 fixes it. This is happening on 2 different sites as well.

Both are a relatively new install of KunstmaanCMS and we haven’t done anything significant other than create a few page parts and admin lists. All of the Admin List sections that are showing errors were created using the generators.

Let me know if I can provide you with more information or access to our code etc?


> On 11 Apr 2015, at 10:25, Roderik van der Veer <notifications@github.com> wrote:
> 
> I just tagged 3.1.0 this morning, could you try that version? I can't reproduce it with that version
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/Kunstmaan/KunstmaanBundlesCMS/issues/307#issuecomment-91798638>.
> 

Giles Smith
Technical Director
Superrb Studio
------------------------------------------
Studio. +44(0) 20 3397 9784 <>
Mobile. +44(0) 7775 938391 <>
Twitter. @superrbstudio <http://twitter.com/superrbstudio>
Facebook. facebook.com/superrb <http://www.facebook.com/superrb>
------------------------------------------
Hayling Island
------------------------------------------
http://superrb.com <http://www.superrb.com/>
------------------------------------------

**Comment by roderik** [comment]
Weird, could you open an issue on github?



*Roderik van der Veer*Technology Director


Kunstmaan nv   Philipssite 5 bus 10   3001 Leuven
T +32 (0)16 300 780    F +32 (0)16 300 789
www.kunstmaan.be

**Comment by mtnorthrop** [comment]
I'm seeing this issue as well.

The admin lists that I've generated with ```kuma:generate:adminlist``` work fine. However, when I ran ```kuma:generate:article```, the generated News Pages admin list index page shows this error:
```
An exception has been thrown during the rendering of a template ("Cannot select distinct identifiers from query with LIMIT and ORDER BY on a column from a fetch joined to-many association. Use output walkers.") in KunstmaanAdminListBundle:AdminListTwigExtension:widget.html.twig at line 15.
```
In the logs on the exception page, this is the SQL statement that appears right before the exception is recorded:
```
DEBUG - SELECT count(DISTINCT k0_.id) AS sclr_0 FROM kuma_node_translations k0_ INNER JOIN kuma_nodes k1_ ON k0_.node_id = k1_.id AND (k0_.node_id = k1_.id) INNER JOIN kuma_node_versions k2_ ON k0_.id = k2_.node_translation_id AND (k0_.public_node_version_id = k2_.id) JOIN (SELECT DISTINCT o.object_identifier as id FROM nlpv2s2.acl_object_identities as o INNER JOIN nlpv2s2.acl_classes c ON c.id = o.class_id LEFT JOIN nlpv2s2.acl_entries e ON ( e.class_id = o.class_id AND (e.object_identity_id = o.id OR e.object_identity_id IS NULL) ) LEFT JOIN nlpv2s2.acl_security_identities s ON ( s.id = e.security_identity_id ) WHERE c.class_type = "Kunstmaan\\NodeBundle\\Entity\\Node" AND (s.identifier = "IS_AUTHENTICATED_ANONYMOUSLY" OR s.identifier = "ROLE_SUPER_ADMIN" OR s.identifier = "ROLE_PERMISSIONMANAGER" OR s.identifier = "ROLE_ADMIN" OR s.identifier = "ROLE_ALLOWED_TO_SWITCH" OR s.identifier = "Kunstmaan\\AdminBundle\\Entity\\User-admin") AND e.mask & 4 > 0) ta_ ON k1_.id = ta_.id WHERE 1 = 1 AND k0_.lang = ? AND k1_.deleted = 0 AND k1_.ref_entity_name = ?
```
Strangely enough, this problem doesn't appear on the generated News Authors admin list index.

I'm using KunstmaanCMS 3.1.0 and Doctrine 2.5. Also, I'm only using a single locale.

I'm not familiar enough with KunstmaanCMS and Symfony to be able to make any useful suggestions on how to fix this, but I hope that this debug information can help point you in the right direction.

**Comment by fundup** [comment]
Thanks. I had the same issue and your commit fixed it
