### ISSUE TITLE
[AdminBundle] User fields have a different column name

### ISSUE THREAD

**Issue by dannyvw** [Kunstmaan/KunstmaanBundlesCMS#3077]
After upgrading to 5.10.2 the user table generates a migration. In https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/5.10/src/Kunstmaan/AdminBundle/Entity/BaseUser.php#L41 there is no column_name defined as before in https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Resources/config/doctrine-mapping/User.orm.xml#L11

`$this->addSql('ALTER TABLE kuma_users ADD usernameCanonical VARCHAR(180) NOT NULL, ADD emailCanonical VARCHAR(180) NOT NULL, ADD confirmationToken VARCHAR(255) DEFAULT NULL, DROP username_canonical, DROP email_canonical, DROP confirmation_token, DROP password_requested_at, CHANGE salt salt VARCHAR(100) DEFAULT NULL, CHANGE password password VARCHAR(100) NOT NULL');`

Also passwordRequestedAt is dropped and the methods (https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/5.10/src/Kunstmaan/AdminBundle/Entity/BaseUser.php#L694) are now returning always a hardcoded value. Is this a BC break?

**Comment by acrobat** [comment]
@dannyvw can you test this fix in #3097? Thanks!

**Comment by acrobat** [comment]
@dannyvw follow up question on this, is the actual removal of `isCredentialsNonExpired` and other deprecated methods/properties a problem for your projects or is that part ok?

**Comment by dannyvw** [comment]
@acrobat No, that's fine!
