### ISSUE TITLE
[UserManagement] User events are removed

### ISSUE THREAD

**Issue by dannyvw** [Kunstmaan/KunstmaanBundlesCMS#3095]
In https://github.com/Kunstmaan/KunstmaanBundlesCMS/commit/15278120fdcc107ff6c786e4fe4ef774368bcc69#diff-a0b5567e80e4ee6d143b2340980ea82f7d60b1bd1a9aeb8f16cdbb52b4ae40e7 (Kunstmaan 6.x) the USER_EDIT_INITIALIZE and USER_DELETE_INITIALIZE are removed without notice. Can this be restored because we need this events.

In Kunstmaan 5.10 is still uses the FOS Event.

**Comment by acrobat** [comment]
Those events are indeed remove and should have been described in the UPGRADE doc. What are the use cases you have for these events? Just to know if it needs a "PreDelete" kind of event in the submit logic or just on load of that controller action

**Comment by dannyvw** [comment]
@acrobat See https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/1169

**Comment by acrobat** [comment]
@dannyvw Can you check #3099? I've restored the events but created a dedicated event class for each event, so you need to change the typehints in your subscribers/listeners
