### ISSUE TITLE
[MultiDomainBundle] Deprecated parameter called

### ISSUE THREAD

**Issue by dannyvw** [Kunstmaan/KunstmaanBundlesCMS#3096]
Using the "kunstmaan_node.slugrouter.class" parameter to change the class of the service definition is deprecated in KunstmaanNodeBundle 5.2 and will be removed in KunstmaanNodeBundle 6.0. Use service decoration or a service alias instead.

https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/6.x/src/Kunstmaan/MultiDomainBundle/DependencyInjection/KunstmaanMultiDomainExtension.php#L40

**Comment by acrobat** [comment]
Well this was actually a special case as the deprecation was there to avoid external overrides with the parameter, but it should indeed have been kept for the multidomain bundle. This override will also be solved in the future by a proper service alias, but that will be done in a next refactor.

I've restored the behaviour in #3098 so it can be refactored later
