### ISSUE TITLE
[MediaBundle] When you start dragging an existing image in the media manager, the upload bubble appears

### ISSUE THREAD

**Issue by jockri** [Kunstmaan/KunstmaanBundlesCMS#312]
![screenshot 2015-04-13 10 06 59](https://cloud.githubusercontent.com/assets/517574/7112089/95bddaac-e1c6-11e4-87c6-de3ab05e7ee3.png)

**Comment by IbeVanmeenen** [comment]
Fix dragging existing image and add translations
