### ISSUE TITLE
UrlChooserType search for nodes broken

### ISSUE THREAD

**Issue by kdrsites** [Kunstmaan/KunstmaanBundlesCMS#3126]
Hello,

In version 6.1.3 in combination with symfony 5.4.5 i've came along a broken link. If you want to select a Node in the UrlChooserType, when trying to search in the modal it gets send to a broken link.

In the src/Kunstmaan/AdminBundle/Resources/ui/js/_app-urlchooser-tree.js on line 90, _search gets added after the url:

'url': $fetchUrl + "_search",

But I can't find a route with _search behind it. Does anyone know what could go wrong here?

Thanks in advance!

Kevin

**Comment by acrobat** [comment]
Thanks for the report @kdrsites. This is fixed in #3127
