### ISSUE TITLE
Page SEO extra meta data is being dumped to page.

### ISSUE THREAD

**Issue by iknowfoobar** [Kunstmaan/KunstmaanBundlesCMS#3131]
I've noticed since upgrading all our sites to Kuma 6.1 and Symfony 5.4 that the extra meta data field for all pages is no longer working correctly.

It is outputting escaped src (visible to the visitor) rather than the raw HTML.

PHP 8.0
Symfony 5.4
Kunstmaan 6.1

**Comment by acrobat** [comment]
Possibly related to this change #3038

**Comment by dannyvw** [comment]
@acrobat Confirmed that it is related to #3038. We have the same issue.

**Comment by acrobat** [comment]
@iknowfoobar @dannyvw I've created a pr to revert the breaking change!

**Comment by acrobat** [comment]
Fixed in #3133

**Comment by iknowfoobar** [comment]
Hi @acrobat do you know when this fix might be released?

**Comment by acrobat** [comment]
Hi @iknowfoobar, I'm a bit behind on PR's and issues but I will look into it to create a release in the next few days!

**Comment by iknowfoobar** [comment]
@acrobat thanks thats great!

**Comment by iknowfoobar** [comment]
Hi @acrobat I know you guys are super busy, but is there any chance we could get a timeline on when the next release with this fix is out?
We are getting a lot of pressure from our clients and need to decide whether we move them onto dev branches so their sites work again, then swap them back later or continue to wait for the release.
Thanks

**Comment by acrobat** [comment]
Sorry for the delay @iknowfoobar! I've just tagged 5.10.5 with this fix included, patch releases for 6.x will be done tomorrow!

**Comment by iknowfoobar** [comment]
Hi @acrobat that is great, however 6.1.4 now has a fatal error in the media bundle. I'll log it as a separate issue.

**Comment by acrobat** [comment]
Ok I will check it out when you created the issue!
