### ISSUE TITLE
[MediaPagePartBundle] __toString() returns null

### ISSUE THREAD

**Issue by dannyvw** [Kunstmaan/KunstmaanBundlesCMS#3134]
__toString() needs to return a string but getUrl() can be null https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/6.x/src/Kunstmaan/MediaPagePartBundle/Entity/VideoPagePart.php#L56

Possible the same for the other entities in this bundle

**Comment by acrobat** [comment]
Fixed in #3135
