### ISSUE TITLE
AdminListBundle Index page buttons not functional in 3.1.0

### ISSUE THREAD

**Issue by iknowfoobar** [Kunstmaan/KunstmaanBundlesCMS#314]
Since upgrading to 3.1.0 from 3.0.3 the buttons at the top right of any AdminListBundle index page have stopped working. It appears that there should be some javascript to provide the functionality, but this doesn't appear to be loading.

![screen shot 2015-04-13 at 10 26 27](https://cloud.githubusercontent.com/assets/255807/7113038/d2cd3edc-e1c7-11e4-83c3-e5c86d89c0e5.png)

As you can see the text link is there, but it only links to '#'

**Comment by roderik** [comment]
We just updated the upgrade docs this morning, had the same issue :) https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/313

**Comment by iknowfoobar** [comment]
Thanks

> On 13 Apr 2015, at 10:32, Roderik van der Veer <notifications@github.com> wrote:
> 
> We just updated the upgrade docs this morning, had the same issue :) #313 <https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/313>
> —
> Reply to this email directly or view it on GitHub <https://github.com/Kunstmaan/KunstmaanBundlesCMS/issues/314#issuecomment-92291610>.
> 

Giles Smith
Technical Director
Superrb Studio
------------------------------------------
Studio. +44(0) 20 3397 9784 <>
Mobile. +44(0) 7775 938391 <>
Twitter. @superrbstudio <http://twitter.com/superrbstudio>
Facebook. facebook.com/superrb <http://www.facebook.com/superrb>
------------------------------------------
Hayling Island
------------------------------------------
http://superrb.com <http://www.superrb.com/>
------------------------------------------
