### ISSUE TITLE
[NodeBundle] Error "Please specify a type of page you want to create"

### ISSUE THREAD

**Issue by dannyvw** [Kunstmaan/KunstmaanBundlesCMS#3191]
`$request->request->get('type');` is empty and `$request->query->get('type');` not
 https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/6.2/src/Kunstmaan/NodeBundle/Controller/NodeAdminController.php#L1223

**Comment by acrobat** [comment]
@dannyvw can you check if #3192 fixes the issue?

**Comment by dannyvw** [comment]
@acrobat Yes that is working
