### ISSUE TITLE
[AdminBundle] User entity implements the Serializable interface, which is deprecated

### ISSUE THREAD

**Issue by dannyvw** [Kunstmaan/KunstmaanBundlesCMS#3198]
implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) 

https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/6.x/src/Kunstmaan/AdminBundle/Entity/UserInterface.php#L7

**Comment by acrobat** [comment]
Do you only implement the `UserInterface` or extend from the `BaseUser`? As this deprecation should be resolved with https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/3012 in the BaseUser

**Comment by dannyvw** [comment]
That commit should indeed fix the issue. We extend from the `BaseUser`. Yesterday I had this deprecation but now I don't see it anymore. So will close this issue.
