### ISSUE TITLE
CSS error when building assets

### ISSUE THREAD

**Issue by ajakov** [Kunstmaan/KunstmaanBundlesCMS#3206]
After following the installation instructions found on this link: [https://kunstmaanbundlescms.readthedocs.io/en/latest/installation/#installation-with-kunstmaancms-skeleton](url)

I get this error when running `npm run build`

```
'cssOptimized' errored after 207 ms
[16:57:01] Error: Sass Error:
node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_variables.scss
Error: Invalid CSS after "...     floor(math": expected expression (e.g. 1px, bold), was ".div($grid-gutter-w"
        on line 369 of node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_variables.scss
        from line 10 of assets/ui/scss/config/vendors/_bootstrap-imports.scss
        from line 22 of assets/ui/scss/config/_config.scss
        from line 12 of assets/ui/scss/style.scss
>> vbar-padding-horizontal:        floor(math.div($grid-gutter-width, 2)) !defa
...
```

**Comment by acrobat** [comment]
Hi @ajakov, which version of node do you use? And is this an existing project or is it a new setup with 6.1? In the second case the installation script should produce a FE setup with node 16 in the `.nvmrc` and this installs correctly for me (`nvm use && npm install && npm run build`)

**Comment by FVKVN** [comment]
see: https://github.com/twbs/bootstrap-sass/issues/1230 
[Limit bootstrap-sass to 3.4.1 to fix issues with the build](https://github.com/netgen-layouts/layouts-ui/commit/6cfc3f02975c60b0872341d007209fa5f0de17bc) …

**Comment by acrobat** [comment]
@ajakov the dependency version is updated in #3253 for newly generated projects, to fix it in existing projects you can copy the changes from that PR.
