### ISSUE TITLE
Allow overriding of Rich Text toolbar.

### ISSUE THREAD

**Issue by iknowfoobar** [Kunstmaan/KunstmaanBundlesCMS#321]
It appears that as of 3.1 the configuration of the CKEditor toolbars is now hard coded into /AdminBundle/Resources/ui/js/_rich-editor.js

In previous versions it was simple to override the configuration of CKEditor by overriding parts of the template, now it seems to be impossible.

I have several use cases where I would like to be able to change the available toolbar options on a per site basis. Is it possible to do this?

**Comment by denbatte** [comment]
Hi,

Thank you for reporting.
We discussed this in the team and we will make an update to allow users to override the config.
I will make a ticket and reference it here.

**Comment by diskwriter** [comment]
This possibility has been re-added. 
(See https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/375)

You can now override a twig file and add your own custom configuration for the ckeditors.
