### ISSUE TITLE
[GeneratorBundle] kernel.root_dir not exist

### ISSUE THREAD

**Issue by dannyvw** [Kunstmaan/KunstmaanBundlesCMS#3217]
`kernel.root_dir` doesn't exists in Symfony 5.x 

https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/6.x/src/Kunstmaan/GeneratorBundle/Command/KunstmaanGenerateCommand.php#L100

**Comment by acrobat** [comment]
@dannyvw do you get an error on this parameter? As this code should only be called by the generators when running on symfony 4

**Comment by dannyvw** [comment]
@acrobat Yes, but we have override some methods. So I think that the problem is there. I have already fixed in on our side. So if this is only called for Symfony 4, in this bundle, then the issue can be closed.
