### ISSUE TITLE
Image url is removed when converting urls to tokens in WYSIWYG editor.

### ISSUE THREAD

**Issue by tarjei** [Kunstmaan/KunstmaanBundlesCMS#3224]
Hi, I got a problem with  WYSIWYG fields. 

If a user inserts an image the image will be stored as 

`<img alt="" data-cke-saved-src="/uploads/media/5da86cf7cb5ed/ams-sikringskap.jpg?token=[M132]" src="/uploads/media/5da86cf7cb5ed/ams-sikringskap.jpg?token=[M132]">
`
but when the user then wants to edit the text later, the img tag has been reduced to 

`<img alt="" data-cke-saved-src="%5BM133%5D" src="%5BM133%5D">` 

 which results in the images missing when editing texts.

NB:  (The tokens are different - that is not the issue here).

This is using Kunstmaan 6.1.5.

**Comment by acrobat** [comment]
Fixed in #3225
