### ISSUE TITLE
[NodeBundle] Would be nice to have "common/non-translatable" datafields

### ISSUE THREAD

**Issue by markmedia** [Kunstmaan/KunstmaanBundlesCMS#326]
Pages can include for ex. "technical data" which is same in every language. Any way you have solved this in your projects? 

Finest solution would be the "Common" tab with own pageparts.

**Comment by krispypen** [comment]
Can you give an example? Maybe you can put all your data in an adminlist under modules? So the data is lang independent, but is it also version independent?

**Comment by markmedia** [comment]
For example "Hotel list" module. 
Every hotel have the same gallery, adress, coordinates, phone number etc..

In our old cms "common tab" was pretty useful, we had non-translatable fields in common + translatable fields under each domain. Screenshot:
![common](https://cloud.githubusercontent.com/assets/1831978/7366083/6bfebe1e-ed9e-11e4-8597-95fa672c7c1c.jpg)

**Comment by wimvds** [comment]
We usually solve that in a different way. We create entities that contain the non translatable info and link such an entity to the relevant page type. So in your example you would end up with a Hotel entity containing all of your fields in the common tab, and a HotelPage that contains a (ManyToOne) reference to a Hotel entity. You can also embed the form to edit the common data on a new tab of the page if you want, by using a listener (listening to the kunstmaan_node.adaptForm event).

**Comment by markmedia** [comment]
Update: new screenshot, just for ideas - we also had additional properties with tagging options on entities.

**Comment by konstantinsp** [comment]
so you will still have to add this non translatable entity to the each translation of hotel?
and if you embed the form how could you choose the same entity for page translations?

**Comment by kimausloos** [comment]
You could add a tab with that kind of information. Have a look at the SEOBundle tab:
https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/src/Kunstmaan/SeoBundle/EventListener/NodeListener.php#L40

There we fetch the SEO data (translated in this case), but it doesn't have to be if you use the nodeId and not the nodeTranslationId or entityId. Then you only have to create an entity with a link to the NodeEntity.

**Comment by markmedia** [comment]
Thank you kimausloos for the suggestion, we can try it out. 
The coolest functionality for a customer would be the ability to add custom fields/pageparts also to that new (common) tab. So we don't need to add new fields manually every time needed.

**Comment by kimausloos** [comment]
I think that's possible too, you can implement a new tab (see [here](https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/src/Kunstmaan/AdminBundle/Helper/FormWidgets/Tabs/Tab.php) ) or add a collection in the entity, depending on your use case.

**Comment by sandergo90** [comment]
@jockri close
