### ISSUE TITLE
[NodeBundle] UrlHelper getMedia can return boolean

### ISSUE THREAD

**Issue by dannyvw** [Kunstmaan/KunstmaanBundlesCMS#3315]
This method https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/6.x/src/Kunstmaan/NodeBundle/Helper/URLHelper.php#L140 can return a boolean if the media is not found. getNodeTranslation has the same issue.

Error: Kunstmaan\NodeBundle\Helper\URLHelper::getMedia(): Return value must be of type array, bool returned

**Comment by acrobat** [comment]
Fixed in #3442
