### ISSUE TITLE
Strange Fatal Error after upgrading to 3.1

### ISSUE THREAD

**Issue by iknowfoobar** [Kunstmaan/KunstmaanBundlesCMS#332]
I have a KunstmaanBundles site that keep throwing a strange error in production mode. This is after a few hours of the site working fine.

`PHP Fatal error:  Call to undefined method Kunstmaan\\MediaBundle\\Helper\\File\\FileHandler::setBlacklistedExtensions() in /home/fasset/fassettechnologies.co.uk/httpdocs/app/cache/prod/appProdProjectContainer.php on line 1471`

Restarting Apache2 fixes the problem but it always comes back after a few hours. This is on Ubuntu 14.04 and PHP 5.5.9 with APCu. There are several other Symfony2 sites on the same server but only 1 other KunstmaanBundles site (3.0.3)

I am trying it at the moment with APC turned off to see if I can isolate the problem.

**Comment by iknowfoobar** [comment]
This may just be a memory issue on a server with a small amount of RAM. I upgraded the web server this was happening on from 2GB to 4GB and so far it hasn't happened again.

**Comment by iknowfoobar** [comment]
Unfortunately this is still happening, now on 2 different sites (both 3.1) on 2 different servers (Same set up). I don't have any more information other than both give the same error as above and restarting Apache fixes it.

**Comment by roderik** [comment]
Do you have "unique" apc prefixes in app.php?
Do you clear caches and apc with deploys?

**Comment by iknowfoobar** [comment]
Ahhh, not sure how I have got so far with Symfony without noticing the prefix in the app.php. I always assumed it was done automatically. Not sure how I have never had this problem before!

I have changed the prefix to something unique on all the Symfony sites on those servers and will see if it still happens.

**Comment by iknowfoobar** [comment]
Looks like it was my apc prefixes. Everything fine today. Thanks for your help.
