### ISSUE TITLE
Kunstmaan 7 testing errors

### ISSUE THREAD

**Issue by KevinSleegers** [Kunstmaan/KunstmaanBundlesCMS#3321]
Hi guys,

We've been doing some testing with Kunstmaan 7 and Symfony 6.4. The list below contains errors we've encountered so far. Any new errors will be added to the list.

- [x] **Saving page permissions**

This can be fixed by replacing `$changes = $request->request->get(‘permission-hidden-fields');` with `$changes = $request->request->all('permission-hidden-fields');` In `kunstmaan/admin-bundle/Helper/Security/Acl/Permission/PermissionAdmin.php` on line 217 since this returns an array.

- [x] **Saving new page parts**

This can be fixed by replacing `$newRefIds = $request->request->get($this->context . '_new');` with `$newRefIds = $request->request->all($this->context . '_new');` In `kunstmaan/pagepart-bundle/PagePartAdmin/PagePartAdmin.php` on line 189 since this returns an array.

- [x] **Existing page parts aren’t rendered**

This can be fixed by replacing `if (!\is_null($sequences)) {` with `if (!empty($sequences)) {` In `kunstmaan/pagepart-bundle/PagePartAdmin/PagePartAdmin.php` on line 203 since the `$sequences` is always an array.

- [x] **Enabling the toolbar helper**

This can be fixed by replacing `$authenticated = $token->isAuthenticated();` with `if (null !== $token) {        $authenticated = true; }` In `kunstmaan/admin-bundle/EventListener/ToolbarListener.php` on line 150 since a token is always authenticated.

- [x] **Configuration page cannot be accessed**

This can be fixed by replacing `_controller: kunstmaan_config.controller.config:indexAction` with `_controller: kunstmaan_config.controller.config::indexAction` In `kunstmaan/config-bundle/Resources/config/routing.yml` on line 4.

- [x] **Selecting page in URL chooser is not working**

This can be fixed by replacing `defaults: { _controller: kunstmaan_node.url_replace.controller:replaceURLAction }` with `defaults: { _controller: kunstmaan_node.url_replace.controller::replaceURLAction }` In `kunstmaan/node-bundle/Resources/config/routing.yml` on line 14.

**Comment by acrobat** [comment]
@KevinSleegers thanks for the extensive testing! I've created #3322 to fix the issues!
