### ISSUE TITLE
[AdminBundle][NodeBundle] The "Symfony\Bridge\Monolog\Logger" class is deprecated,

### ISSUE THREAD

**Issue by dannyvw** [Kunstmaan/KunstmaanBundlesCMS#3391]
User Deprecated: Since symfony/monolog-bridge 6.4: The "Symfony\Bridge\Monolog\Logger" class is deprecated, use HttpKernel's DebugLoggerConfigurator instead.

**Comment by acrobat** [comment]
Fixed in #3398
