### ISSUE TITLE
[NodeBundle] Doctrine deprecations

### ISSUE THREAD

**Issue by dannyvw** [Kunstmaan/KunstmaanBundlesCMS#3392]
Method Doctrine\ORM\Event\OnFlushEventArgs::getEntityManager() is deprecated and will be removed in Doctrine ORM 3.0. Use getObjectManager() instead. (OnFlushEventArgs.php:29 called by NodeTranslationListener.php:107

LifecycleEventArgs is deprecated with getEntity and getEntityManager

**Comment by acrobat** [comment]
Fixed in #3388
