### ISSUE TITLE
Update KnpGaufretteBundle to 0.9 to fix deprecations

### ISSUE THREAD

**Issue by dannyvw** [Kunstmaan/KunstmaanBundlesCMS#3393]

**Comment by acrobat** [comment]
We don't force a specific version of KnpGaufretteBundle, 0.9 is allowed in the version constraint. https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/55c003ff4ec4677d4605580a62bf64634e9e6b61/src/Kunstmaan/MediaBundle/composer.json#L21

If you can't install that version, you always try to check the reason with `composer why-not knplabs/knp-gaufrette-bundle 0.9`
