### ISSUE TITLE
[LeadGenerationBundle] Wrong routes and missing type parameter

### ISSUE THREAD

**Issue by virtualize** [Kunstmaan/KunstmaanBundlesCMS#3401]
I encountered two fatal errors when using the LeadGenerationBundle with in 7.1 

- the menu entry for Modules > Popups has a wrong URL due to a wrong route name generated by [AbstractAdminListConfigurator::getPathByConvention](https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/f07cc4584d4005f45126e462609bbf3aeb23fd6a/src/Kunstmaan/AdminListBundle/AdminList/Configurator/AbstractAdminListConfigurator.php#L815)
- when submitting a popup or rules form, the type parameter is not correctly fetched from the request, the is a regression introduced in 59dcd2c25772d361a27e65b4133a2ad4814201e6 where all `$request->get('type');` statements were replaced by `$request->query->get('type');`. But this is missing post request handling where params should be fetched from the request.

I prepared a PR with fixed for these.

**Comment by acrobat** [comment]
Fixed in #3403
