### ISSUE TITLE
[AdminBundle] PasswordCheckListener

### ISSUE THREAD

**Issue by dannyvw** [Kunstmaan/KunstmaanBundlesCMS#3462]
Is it needed to call this on all requests? Can we move it to a login success event?

https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/7.x/src/Kunstmaan/AdminBundle/EventListener/PasswordCheckListener.php

**Comment by acrobat** [comment]
On login success can indeed be used but the request event is needed because the user can go to a different url after the login redirect to the password change page, so the password is still not changed.
