### ISSUE TITLE
Move pages in the page tree

### ISSUE THREAD

**Issue by wimvds** [Kunstmaan/KunstmaanBundlesCMS#35]
It would be nice if pages could be moved in the page tree (when it is allowed to move them).

**Comment by krispypen** [comment]
@wimvds this is already possible? Or doesn't it work like it should?

**Comment by IbeVanmeenen** [comment]
@krispypen nope

**Comment by krispypen** [comment]
@wimvds @IbeVanmeenen please check http://demo.bundles.kunstmaan.be/en/admin/nodes/

**Comment by IbeVanmeenen** [comment]
Indeed.
