### ISSUE TITLE
[DashboardBundle] the code from google is not decode

### ISSUE THREAD

**Issue by krijnkok** [Kunstmaan/KunstmaanBundlesCMS#359]
I had a problem where i got a code back from google. In this code there was a "/" normally not used in GET variables.
In the setTokenAction where the code is passed back to google this is not decoded any more. 
It's encoded like %2F because its a GET variable when its passed to google, i get a error and it will not work. 
I made a new client in google with a new client_id where i get a code without "/" and then the bundle works fine.
The fix could be on line 89 in GoogleAnalyticsController.php to add the urldecode function.

**Comment by krispypen** [comment]
@krijnkok can you create a PR for this?
