### ISSUE TITLE
Warming the cache after flush

### ISSUE THREAD

**Issue by hpatoio** [Kunstmaan/KunstmaanBundlesCMS#370]
When I run `kuma:translator:cache --flush` files with translations are removed but is the cache warmed up too or is created when the resources are requested ?

**Comment by denbatte** [comment]
The cache will not be automatically warmed, it will just remove the files in the cache directory.
See:
https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/src/Kunstmaan/TranslatorBundle/Service/Translator/ResourceCacher.php#L71-L85
