### ISSUE TITLE
Implement a standard console event listener

### ISSUE THREAD

**Issue by wimvds** [Kunstmaan/KunstmaanBundlesCMS#38]
It would be nice if we had a standard console event listener in the AdminBundle that can be used to log console command exceptions.

http://symfony.com/doc/current/cookbook/console/logging.html#enabling-automatic-exceptions-logging

It would be nice if it was configurable (ie. add a console_exception_listener_enabled: true/false option to enable/disable it).

**Comment by woutervandamme** [comment]
https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/213
