### ISSUE TITLE
Improve the Google Sitemap generation and robots.txt integration

### ISSUE THREAD

**Issue by roderik** [Kunstmaan/KunstmaanBundlesCMS#4]
* Sitemaps conform to the [recommendations by Google](https://support.google.com/webmasters/answer/183668?hl=en)
* An option to manage the robots.txt settings

**Comment by roderik** [comment]
Make sure the robots.txt is editable in the backend (below settings?)

**Comment by roderik** [comment]
Also add the sitemapindex

**Comment by tarjei** [comment]
Isn't this issue solved?
