### ISSUE TITLE
Media bundle: pdf preview on => error

### ISSUE THREAD

**Issue by kimausloos** [Kunstmaan/KunstmaanBundlesCMS#407]
When pdf preview is enabled, the container can not be built because FileHandler does not implement the MimeTypeGuesserFactoryInterface:

```
  [Symfony\Component\Debug\Exception\ContextErrorException]
  Catchable Fatal Error: Argument 2 passed to Kunstmaan\MediaBundle\Helper\File\FileHandler::__construct() must implement interface Kunstmaan\MediaBundle\Helper\MimeTypeGuesserFactoryInterface, none given, called in /app/cache/dev/appDevDebugProjectContainer.php on line 3728 and defined
```

A test should also be added.

**Comment by wimvds** [comment]
I'm not sure why this even got merged : https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/394#issuecomment-101609212

**Comment by krispypen** [comment]
@arneruy can you write a test for it also?
