### ISSUE TITLE
Search Engine: Extra fields

### ISSUE THREAD

**Issue by thomasverleye** [Kunstmaan/KunstmaanBundlesCMS#411]
I have a problem with the usage of elastica search. In the documentation there's being mentioned that you can add extra fields into the Elastica Node index by listening to the onIndexNode-event. I've tried to manage and listen to this event but apparently you guys have removed this event? Is there a particular reason for that and do you guys have any alternative way to add extra fields to the Elastica node index?

https://github.com/Kunstmaan/KunstmaanNodeSearchBundle/commit/b1024869bc98389ca2379f6e01d49ea2c4029551#diff-550e5703d71973170435fb7e34f293f0L11

**Comment by sandergo90** [comment]
@jockri close
