### ISSUE TITLE
Exporting translation

### ISSUE THREAD

**Issue by hpatoio** [Kunstmaan/KunstmaanBundlesCMS#412]
Hello. I've talked to @denbatte during the phpday about problems extracting strings to translate (for custom validator for instance). As fa as I remember he told me you manually add these strings from PHPstorm. Can I have some more details about this solution If possible ? 

I was also thinking about a console command to manually add string to translation files. Something like

`app/console my:command:add_translation_key key --locale=en --desc="This is a string I couldn't extract so I've added it manually" --domain=my_domain`

What do you think ?

PS: I could have written a mail for this but I think other are interested.

**Comment by denbatte** [comment]
Hi Simone,

Nice to see you are giving our bundles a try. 

- I add a translation key in phpstorm like this.
![add_translation_key_phpstorm](https://cloud.githubusercontent.com/assets/505196/7697460/4e6f8a98-fe08-11e4-883f-10deea80de3e.png)
This way the key and its parents will be created when they do not exist (you could possibly need the symfony2 plugin for this).
- A other way is to manually add the keys in those files.

- When you deploy your site, the translation files will also be deployed.
If you log in to the admin backend and you go to settings -> translations. You will get a list of all translations you created in your messages, ....yml files. (if not? press import button, your translations will be imported in database when pressed).
- If needed you can even add translations directly to database in the backend by pressing the add button.

Hope this answers your question
If you have any more, do not hesitate to ask them.

**Comment by hpatoio** [comment]
Thanks @denbatte going to test
