### ISSUE TITLE
[NodeBundle] Refactor isStructureNode() and isHiddenFromNodeTree() methods

### ISSUE THREAD

**Issue by jockri** [Kunstmaan/KunstmaanBundlesCMS#426]
Check that it is better to use reflection to check this.
Also cache the classes that were already checked.

https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/src/Kunstmaan/NodeBundle/Helper/Menu/PageMenuAdaptor.php#L136
https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/src/Kunstmaan/NodeBundle/Helper/Menu/PageMenuAdaptor.php#L155
https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/src/Kunstmaan/NodeBundle/Controller/WidgetsController.php#L112

**Comment by wimvds** [comment]
I don't think using a ReflectionClass would be beneficial, it's a lot slower then creating instances of objects and using these to test if a class is an instance of an interface : cfr. https://gist.github.com/wimvds/a6708a67b362ef4a4121

**Comment by kimausloos** [comment]
It's a bit slower but using a reflectionclass won't give you exceptions when someone decides to add a non optional constructor argument. Of course we should cache this too.
