### ISSUE TITLE
[SeoBundle] Og Image not able to delete it.

### ISSUE THREAD

**Issue by bureaublauwgeel** [Kunstmaan/KunstmaanBundlesCMS#428]
CMS: v3.1

To repoduce:

-Add image to OG Image.
-Save page
-Delete OG Image
-Save page

Get greeted by exception:

Catchable Fatal Error: Argument 1 passed to Kunstmaan\SeoBundle\Entity\Seo::setOgImage() must be an instance of Kunstmaan\MediaBundle\Entity\Media, null given

**Comment by sandergo90** [comment]
@jockri close
