### ISSUE TITLE
[AdminBundle] Rich editor issue pageparts

### ISSUE THREAD

**Issue by bureaublauwgeel** [Kunstmaan/KunstmaanBundlesCMS#430]
This fix gives a issue when there is a page with a page part with subentities and a other page part with de rich-editor.

Example:
- PP with subentities
- PP with editor

When you add a subentities the ckeditor throws a exception on the form field of the page part of the editor.

Example:
The editor instance "form_pagepartadmin_7_content" is already attached to the provided element.

**Comment by sandergo90** [comment]
@jockri close
