### ISSUE TITLE
Batch pagepart add

### ISSUE THREAD

**Issue by konstantinsp** [Kunstmaan/KunstmaanBundlesCMS#433]
Hello,
im generating page parts programmatically like in the site fixtures...
and i noticed it is quite slow when im adding multiple page parts.
i looked at your code and i noticed that you have a lot of db requests in the process of saving them
can it be optimized for adding multiple page parts at once to page?

and also i noticed that creating page translations is also quite slow i guess for the same reason..

**Comment by jockri** [comment]
Feel free to send a pull request, closing this for now.
