### ISSUE TITLE
[Insight] Usage of a function in loops should be avoided - in src/…/Command/CreateUserCommand.php, line 200

### ISSUE THREAD

**Issue by denbatte** [Kunstmaan/KunstmaanBundlesCMS#435]
**[in src/Kunstmaan/AdminBundle/Command/CreateUserCommand.php, line 200](https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/a58d4c9f5e597fed221fdb5d5bf526adea1a8916/src/Kunstmaan/AdminBundle/Command/CreateUserCommand.php#L200)**

> This loop uses a function. To avoid the overhead of executing the function n times, you should precalculate it before the loop.

```php

        if (!$input->getOption('group')) {

        $output->writeln('<info>available groups:</info>');

        for($i = 0 ; $i < count($groups); $i++){
        $output->writeln('[<info>' . $i . '</info>] ' . $groups[$i]);
        }

            $group = $this->getHelper('dialog')->askAndValidate(
                $output,
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/313ff798-9e67-4c0c-9a04-ee4d5cdde1e6/analyses/541)_

**Comment by krispypen** [comment]
@woutervandamme so don't use functions in a for loop if it's not needed
