### ISSUE TITLE
Generating an entity with adminlist set to yes gives an exception

### ISSUE THREAD

**Issue by kimausloos** [Kunstmaan/KunstmaanBundlesCMS#443]
I used ```app/console  kuma:generate:entity``` to generate the entity and said yes to generate an adminlist. When executing ```kuma:generate:adminlist``` after this error, the adminlist is generated without error.
```
Generating the entity code: OK


  Welcome to the Kunstmaan admin list generator





  [ReflectionException]
  Class Kunstmaan\KunstmaanTestBundle\Entity\NewsletterSubscription does not exist



kuma:generate:entity [--entity="..."] [--fields="..."] [--prefix[="..."]] [--with-repository] [--with-adminlist]
```

**Comment by denbatte** [comment]
Error is being triggered here:
https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/src/Kunstmaan/GeneratorBundle/Command/GenerateAdminListCommand.php#L60
