### ISSUE TITLE
Updating 3.1 -> 3.1.1 fatal error

### ISSUE THREAD

**Issue by thomasverleye** [Kunstmaan/KunstmaanBundlesCMS#449]
Hello

When I was trying to update the KumaBundles with composer update, It gave me the following fatal error:

 Catchable Fatal Error: Argument 2 passed to Kunstmaan\MediaBundle\Helper\File\FileHandler::__construct() must implement interface Kunstmaan\MediaBundle\Helper\MimeTypeGuesserFactoryInterface, none given, called in /Users/thomasverleye/Sites/superrbtemplate/app/cache/dev/appDevDebugProjectContainer.php on line 3716 and defined

any suggestions what's this all about?

**Comment by iknowfoobar** [comment]
I get this on sites I try to take from 3.1 to 3.1.1 too.

**Comment by tentwofour** [comment]
Just had this as well, solved with

```bash
rm -Rf app/cache/*
app/console cache:warmup
```

Also had to lock some dependencies, due to circular reference exceptions (related to security.context in UserProcessor) - this may have been unique to my project though, but the exception seemed to disappear when I downgraded from the Symfony 2.7 branch. This is what I ended up with, hope it helps.

```javascript
"symfony/symfony": "2.6.7",
    "doctrine/orm": "2.5.0",
    "doctrine/doctrine-bundle": "1.4.0",
    "twig/extensions": "1.2.0",
    "symfony/assetic-bundle": "2.6.1",
    "symfony/swiftmailer-bundle": "2.3.8",
    "symfony/monolog-bundle": "2.6.1",
    "sensio/distribution-bundle": "3.0.22",
    "sensio/framework-extra-bundle": "3.0.7",
    "incenteev/composer-parameter-handler": "2.1.0",
    "kunstmaan/bundles-cms": "3.1.1",
    "raven/raven": "0.11.0",
    "liip/cache-control-bundle": "1.0.7",
    "ekino/newrelic-bundle": "1.2.3",
    "jms/security-extra-bundle": "1.5.1",
    "doctrine/doctrine-migrations-bundle": "2.1.*@dev",
    "doctrine/migrations": "~1.0@dev",
    "stof/doctrine-extensions-bundle": "1.1.0",
    "friendsofsymfony/user-bundle": "2.0.*@dev",
    "friendsofsymfony/http-cache-bundle": "1.2.1",
```

**Comment by denbatte** [comment]
We noticed indeed some issue's with Symfony 2.7 so we locked the Symfony version for now.
"symfony/symfony": "~2.3,<2.7"
