### ISSUE TITLE
[MediaBundle] Image extension case sensitivity

### ISSUE THREAD

**Issue by kimausloos** [Kunstmaan/KunstmaanBundlesCMS#455]
When you add an image with upper case extension (ie. file.JPG), the image fails to display. Rename the same image to a lowercase extension (file.jpg) and it works.

**Comment by krispypen** [comment]
@kimausloos Is the filesystem where you have the problem case sensitive?

**Comment by kimausloos** [comment]
Of course :)

**Comment by krispypen** [comment]
The default extensions are jpg, jpeg, png, ... and liip imaginebundle only checks with "in_array"... so you can configure the liip_image.formats in your config_base.yml  or we should change the filename to lowercase when saving in our storage here https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/079e68859a2731504c6887c2a42095d137b7aa02/src/Kunstmaan/MediaBundle/Helper/File/FileHandler.php#L224. I think the latest one.

**Comment by sandergo90** [comment]
@jockri close
