### ISSUE TITLE
[TranslatorBundle] Editing impossible

### ISSUE THREAD

**Issue by kimausloos** [Kunstmaan/KunstmaanBundlesCMS#466]
When you have a lot of languages and some long keys in your page the edit popup falls of the screen.
![screen shot 2015-06-02 at 17 05 42](https://cloud.githubusercontent.com/assets/493233/7939164/d3b1b1f8-0949-11e5-96a0-5fe5dff38163.png)

There are 2 more locales, but they aren't shown at all.

**Comment by wimvds** [comment]
You can filter the languages that are visible on the translations (not ideal maybe, but it's a workaround for the time being).

**Comment by FVKVN** [comment]
Isn't this fixed with the table-responsive wrapper which was added a while ago?

**Comment by jockri** [comment]
Yes looks like this is solved.
