### ISSUE TITLE
Save to Draft > Publish flow is broken

### ISSUE THREAD

**Issue by ChristerGustavsson** [Kunstmaan/KunstmaanBundlesCMS#469]
Saving a page as draft and then trying to publish it the the public version does not work anymore. When the publish modal is shown the page refreshes. If you're quick enough you can still publish your drafts if you manage to press the button. 

I could reproduce this on the [demosite](http://demo.bundles.kunstmaan.be/en/admin) so I know this is not something I have done in my local environment.

**Comment by woutervandamme** [comment]
this has been fixed in 3.1.2 

https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/409

**Comment by krispypen** [comment]
We release 3.1.2 yesterday but the demosite is not updated yet.

**Comment by ChristerGustavsson** [comment]
Okay, my bad. I tried to search for an issue for this but couldn't find any. Guess I forgot to search for pull requests. Thanks for your quick reply.
