### ISSUE TITLE
Database tables not found at the poroject startup

### ISSUE THREAD

**Issue by ltarasiewicz** [Kunstmaan/KunstmaanBundlesCMS#498]
Hello,

When going to the `app_dev.php ` for the first time, the system errors out with: 

1/3
> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'kunt.kuma_translation' doesn't exist
2/3
> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'kunt.kuma_translation' doesn't exist
3/3
> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'kunt.kuma_translation' doesn't exist

The databse for the system was created befoe installing BundlesCMS, and proper credential were given at the intial configuration. As far as I remember Symfony Standard Edition could create a database for you with `doctrine:database:create`. Here the db was created beforehand.

Any idea what the cause might be ?

**Comment by denbatte** [comment]
Hi,

You have to use doctrine:schema:create, this will create the tables in the database.
After that step you have to fill those tables with the command doctrine:fixtures:load

see documentation:
![screen shot 2015-06-18 at 14 10 32](https://cloud.githubusercontent.com/assets/505196/8230813/f2a82534-15c3-11e5-8356-ecb1d74b259c.png)


Hope this helps

**Comment by ltarasiewicz** [comment]
Thanks. I've missed that part.
