### ISSUE TITLE
Getting the PuPHPet Vagrant box (installation instruction)

### ISSUE THREAD

**Issue by ltarasiewicz** [Kunstmaan/KunstmaanBundlesCMS#502]
Hi,

I'm not sure if this is the right place to ask, but I think it's the only to get in touch with Kunstmaan CMS community.

I've followed the instruction for setting up a development environment available at http://bundles.kunstmaan.be/documentation/installation/development-environment .

Executing `vagrant up` provisiones the virtual machine, but the process errors out at the end with:

Has anybody experienced the same problem? How have you overcome it?

> ==> default: Notice: /Stage[main]/Main/Exec[Create apache webroot]/returns: chown: changing ownership of ‘/var/www’: Operation not permitted
==> default: Error: mkdir -p /var/www &&                 chown root:www-data /var/www &&                 chmod 775 /var/www &&                 touch /.puphpet-stuff/apache-webroot-created returned 1 instead of one of [0]
==> default: Error: /Stage[main]/Main/Exec[Create apache webroot]/returns: change from notrun to 0 failed: mkdir -p /var/www &&                 chown root:www-data /var/www &&                 chmod 775 /var/www &&                 touch /.puphpet-stuff/apache-webroot-created returned 1 instead of one of [0]
==> default: Notice: /Stage[main]/Main/File[/var/run/apache2/ssl_mutex]/ensure: created
==> default: Info: /Stage[main]/Main/File[/var/run/apache2/ssl_mutex]: Scheduling refresh of Service[httpd]
==> default: Notice: /Stage[main]/Main/Exec[exec mkdir -p /var/www/html @ key default_vhost_80]: Dependency Exec[Create apache webroot] has failures: true
==> default: Warning: /Stage[main]/Main/Exec[exec mkdir -p /var/www/html @ key default_vhost_80]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Main/Exec[exec mkdir -p /var/www/html @ key default_vhost_443]: Dependency Exec[Create apache webroot] has failures: true
==> default: Warning: /Stage[main]/Main/Exec[exec mkdir -p /var/www/html @ key default_vhost_443]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Main/Exec[exec mkdir -p /var/www/myprojectname/web @ key d2wndcy7blwm]: Dependency Exec[Create apache webroot] has failures: true
==> default: Warning: /Stage[main]/Main/Exec[exec mkdir -p /var/www/myprojectname/web @ key d2wndcy7blwm]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Apache::Service/Service[httpd]: Triggered 'refresh' from 1 events
==> default: Notice: /Stage[main]/Main/File[/var/www/html/index.html]: Dependency Exec[Create apache webroot] has failures: true
==> default: Warning: /Stage[main]/Main/File[/var/www/html/index.html]: Skipping because of failed dependencies
==> default: Notice: Finished catalog run in 101.45 seconds
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by roderik** [comment]
Seems to be a bug in puphpet: https://github.com/puphpet/puphpet/issues/1540

**Comment by ltarasiewicz** [comment]
I guess then this topic does not belong here.

**Comment by roderik** [comment]
wel not entirely, it seems it was fixed in puphpet and we need to update the generated puppet scripts https://github.com/puphpet/puphpet/commit/5dc110e61f88a7d79a72e6f40d246fab36b98746

**Comment by ltarasiewicz** [comment]
So I guses I'll leave the issue open for now :)

**Comment by jezemery** [comment]
Hey guys has there been any progress here? Getting similar errors!

**Comment by roderik** [comment]
They changed everything in puphet, i have to start fresh. It's on my list of todo's :)

**Comment by jockri** [comment]
puphet is upgraded in the meanwhile
