### ISSUE TITLE
Unrecognized option "admin_password" under "kunstmaan_admin"

### ISSUE THREAD

**Issue by iknowfoobar** [Kunstmaan/KunstmaanBundlesCMS#503]
I am receiving this error after a composer update on all KunstmaanBundles websites we have.

`[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
  Unrecognized option "admin_password" under "kunstmaan_admin" `

Commenting out the `admin_password` line in `config.yml` fixes it.

I have also just tried a fresh install and the same problem is happening.

**Comment by roderik** [comment]
If you install with -s dev, you get the master of the standard edition with the stable of the cms bundle. You need master of the cms bundle to have this option

**Comment by iknowfoobar** [comment]
Ahh, ok thanks

**Comment by krispypen** [comment]
The error is still their with the current master branch, see https://travis-ci.org/Kunstmaan/KunstmaanBundlesStandardEdition/jobs/67257721

**Comment by jockri** [comment]
Fixed
