### ISSUE TITLE
[NodeSearchBundle] Not adding any content from page parts to index documents

### ISSUE THREAD

**Issue by iknowfoobar** [Kunstmaan/KunstmaanBundlesCMS#521]
I have noticed of the last few sites we have built that the site search function doesn't seem to work as described in the documentation. When searching for key words very few results are being returned. I have just been investigating further and it appears that all documents in my index don't have any content with them so the search is only searching the document title.

Your documentation says that if the object implements the `HasPagePartsInterface` then the page parts will be indexed as the content for that document.

Following your code I can see that `NodePagesConfiguration::addPageContent()` determines if the entity uses the `HasPagePartsInterface` and then calls `NodePagesConfiguration::renderDefaultSearchView()` This method then in turn finds all the page parts for the entity. However it never finds any page parts for any of my entities/nodes, hence no index documents ever have any content in them.

This is because the context passed to `IndexablePagePartsService::getIndexablePageParts()` is hard coded as `main` and due to the way we have been using the CMS we have been creating regions with different names so that we can control which page parts are available on each page type more easily. It should probably be noted in the documentation that only page parts in a region called 'main' will be indexed.

Is is possible to change the way this works so that we can either define the context or that the search indexing uses all possible regions to generate content? If I manually change the hardcoded context then the content of the region is added correctly to the search index document.

You could potentially add a method to the Page entity that allows overriding of the main region allowing us to define which context should be used? e.g.: in my custom `NewsPage` entity

`protected function getSearchIndexContext() {
    return 'newsdetail';
}`

This could easily be defaulted to `main` using class inheritance.

**Comment by iknowfoobar** [comment]
Has anyone had a chance to think about this? It is causing us a lot of problems as it makes the search results very inaccurate when you have several content areas on a page.

**Comment by mlebkowski** [comment]
You can do it by yourself. Create your own implementation of `IndexablePagePartsService`, for example:

```php
<?php

use Kunstmaan\NodeSearchBundle\Helper\IndexablePagePartsService;
use Kunstmaan\PagePartBundle\Helper\HasPagePartsInterface;

interface HasSearchContext { public function getSearchIndexContext(); }

class CustomIndexablePagePartsService extends IndexablePagePartsService {
    public function getIndexablePageParts(HasPagePartsInterface $page) {
         $context = $page instanceof HasSearchContext ? $page->getSearchIndexContext(): "main"
         return parent::getIndexablePageParts($page, $context);
    }
}
```

And then replace it in the container using a compiler pass:

```php
<?php

use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;

class CompilerPass implements CompilerPassInterface {
    public function process(ContainerBuilder $container) {
        $container->getDefinition('kunstmaan_node_search.service.indexable_pageparts')
            ->setClass(CustomIndexablePagePartsService::class);
    }
}
```

**Comment by iknowfoobar** [comment]
Thanks, that was really helpful and has solved our problems! I didn't think of using that.
