### ISSUE TITLE
How do I define default pageparts for a pagetype

### ISSUE THREAD

**Issue by tarjei** [Kunstmaan/KunstmaanBundlesCMS#527]
Hi, I have a defined pagetype, and now I want to have a set of pagetypes that are added to the page when the page is created. How do I do that?

**Comment by denbatte** [comment]
Hi,

When you create a new page, the system will fire a event.
Use `app/console debug:event-dispatcher`

You can create a event listener that listens for the right event and checks that the page added is your desired type.
There you will be able to add pageparts.

**Comment by tarjei** [comment]
Great! Thanks
