### ISSUE TITLE
How can I perform a query in a PagePart

### ISSUE THREAD

**Issue by tarjei** [Kunstmaan/KunstmaanBundlesCMS#530]
Hi, I want to do a query in a PagePart. I there a way I can have a controller method/class for adding data to the PagePart view?

**Comment by denbatte** [comment]
Best way to do this is by using a twig extension.

**Comment by tarjei** [comment]
I decided I would use an extra controller
9. jul. 2015 11.39 skrev "Bart" <notifications@github.com>:
