### ISSUE TITLE
[AdminListBundle] fix margin for extra list item actions

### ISSUE THREAD

**Issue by jockri** [Kunstmaan/KunstmaanBundlesCMS#533]
![screenshot 2015-07-08 15 13 37](https://cloud.githubusercontent.com/assets/517574/8570945/1e939e56-2584-11e5-9392-e7d3c9795c56.png)

**Comment by diskwriter** [comment]
@jockri Was this resolved ?

**Comment by jockri** [comment]
jep, by removing the labels
