### ISSUE TITLE
[Admin] Media chooser popup - cant choose 'media' root folder

### ISSUE THREAD

**Issue by kimausloos** [Kunstmaan/KunstmaanBundlesCMS#545]
When you open the media chooser popup you arrive in the media root folder. You can upload a file there.
Then, when you choose the 'images' folder in the popup, you can never go back to the media root folder where you uploaded your file.

**Comment by sandergo90** [comment]
I don't think this is still an issue. Can't reproduce this kind of behaviour.

**Comment by jockri** [comment]
It is still an issue, you cant select images from the root dir
