### ISSUE TITLE
Nested form max has no effect

### ISSUE THREAD

**Issue by alexborton** [Kunstmaan/KunstmaanBundlesCMS#547]
It would seem that the nested_form_max does not stop the admin from exceeding the value. 

I have a nested form for sub-entities and a value of 'nested_form_max' => 3 but i am still allowed to exceed this and save it. 

Is there something else i could be missing?

The complete form builder looks like this for the parent;

    $builder->add('imageCTAs', 'collection', array(
            'label' => 'Image call to actions',
            'type' => new ImageCTAAdminType(),
            'allow_add' => true,
            'allow_delete' => true,
            'by_reference' => false,
            'cascade_validation' => true,
            'attr' => array(
                'nested_form' => true,
                'nested_form_min' => 2,
                'nested_form_max' => 3,
                'nested_sortable' => true,
                'nested_sortable_field' => 'displayOrder',
            )
        ));

Worth noting that nested_form_min does work as expected. 

Thanks

**Comment by mlebkowski** [comment]
I experienced it as well and found a bug in `nested-forms.js`. It should be fixed on master in bd4281a3cb6a59e3189cddccb25d0312d24a806e. Could someone confirm?

@alexborton, if you can’t wait for the next release, you could extend this asset (google symfony docs on the topic, but basically you need to copy the file to `app/Resources/…`) and [make this fix yourself](https://github.com/Kunstmaan/KunstmaanBundlesCMS/commit/bd4281a3cb6a59e3189cddccb25d0312d24a806e#diff-6e7d31ed82d0cefb5a4fd05a981e8797L89)

**Comment by alexborton** [comment]
OK, great - thanks @mlebkowski and thanks for the quick reply. 

I will look into a local fix, but if this could be amended on the master, that would be great as i think it's a pretty vital part of the sub-entities setup! Thanks

**Comment by jockri** [comment]
Solved in the new release.
