### ISSUE TITLE
dublicate "delete" button on the second level of nested forms

### ISSUE THREAD

**Issue by evgemar** [Kunstmaan/KunstmaanBundlesCMS#561]
![screen](https://cloud.githubusercontent.com/assets/296414/8730534/05e97084-2bfa-11e5-9238-0ca3e87e7481.PNG)

**Comment by mlebkowski** [comment]
same issue as in #560

**Comment by roderik** [comment]
We just tagged 3.2.1, is it solved for you now?

**Comment by evgemar** [comment]
I've updated to the 3.2.1, but it's not fixed yet :(

**Comment by evgemar** [comment]
fixed. Thanks
