### ISSUE TITLE
TagManager::saveTagging should be compatible with DoctrineExtensions\Taggable\TagManager::saveTagging

### ISSUE THREAD

**Issue by tarjei** [Kunstmaan/KunstmaanBundlesCMS#566]
Hi, after updating to 3.2 I get this error:

 [Symfony\Component\Debug\Exception\ContextErrorException]                                                                                                                                 
  Runtime Notice: Declaration of Kunstmaan\TaggingBundle\Entity\TagManager::saveTagging() should be compatible with DoctrineExtensions\Taggable\TagManager::saveTagging(DoctrineExtensions  
  \Taggable\Taggable $resource)

**Comment by tarjei** [comment]
I see this has been fixed in master btw.

**Comment by krispypen** [comment]
@tarjei maybe it was not on 3.2.1 then? can you check your composer.lock file?

**Comment by tarjei** [comment]
I checked. The fix is not in 3.2.1.

A simple fix is to change `loadTagging(Taggable $resource)` to `loadTagging(BaseTaggable $resource)` and `saveTagging(Taggable $resource)` to `saveTagging(BaseTaggable $resource)`.

The change in master is bigger.
