### ISSUE TITLE
The issue with empty slug for the homepage

### ISSUE THREAD

**Issue by evgemar** [Kunstmaan/KunstmaanBundlesCMS#568]
For the homepage when slug is NULL slugifier change it to 'n-a'.

P.S.
Something like this issue has been fixed before v3.2, but I can't find it in the issue list.

**Comment by krispypen** [comment]
This is fixed in #567

**Comment by krispypen** [comment]
https://github.com/Kunstmaan/KunstmaanBundlesCMS/releases/tag/3.2.1.1

**Comment by evgemar** [comment]
fixed. Thanks
