### ISSUE TITLE
Fix admin tests

### ISSUE THREAD

**Issue by roderik** [Kunstmaan/KunstmaanBundlesCMS#575]
I've gotten the travis builds of the standard edition back up and running. But the admin tests have not been updated for the new backend code. This should be fixed asap.

**Comment by krispypen** [comment]
#603 partly fixes the tests,
The other problem is the generated password of the admin user which is not used in the tests... A workarround is generating the admintests after the doctrine fixtures has run, but don't know if that's a good idea, still looking for a better solution.

**Comment by jockri** [comment]
All tests are green!
