### ISSUE TITLE
[AdminBundle] Error when using media type in PagePart collection

### ISSUE THREAD

**Issue by waaghals** [Kunstmaan/KunstmaanBundlesCMS#579]
My pagepart has multiple images which should be managed when editing the pagepart.
But an "Array to string conversion" error happens in the `/Form/fields.html.twig` file.

In #540,  when the form is a composite type it uses `obj.vars.value` because it thinks it is a scalar type.
But the MediaType is not composite but the value is an array containing both a 'id' and 'ent' field.

I've created a workaround by checking if the value has an id field. 

```twig
# /Forms/fields.html.twig (L: 157-159)
<div class="js-nested-form__item nested-form__item 
     {% if sortable %}js-sortable-item sortable-item{% endif %}"
    data-delete-key="{{ form.vars.id|replace({'form_': 'delete_'}) }}_{% if obj.vars.value.id is defined  %}{{ obj.vars.value.id }}{% else %}{{ obj.vars.value }}{% endif %}"
    {% if sortable %}data-sortkey="{{ obj.children[sortableField].vars.id }}"{% endif %}>
```

But I do not know if this is a save solution, or else I would have created a pull request.

PS: Does the collection actually support the media type? I'm having difficulties when removing a complete row it tries to remove the Media entity as well, but this is not supposed to happen.
```php
//My form field:
$builder->add('images', 'collection', array(
    'type' => 'media',
    'allow_add' => true,
    'allow_delete' => true,
    'by_reference' => false,
    'cascade_validation' => true,
    'options' => array(
        'mediatype' => 'image',
        'required' => true,
    ),
    'attr' => array(
        'nested_form' => true,
        'nested_form_min' => 1,
        'nested_form_max' => 4,
    ),
));
```

**Comment by jockri** [comment]
I think it is easier to use this:
https://bundles.kunstmaan.be/news/using-sub-entities-in-pageparts
