### ISSUE TITLE
`createModal.html.twig` template is missing

### ISSUE THREAD

**Issue by mlebkowski** [Kunstmaan/KunstmaanBundlesCMS#580]
![Template missing](https://www.evernote.com/l/AAR11iM1ACdGs5OyhLuNL4HD_HB09WIifP0B/image.png)

`\Kunstmaan\MediaBundle\Controller\MediaController::createModalAction` throws an exception because the `createModal.html.twig` template is missing

**Comment by yoshz** [comment]
Had this exception a few times, but couldn't reproduce it quickly.
Seems like to occur when you try to add a new file from an existing modal.

**Comment by jeroenjans** [comment]
I was able to reproduce the issue by uploading a file that was bigger than the `upload_max_filesize` directive in php.ini (which in my case was 2M)

**Comment by aistis-** [comment]
I also run into the same issue.

**Comment by jockri** [comment]
I think this was solved in #580. If not please reopen the issue.
