### ISSUE TITLE
Collection form type in page admin form

### ISSUE THREAD

**Issue by ro0NL** [Kunstmaan/KunstmaanBundlesCMS#584]
Hi,

I have a custom page type with a collection field (doctrine type array that is), i.e. the collection is stored serialized.

When adding a collection form for the corresponding field things get weird. I use the following code for now;
```php
// class SomePageAdminType extends PageAdminType
$builder->add('fieldname', 'collection', array(
    'type' => 'text',
    'options' => array(
        'label' => false,
        'required' => true,
        'constraints' => array(new NotBlank()),
    ),
    'allow_add' => true,
    'allow_delete' => true,
    'cascade_validation' => true,
));
```

This basicly works, however;
-  the add & delete buttons are not shown
![collection form symfony](http://i.snag.gy/dRkmf.jpg)
- ...? (populating, saving, violations seems all OK)

Then I add this option;
```php
'attr' => array(
    'nested_form' => true,
),
```

Now i got the nice add button and a trashcan per item;
- What just happened?
- Can we make allow_add/delete work out of the box?
- Populating exsting records shows collection rows, however the inner input is not there, ie i cant modify existing data
![collection form kunstmaan](http://i.snag.gy/rSJaT.jpg)
- Violations are messed up. When i add a 3rd row and press save my first 2 rows are gone, the new row is again missing it's inner input and has no violation message cascaded.
- Saving seems OK

I'd like to drop the nested_form option here (i dont understand it.. as collection forms should just work on each level). However it seems all client-side logic is triggered by this option... (?)

Hope you guys can have a look a this.

**Comment by mlebkowski** [comment]
@ro0NL, there’s a very simple fix for the missing inputs — it’s in the referenced PR (#629). You can make this fix by yourself by copying the `fields.html.twig` to `app/Resources/KunstmaanAdminBundle/views/Forms/` without waiting for the next release

**Comment by ro0NL** [comment]
@mlebkowski thanks for your reply.. I already had a workaround in our fork but I wasnt sure it was the 'right' fix to create a pull request for.

Looking at PR #629 you did somewhat the same :+1: 

https://github.com/insiders/KunstmaanBundlesCMS/commit/e80939398d8fd934802154923651b1f4ed4b7867
