### ISSUE TITLE
How do I override the WYSIWYG config?

### ISSUE THREAD

**Issue by tarjei** [Kunstmaan/KunstmaanBundlesCMS#593]
Hi, I want to tunde the WYSIWYG configuration for the admin. How do I do that?

**Comment by denbatte** [comment]
@diskwriter made a pull request for it in the past. See #375

**Comment by tarjei** [comment]
More complete solution:
I copied  _ckeditor_configs.html.twig to
`app/Resources/KunstmaanAdminBundle/views/Default/_ckeditor_configs.html.twig` 
and modified it as I wanted.

Then I added modified the wysiwyg field definition in the adminType to:
```php
$builder->add('body', 'wysiwyg', array('attr' => ['data-editor-mode' => 'full']));
```

Which worked :)

**Comment by tarjei** [comment]
So, thanks :)
