### ISSUE TITLE
[frontend] Missing html5shiv.min.js asset

### ISSUE THREAD

**Issue by ro0NL** [Kunstmaan/KunstmaanBundlesCMS#595]
Hi,

There's an hardcoded asset file in the generated `_js_header.html.twig`, ie;
https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Layout/_js_header.html.twig

The asset is configured in the groundcontrol settings but is ignored by gulp, ie;
https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/gulp/.groundcontrolrc#L50

`config.js.other` is unused in gulp;
https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/gulp/gulpfile.js

How do we control assets that needs to be loaded in the header?

**Comment by sulazix** [comment]
Same problem for me .... How can we properly manage JavaScript header's assets ?

**Comment by dbeerten** [comment]
I am working on a fix where you can configure the JavaScript header's assets  in the .groundcontrolrc, with the same functionality as the _js_footer.html.twig.
