### ISSUE TITLE
Improve cache headers

### ISSUE THREAD

**Issue by JoakimLofgren** [Kunstmaan/KunstmaanBundlesCMS#597]
I've been experimenting with trying to improve the caching.

My idea is to set the Last-Modified header by using NodeVersion::getUpdated().
I use nginx with compression so the etags are removed sadly.

Using a SlugActionInterface this becomes a bit tedious as I need a Response object to do that and I don't want to reproduce the template rendering in my slug action.

Seems like there are some pretty [nice annotations](http://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/annotations/cache.html#http-validation-strategies) for this, however I only get the request so I doubt I can use them in a nice manner.

What are your thoughts?

**Comment by kimausloos** [comment]
While it won't allow you to use annotations, you can just create an event listener on [kernel.response](http://symfony.com/doc/current/components/http_kernel/introduction.html#component-http-kernel-kernel-response).

This event is used a lot for this kind of things as you already have a response so you can modify headers and you should also have the request object. That request typically contains ```_nodeTranslation``` in the attributes so you can use the ```getPublicNodeVersion()``` method to fetch the NodeVersion.

**Comment by JoakimLofgren** [comment]
Ah, right, I didn't think about that event. Thanks for the tip.

Sadly the 304 Not Modified response would still need to have the response
fully rendered which is one thing I wanted to avoid.

Maybe I can run some code after the RenderContextListener because that is the last step before the HTML is actually rendered right?

**Comment by jockri** [comment]
Cleaning up old issues
