### ISSUE TITLE
Inject PagePart into controller

### ISSUE THREAD

**Issue by aistis-** [Kunstmaan/KunstmaanBundlesCMS#598]
Hello, I have a situation where I have simple controller which returns a `Response` like

```
return $this->render(
            ':Website/Houses:list.html.twig',
            [
                'oldHouses' => $houseRepository->findActive(),
                'newHouses' => $houseRepository->findExpired(),
            ]
        );
```

The view extends a layout like
```
{% extends 'YoloWebsiteBundle:Layout:layout.html.twig' %}
```

The thing is, that the layout hold header with menu logic (default generated by Kunstmaan generator) and footer which is our hardcoded pagepart name 'FooterPagePart'.
Regular `Page` works as expected, but how to force include `PagePart` in regular controllers?

Any other workflow is worth to be mentioned!

**Comment by denbatte** [comment]
There is a way to attach pageparts but it's not that easy.

A far more easy way is to create a new pagetype. `app/console kuma:generate:page` 
That way you can attach a controller to that pagetype using the controller as a service method to return the houses you need. 
See: https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/UPGRADE-3.1.md#deprecated-the-service-method-in-pages-in-favour-of-controller-methods

We will try to get some documentation about the controller methods online soon.

**Comment by aistis-** [comment]
The problem is, that there are a lot of controllers which has to have some `PageParts` in their rendered templates. It would be quite messy to have a `Page` for every `Controller` :/

**Comment by denbatte** [comment]
One way to get to pageparts of a page could be to give that page an internal name.

That way you could write an SQL query in your controllers to get to that page. 
The `kuma_nodes` table has a column called internal name. 
Join the `kuma_page_parts_refs` table to link the right pageparts to the right page.

**Comment by iBenito** [comment]
@denbatte: I am trying to follow the documentation in the [link],(https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/UPGRADE-3.1.md#deprecated-the-service-method-in-pages-in-favour-of-controller-methods) however "Symfony2 expects a Response object to be returned from a controller action." Is there a workaround for this, or am I missing something? Thanks for your help.

**Comment by jockri** [comment]
Cleaning op old issues
