### ISSUE TITLE
[MenuBundle] Page marked as Offline if not in main navigation.

### ISSUE THREAD

**Issue by iknowfoobar** [Kunstmaan/KunstmaanBundlesCMS#599]
If you mark a page as not to be shown in the nav it marks the page as offline in the MenuBundle admin area and also won't output the link in the menu.

This makes it impossible to create links to pages that are not in the main navigation in MenuBundle navigations, which is what we would find it most useful for.

**Comment by jockri** [comment]
This was fixed with this commit: https://github.com/Kunstmaan/KunstmaanBundlesCMS/commit/0ee1010bf62def67768752a14d497697a78fcbbd
