### ISSUE TITLE
[v3.2.2] twig function get_node_menu is gone

### ISSUE THREAD

**Issue by aistis-** [Kunstmaan/KunstmaanBundlesCMS#604]
After upgrade to **3.2.2** I get an error:
```
The function "get_node_menu" does not exist. Did you mean "get_node_for" in CrowdhouseWebsiteBundle:Layout:layout.html.twig at line 17
```
What was it replaced by?

**Comment by wimvds** [comment]
It's still there... https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/3.2.2/src/Kunstmaan/NodeBundle/Twig/NodeTwigExtension.php#L69

**Comment by aistis-** [comment]
My bad. Composer was resolving Kunstmaan to 3.1.2
