### ISSUE TITLE
Invalid transliterator ID in UtilitiesBundlle/Helper/Slugifier

### ISSUE THREAD

**Issue by mwoynarski** [Kunstmaan/KunstmaanBundlesCMS#610]
I ran into an issue with Kunstmaan 3.2.2 where, when I tried to load the fixtures in a new project, I was having an exception thrown from the [Slugifier](https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/src/Kunstmaan/UtilitiesBundle/Helper/Slugifier.php) helper:

> Error: Call to a member function transliterate() on a non-object

The exact line in question is line 29:

> $transliterator = \Transliterator::create('Any-Latin; Latin-ASCII');

This function is returning null.  When I dump a list of valid IDs with [\Transliterator::listIDs()](http://php.net/manual/en/transliterator.listids.php), "Latin-ASCII" is not returned as a valid ID.  Removing that ID from the argument fixes the problem.

I haven't filed a PR over this, because I don't actually know what the nature of the problem is: Am I missing a standard ID for some reason?  If so, I don't have an unusual system implementation, so there should likely be a fallback in place here as there are surely other developers in the same boat.  Alternatively, should there have been a custom transliterator created with [\Transliterator::createFromRules()](http://php.net/manual/en/transliterator.createfromrules.php)?  If so, the issue is likely somewhere else in the system.

**Comment by jockri** [comment]
Slugifier was update. Please check again.
