### ISSUE TITLE
[MediaBundle] Using placeholders for nodes and media in wysiwyg

### ISSUE THREAD

**Issue by yoshz** [Kunstmaan/KunstmaanBundlesCMS#636]
@roderik I have some thoughts about wysiwyg I would like to discuss with you.

I would like to see a possibility to use placeholders for links to nodes and media which are inserted using the wysiwyg image/link plugins.
The placeholders will be saved in the database using the reference id like `<a href="[node:1]">Home</a>` for nodes and `<img src="[media:1]">` for images.
A twig function or filter can be used to replace the placeholders during rendering.
You can also use placeholders to render the entire image tag or make it possible to embed video/slideshare objects. You can also extend this functionality to apply an image filter.

Second, it would be a good idea to keep track of used nodes and media for each wysiwyig field, so you can lookup usages when you try to delete an image or node.

Do you already have plans or thoughts about implementing above functionalities into Kunstmaan CMS?

**Comment by krispypen** [comment]
:+1:

**Comment by sandergo90** [comment]
@jockri close

Implemented in https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/1225
