### ISSUE TITLE
[AdminBundle] Make ckeditor for a specific field configurable again

### ISSUE THREAD

**Issue by krispypen** [Kunstmaan/KunstmaanBundlesCMS#640]
Now you can only change the toolbar, but it should also be possible to provide a custom configuration (path to a configuration js file)

Now the "customConfigFile" is taken from the global scope: https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/src/Kunstmaan/AdminBundle/Resources/ui/js/_rich-editor.js#L97
the ckEditorConfigs should not be a list of arrays, but a list of objects which can contain an array for the toolbar and a customConfigFile. (both are not required so have to fallback to the default one)

**Comment by krispypen** [comment]
@diskwriter assign

**Comment by evgemar** [comment]
And you can add plugins to the ckeditor to the plugins folder ?
