### ISSUE TITLE
Proper way of passing the current locale to a PagePartAdminType

### ISSUE THREAD

**Issue by Perni1984** [Kunstmaan/KunstmaanBundlesCMS#664]
Dear all,

not sure if this is the correct place to ask - so sorry, when it's not.

I am trying to create a new PagePart called IntroPagePart that should directly link to a specific NodeTranslation in my Site.

In my IntroPagePartAdminType.php im adding the following code to have a nice dropdown menu with the available NodeTranslations of my Site:

```php
$builder->add('nodeTranslation', 'entity', array(
            'class' => 'KunstmaanNodeBundle:NodeTranslation',
            'property' => 'title',
            'query_builder' => function(EntityRepository $er) use ($options) {
                return $er->createQueryBuilder('nt')
                    ->innerJoin('nt.publicNodeVersion', 'nv')
                    ->innerJoin('nt.node', 'n')
                    ->where('n.deleted = 0')
                    ->andWhere('nt.lang = :lang')
                    ->setParameter('lang', $options["locale"])
                    ->andWhere('nt.online = 1')
                    ->orderBy('nt.title', 'ASC');
            },
            'attr' => array(
                'class' => 'js-advanced-select',
                'data-placeholder' => 'Select the page to link to...'
            ),
            'multiple' => false,
            'expanded' => false,
            'required' => true,
            'label' => 'Link page'
        ));
```
Moreover I added a default option for the locale:
```
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(
            array(
                'data_class' => '\Dominator\WebsiteBundle\Entity\PageParts\IntroPagePart',
                'locale' => 'en'
            )
        );
    }
```
But now I am stuck to figure out the best way to pass the current locale in the NodeAdminController to my IntroPagePartAdminType as an option. Could somebody shed some light on how to correctly do that?

**Comment by jverdeyen** [comment]
You could define the form type as a service and inject the requeststack to resolve the current locale. (If you need the current locale)

**Comment by Perni1984** [comment]
thanks for pointing it out to me. I now understood that I don't need to do this - I was trying something weird I learned now ;-)
