### ISSUE TITLE
Have pagepartes be able to call a Controler like method

### ISSUE THREAD

**Issue by tarjei** [Kunstmaan/KunstmaanBundlesCMS#669]
I'm in two minds about this one.

One option that exists today is just to have a pagePart use the render() twig method to render an external controller. 

But...

It would be nice to be able to keep it all in the family, I.e. be able to define a PagePart that can execute logic and use services when building the response. I would suggest something like this:

```php
class MyPagePart implements PagePartRenderInterface  {
   public static function beforeRender(array $view, Container $container) {
       // view will contain the current pagepart as $resource
       $someResult = $container->get('myService')->fetchFoo($view['resource']->getId());
      $view['listOfSomethingRelated'] = $someResult;
      return $view;
   }
}
}
```

Since it is a static method, it can live in the entity without relating to it. The other option would be to define some kind of PagePartViewAnnotator interface and relate them to a given pagepart using DI but that would make it a lot more complex than just allowing for one method directly on the PagePart.

**Comment by jverdeyen** [comment]
Defining logic and injecting the container into an entity doesn't feel like a good idea.

I think there are some other solutions for this problem:

1. Define a twig function and rely on an external service.
2. Define some listener on a pagepart pre-render to inject specific vars into the view

Solution 1. is very easy to implement, 2. would take more time but will be a cleaner solution on the long run.

@jockri @krispypen

**Comment by tarjei** [comment]
I do agree htat having logic in the Entity isn't a good idea, but I wasn't sure where else to put it :) 

Part of the point must be that the whole thing must reside in a logical place to look within the pageparts system.

Hmm, how about linking it in the pageparts configuration files?

```yaml
name: Main
context: main
types:
    - { name: MyPagePart, class: Me\SiteBundle\Entity\PageParts\MyPagePart, command: my.service.id,method: 'myMethod' }

```

**Comment by wimvds** [comment]
There's a third option as well. Just call a seperate controller action to render the contents of the pagepart (passing the id if it contains any data that is needed to render it). That's also very easy to implement and can be done without changing anything to the core functionality (we've done that numerous times already).

**Comment by tarjei** [comment]
Yes, that is what I'm doing today. I just thought it would be nice to have
the option integrated into the PageParts system :P

2015-08-31 14:14 GMT+02:00 Wim Vandersmissen <notifications@github.com>:

> There's a third option as well. Just call a seperate controller action to
> render the contents of the pagepart (passing the id if it contains any data
> that is needed to render it). That's also very easy to implement and can be
> done without changing anything to the core functionality (we've done that
> numerous times already).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Kunstmaan/KunstmaanBundlesCMS/issues/669#issuecomment-136354459>
> .
>



-- 
__________________
Tarjei Huse
Mobil: 920 63 413

**Comment by jverdeyen** [comment]
+1 for Wim' solution. This way you can also easily use `render_esi`.
