### ISSUE TITLE
Migrate to Gulp instead of Assetic

### ISSUE THREAD

**Issue by jverdeyen** [Kunstmaan/KunstmaanBundlesCMS#676]
Is it an option to build all the assets with a custom Gulpfile?
A main project Gulpfile can include all Gulpfile from specific bundles.

I'm currently using this custom Guplfile to pre-build the assets, as they will almost never change during developement.

https://gist.github.com/jverdeyen/ba8471307f2589a3d85b

Overruling templates an adding the static assets it trivial for example in `app/Resources/KunstmaanAdminBundle/views/Default/_css.html.twig`

```
<link rel="stylesheet" href="{{ asset('/css/admin.min.css') }}">
```

Can I open this discussion? Any suggestions? Any remarks?

**Comment by vizo** [comment]
:+1:

**Comment by roderik** [comment]
This is fine, we tried to keep the backend without extra gulp dependency, but in reality you always need it.

**Comment by jverdeyen** [comment]
In order to remove the Assetic bundle, how do you guys see this implemented?
A gulpfile with settings/tasks per bundle and add css/js in `Resources/public`.
Pre-pack these files in the repo can speed up the CMS install process and lower the number of requirements.

**Comment by wesleylancel** [comment]
Bumping this. Any suggestions or remarks from the Kunstmaan team? /cc @jockri @diskwriter

**Comment by diskwriter** [comment]
@wesleylancel I discussed this with @jockri yesterday. It's on our roadmap. I'll keep you posted on the progress!

**Comment by jverdeyen** [comment]
Nice! 🚀

**Comment by Perni1984** [comment]
@diskwriter @jockri:
as this thread is fairly old, but has now been rescheduled to 4.1 - can we help anyhow?

I am using Kunstmaan as underlying base for a project of mine, which I needed to rewrite also on the backend quite a bit. The current assetic architecture makes this kind of hard (especially in conjunction with the bower dependencies in the different bundles) - I eventually need to rewrite the asset management part anyway to stay clean in my architecture. Any input from you how you would like to have that implemented? (e.g. how to manage the bower dependencies, etc.)

**Comment by mlebkowski** [comment]
For an end user, KunstmaanBundles is just a library. They shouldn’t have to compile its assets, the lib should be shipped with them compiled already, in my opinion. BTW, the first thing I do in a new kunstmaan project is `assetic:dump`, commit the generated files to the repository and never do it again unless I update one of the bundles.

**Comment by diskwriter** [comment]
@Perni1984 We are currently working hard on something that will allow the use of Gulp instead of assetic in the bundles. The project was on hold for a while but we've recently restarted developing it and expect it to be ready soon. @mlebkowski is right though: The lib should be shipped with the assets already compiled, this will also be resolved once we're finished and should fix your bower-dependency issue.

**Comment by Perni1984** [comment]
@mlebkowski: as assetic is not bundled with symfony anymore since 3.0 (or was it 2.8?), this will change in the future
@diskwriter: I appreciate that the project has been restarted.

**Comment by Perni1984** [comment]
@diskwriter: is there a public branch that I could have a look into so I understand in which direction your development is heading so I can consider this in my upcoming projects?

**Comment by Perni1984** [comment]
is there any update on this?

**Comment by Devolicious** [comment]
Hi @Perni1984,

We're currently busy with our roadmap. We'll notify you when it's online. But we want to handle this issue in small steps. So first task would be to have compiled assets. Next steps will become clear once the roadmap is online. Help would be much appreciated.

**Comment by Perni1984** [comment]
@Devolicious: looking forward to the roadmap then.
