### ISSUE TITLE
[MultiDomainBundle] Can not generate url to a node on a different host

### ISSUE THREAD

**Issue by yoshz** [Kunstmaan/KunstmaanBundlesCMS#684]
I used the MultiDomainBundle #633 to successfully implement multilingual site with a different domain for each locale.
However I'm not sure how I can easily generate an url to a translation on a different hostname.
This functionality seems te be missing in DomainBasedLocaleRouter.

In pull request #570 I was achieving this by setting the host parameter when you generate url.

@wimvds, @krispypen: Any thoughts about a proper solution? Im about to implement my way by overridding the hostname with the first found hostname by current locale in generateUrl().

**Comment by yoshz** [comment]
Could anyone please comment on this issue? I would like to spend time to solve this issue, but it would be nice if I know the solution i'm thinking about is the right solution.

**Comment by denbatte** [comment]
@jockri

**Comment by yoshz** [comment]
Yesterday I tried to find a proper solution. But it isn't that easy to generate an url inside the router to a different host as you don't have scope on the nodeTranslation and don't know the root node.
It would be easier if it would be allowed to set the node or nodeTranslation as parameter when you generate an url. From the node it is easier to determine the root node and use the internal name to find the first host which matches. But I think it is to much effort for now.

For the current usecase I only need to determine the right host for a translation of the current active node. So I'm thinking about adding a `get_translation_host(locale)` twig function. What do you think?
