### ISSUE TITLE
[MultiDomainBundle] Optimize host override flash message

### ISSUE THREAD

**Issue by yoshz** [Kunstmaan/KunstmaanBundlesCMS#685]
I noticed the flash message when you override the hostname (#633).
The message is a bit weird for non technical users. Shown as warning makes you think you did something wrong. I also think it isn't necessary to display the message on each page. Furthermore the message gets displayed twice on the dashboard when GA is enabled.

@wimvds, @krispypen: I rather see a success message like "You changed to www.domain.tld successfully for this session" once after you switched?

**Comment by roderik** [comment]
We decided to put it on every page because if you "forget" you changed to a different hostname it get's confusing fast.

Both in GUI (a flash message like you describe + some kind of permanent marker, maybe in the dropdown?) and description we welcome suggestions and PR's

**Comment by yoshz** [comment]
More a consistenty thing: what is the difference between changing to a different locale (without the MultiDomainBundle and no flash message is displayed) and changing to a different host (with the MultiDomainBundle and a flash message is displayed).

Don't understand me wrong, the flash message isn't that big thing. But I rather see some optimalizations. I will try to put these things in a pull request later:
* Display flash message in current request. The message isn't displayed directly after you switched.
* Remember if the flash message is triggered in current request. The message is shown twice on the google analytics dashboard for example.
* Change warning to notice and update the message to "Notice: current active host is set to %domain%"

**Comment by yoshz** [comment]
We removed the message for now by removing the event listener using a kernel pass.
