### ISSUE TITLE
[MediaBundle] Multiple file upload doesn't remove temporary files

### ISSUE THREAD

**Issue by yoshz** [Kunstmaan/KunstmaanBundlesCMS#690]
I noticed the folder /tmp/plupload which keeps on growing and eating diskspace. 
Looks like uploaded files are not removed when they are copied to the upload folder.

**Comment by roderik** [comment]
Cleanup should work, code is here and cleanup is enabled by default: https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/7fdd398e88ef6e827422bf8bbe9dc26087b3ce40/src/Kunstmaan/MediaBundle/Controller/MediaController.php#L170

But i see the unlink is silenced at https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/7fdd398e88ef6e827422bf8bbe9dc26087b3ce40/src/Kunstmaan/MediaBundle/Controller/MediaController.php#L187 so maybe there is an hidden issue?

**Comment by yoshz** [comment]
I will try to reproduce it some time later. As it isn't that big issue right now.
