### ISSUE TITLE
Can the admin pageparts emit an event when a new patepart is created?

### ISSUE THREAD

**Issue by tarjei** [Kunstmaan/KunstmaanBundlesCMS#695]
Hi, I've made a pagepart that uses some JS in the admin form to show / hide fields and also to run a select2 selector on one of the fields. My problem now is in having an event to hook up some init code when a new pagepart is created.

Would it be possible for _pagepart_editor.js to emit an event when a new pagepart is created containing some metadata (pagepart class for example) that external scripts could listen to?

**Comment by roderik** [comment]
Seems like a good addition, can you send a PR?

**Comment by tarjei** [comment]
I'll see what I can cook up. Any input on conventions in the code I should be aware of? Do you do something like this somewhere else?
