### ISSUE TITLE
Default Varnish vcl file

### ISSUE THREAD

**Issue by jverdeyen** [Kunstmaan/KunstmaanBundlesCMS#699]
Is there a default vcl file which can be shipped with the CMS?
As query caching isn't enabled by default (on specific queries) it's easier to implement a Varnish cache.

We can put this vcl file in the repo so everyone using the CMS can benefit from it, or adjust/tweak where possible.

**Comment by roderik** [comment]
we use a slightly modified version of this config https://github.com/mattiasgeniar/varnish-4.0-configuration-templates
