### ISSUE TITLE
Problems with StructureNodes

### ISSUE THREAD

**Issue by wesleylancel** [Kunstmaan/KunstmaanBundlesCMS#701]
I'm currently using a few StructureNodes to group certain pages in the CMS. This works pretty good, however I've started running in to some issues. As a StructureNode doesn't have any NodeTranslations that are online, it'll be skipped by the getChildren in NodeMenu by default. As this function is used by the SitemapBundle and the SearchBundle, any children of StructureNodes will not be visible in the sitemap or be indexed for searching. Is there an existing work around for this? If not, how would I go about writing a solution?

**Comment by mlebkowski** [comment]
Yeah, I ran into this so I have a listener:

```php
<?php
use Kunstmaan\NodeBundle\Event\Events;
use Kunstmaan\NodeBundle\Event\NodeEvent;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;

class StructureNodeListener implements EventSubscriberInterface
{
    public function onNodeSave(NodeEvent $event)
    {
        $page = $event->getPage();
        if (false === $page->isStructureNode()) {
            return;
        }

        $node = $event->getNode();
        $nodeTranslation = $event->getNodeTranslation();

        $node->setHiddenFromNav(true);
        $nodeTranslation->setOnline(true);
        $nodeTranslation->setUrl('');
    }

    public static function getSubscribedEvents()
    {
        return [
            Events::PRE_PERSIST => 'onNodeSave',
            Events::ADD_NODE => 'onNodeSave',
        ];
    }
}
```

I believie this could be the default. I can prepare a PR with this in the future, but currently I’m a little swamped.

**Comment by roderik** [comment]
Seems like a good solution, a PR is welcome

**Comment by jverdeyen** [comment]
I think most of these "decisions" should be in listeners. As the default behaviour for adding paging will diverge from the fixtures' bundle behaviour. For example, the possible children check when adding a page should also throw an exception when using fixtures. My two cents ;-)

:+1:
