### ISSUE TITLE
View permissions not working as expected

### ISSUE THREAD

**Issue by henrypenny** [Kunstmaan/KunstmaanBundlesCMS#705]
If I set a role to have only view permissions on a page, that page is not visible in the admin.
I need to give the role permission to edit.

**Comment by evgemar** [comment]
yep, because view permission for the frontend and preview, not admin section

**Comment by henrypenny** [comment]
Can I make it a feature request to allow read only access to pages in the admin. We have a client who is operating in multiple countries and wants to give country level admins full access to sub-sections of the site and view only access to all pages.

**Comment by krispypen** [comment]
@henrypenny yes offcourse, looks like a useful feature!
