### ISSUE TITLE
Cannot save when required field hasn't been filled.

### ISSUE THREAD

**Issue by indrikenens** [Kunstmaan/KunstmaanBundlesCMS#730]
A checkbox that was required, wasn't checked.
When pressing the save button, instead of saving and returning an error, the page wouldn't save.
This was the error in the console: 
An invalid form control with name='form[pagepartadmin_534][external]' is not focusable.

**Comment by whitewhidow** [comment]
Are you trying this with the existing CheckboxPagePart ?    if so, i cannot seem to reproduce this.

It provides a proper error for me ...
