### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by rifer** [Kunstmaan/KunstmaanBundlesCMS#734]
After complete all the steps i type 

``` 
php app/console assetic:dump

```

and get this error:

```
06:40:00 [file+] /var/www/kunstmaan/app/../web/KunstmaanMediaBundleAssets/js/mediaFooter.min.js
[2015-10-02 06:40:00] app.ERROR: RuntimeException: Path to node executable could not be resolved. (uncaught exception) at /var/www/kunstmaan/vendor/kriswallsmith/assetic/src/Assetic/Filter/UglifyJs2Filter.php line 138 while running console command `assetic:dump` {"exception":"[object] (RuntimeException(code: 0): Path to node executable could not be resolved. at /var/www/kunstmaan/vendor/kriswallsmith/assetic/src/Assetic/Filter/UglifyJs2Filter.php:138)"} {"file":"/var/www/kunstmaan/vendor/kunstmaan/bundles-cms/src/Kunstmaan/AdminBundle/EventListener/ConsoleExceptionListener.php","line":28,"class":"Kunstmaan\\AdminBundle\\EventListener\\ConsoleExceptionListener","function":"onConsoleException"}
                                                  
  [RuntimeException]                              
  Path to node executable could not be resolved.  
 ```

I'm runing the framework on Linux Mint17.2~Ubuntu, Apache/2.4.7, ruby 1.9.3p484, gul 3.9.0,...

Thanks

**Comment by krispypen** [comment]
What is the answer of the command
```which node```
and
```node --version```
?

Or maybe you do not have nodejs yet?

**Comment by rifer** [comment]
I knew I was forgetting something

```
$ which node
/usr/bin/node
```
and

```
$ node -v
v0.12.7
```

**Comment by denbatte** [comment]
In ubuntu package manager there is an other package called node. So make sure that's not the one installed.

Try sudo apt-get install nodejs. Than change the path to the executable or symlink node to nodejs.

**Comment by krispypen** [comment]
It tries to load node from /usr/local/bin/node (I think because that is the default location on an OSX dev environments). But on linux it's default /usr/bin/node. That's why it's /usr/bin/node in all environments except config_dev.yml https://github.com/Kunstmaan/KunstmaanBundlesStandardEdition/blob/master/app/config/config_dev.yml

So for now this will do the trick:
```ln -s /usr/bin/node /usr/local/bin/node```

**Comment by wimvds** [comment]
Though it's probably easier to just change the config_dev.yml manually for your own projects.

**Comment by rifer** [comment]
Thanks all. I've changed the config_dev.yml as suggested @wimvds and after:
```
$ sudo npm -g install uglifyjs
$ sudo npm -g install uglifycss
```

Now it works right. In the other hand, I'm finding some inconsistences in the documentation. I have to add an sites-available file to run it, i mean. Meanwhile, in the documentation, just says, after the assetic:dump:

> At this point browsing to http://kunstmaan.cms/en/admin should greet you with the following screens.

Anyway, I'm closing this issue.
Thanks again

**Comment by rifer** [comment]
I must rectify. In the install documentation clearly specifies that assume it's a vagrant runing.
