### ISSUE TITLE
Dependency on kriswallsmith/spork made Kunstmaan >3.2 not usable on some systems. 

### ISSUE THREAD

**Issue by aistis-** [Kunstmaan/KunstmaanBundlesCMS#745]
Hello, we cannot update Kunstmaan to 3.3 or newer because on dependency `"kriswallsmith/spork": "~0.2.0"`

Anyone have the same issue?

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for kriswallsmith/spork v0.2 -> satisfiable by kriswallsmith/spork[v0.2].
    - kriswallsmith/spork v0.2 requires ext-pcntl * -> the requested PHP extension pcntl is missing from your system.
  Problem 2
    - kriswallsmith/spork v0.2 requires ext-pcntl * -> the requested PHP extension pcntl is missing from your system.
    - kunstmaan/bundles-cms 3.4.0 requires kriswallsmith/spork ~0.2.0 -> satisfiable by kriswallsmith/spork[v0.2].
    - Installation request for kunstmaan/bundles-cms 3.4.0 -> satisfiable by kunstmaan/bundles-cms[3.4.0].
```

**Comment by roderik** [comment]
You need to install the pcntl php extension, i'll add it to the requirements file

**Comment by aistis-** [comment]
The problem is that we cannot update software in some of servers. Is there any Composer config parameters which allows to ship this **particular** `pcntl` extension?

**Comment by roderik** [comment]
That's an issue indeed. I've moved the Spork dependency to the StandardEdition, since it's more of an application improvement than a dependency. Use dev-master for now to fix this.

**Comment by aistis-** [comment]
Thanks!
