### ISSUE TITLE
[NodeBundle] "Hidden from menu" option is not language specific

### ISSUE THREAD

**Issue by yoshz** [Kunstmaan/KunstmaanBundlesCMS#799]
If you enable "Hidden from menu" on a node this will effect all translations of the node.
You would expect the same behavior as "Weight" which is specific for each translation.

**Comment by denbatte** [comment]
Although I understand your argument. This would be not an easy fix.
The behaviour is by design. The value to hide a node from the menu lives in the database node table. Not the node translation table. It would be a major braking change if this is changed.

**Comment by yoshz** [comment]
I think it is a design flaw, but only an issue for specific situations.
Although it isn't that big issue I think it is smart to solve this on long term.
It could be easily fix by writing a migration to preserve the data in a new major version.
