### ISSUE TITLE
[NodeBundle] Unable to only delete a translation and not the node

### ISSUE THREAD

**Issue by yoshz** [Kunstmaan/KunstmaanBundlesCMS#800]
When you think you delete a translation you delete the entire node and all other translations.
Rather buildin a check if a node has multiple translations only delete the current translation.

**Comment by yoshz** [comment]
@denbatte or @roderik  do you agree to add this behavior?
The user probably also expects a notice in the confirmbox that only the translation will be deleted.
I can probably create a pull request to solve this issue in the next few days.

**Comment by jockri** [comment]
I would ask the end user in the confirmation dialog that appears when you click the delete button.
"Do you want to delete the current page for all available languages or only for the current language?" And then 3 buttons: "Cancel", "Delete page in current language", "Delete page in all languages"

**Comment by jockri** [comment]
I have second thoughts about this. For the moment, when you delete a node, it is a soft delete (deleted set to 1 in the node table). When you want to delete only one node translation, you need to move that column to the node_translation, which will be a huge BC break. In most cases you also want to delete the page in the other language, if not, you can just unpublish the page that you want to put offline.
