### ISSUE TITLE
[NodeBundle] Display pagetype on the edit page of a node

### ISSUE THREAD

**Issue by yoshz** [Kunstmaan/KunstmaanBundlesCMS#802]
It is confusing sometimes that you can't see which pagetype a specific node has.
An easy fix is to display the name of the contenttype below the node name next to Public/Draft version on the edit page of a node.

**Comment by denbatte** [comment]
@yoshz If you hover over the title, the pagetype will be displayed.

**Comment by yoshz** [comment]
Well that isn't really intuitive :). 
Still think that a human readable string below the title is more user friendly.
I think the easiest solution is to lookup to description of the pagetype by using the childtypes of the parent node?

**Comment by mlebkowski** [comment]
I created a `PageConfiguration` bundle in #538. It provides a name for each pagetype, you could use that. 

There even is a twig extension, the only thing left is to add a `get_page_name` function: https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/538/files#diff-bd3ec64cc8bb451e094095fcb30a106fR1
