### ISSUE TITLE
[SeoBundle] Keywords are missing from SEO settings

### ISSUE THREAD

**Issue by yoshz** [Kunstmaan/KunstmaanBundlesCMS#803]
For some reason the keywords are removed from the SEO settings of a node by pull request #750.
What is the reason? Our customers still use this field?

**Comment by denbatte** [comment]
Keywords are not used by search services anymore.
See for example here: http://googlewebmastercentral.blogspot.be/2009/09/google-does-not-use-keywords-meta-tag.html

**Comment by yoshz** [comment]
Ok. I didn't see this change back in the changelog of 3.4.1, so it was a bit confusing for a couple of our users.

**Comment by yoshz** [comment]
I discussed it with our SEO experts. The keywords are not used for ranking as the article says, but still can be used to match content.
Why remove the keywords when it could still be relevant to some users?

**Comment by roderik** [comment]
Of you want i'll merge a PR that puts them back

**Comment by mlebkowski** [comment]
„SEO Experts” always claim everything matters :P

**Comment by denbatte** [comment]
I would love to see a source explaining the matching content.

**Comment by yoshz** [comment]
Removing the keywords will make this an opinionated design choose for the CMS. 
I have no real opinion about whether it is or not is used by searchengines from developer perspective. But I think you should let users decide them selfs.

**Comment by denbatte** [comment]
I propose making the SEOBundle extendable. 
This way everybody can add their own properties depending on the need of the project.

**Comment by yoshz** [comment]
I just created a pull request #855 to readd the keywords.
Regardless if you merge it back or not, you should update at least the changelog and mentioning the keywords are deleted in version 3.4, but also update the UPGRADE-3.4.md with this bc change!

My advise is whenever you make a choose to remove a feature from Kunstmaan CMS in the future to really communicate this. For some users it can have a huge impact.
