### ISSUE TITLE
Custom routes a certain page entity

### ISSUE THREAD

**Issue by virtualize** [Kunstmaan/KunstmaanBundlesCMS#804]
I've created an ArticlePage entity and want to prefix all frontend paths to it with a custom pattern. 
We need URLs like `/en/magazine/category/articles/article-slug` that are different to the position in the page node tree.
Any suggestions would be helpful. Thanks

**Comment by jockri** [comment]
Create a custom router where you can add these specific routes to the RouteCollection. Use the default slug controller as a resolver.
