### ISSUE TITLE
Delimit the text in text areas on their respes

### ISSUE THREAD

**Issue by WardBrems** [Kunstmaan/KunstmaanBundlesCMS#805]
![image](https://cloud.githubusercontent.com/assets/6450290/11033162/5d6ec4de-86e1-11e5-8f61-40a7402d93f0.png)

When a text field has a maximum amount of characters, is it possible to strip all pasted text to this number of characters? Afterwards it should not be possible to add any more text till the user deletes more characters.

**Comment by diskwriter** [comment]
@FVKVN  Can you include this kind of functionality in #899?

**Comment by diskwriter** [comment]
Should be fixed in #905
