### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by aistis-** [Kunstmaan/KunstmaanBundlesCMS#828]
Hello guys, do you have an official Roadmap what you are working on, what are planned and when it is planned? Something like Sylius have http://sylius.org/roadmap

**Comment by wesleylancel** [comment]
:+1: /cc @denbatte

**Comment by denbatte** [comment]
@roderik Maybe we could add such a thing to the bundles documentation?

**Comment by Perni1984** [comment]
+1

**Comment by aistis-** [comment]
Hey guys, any news? :)

@roderik @KunstmaanLabs

**Comment by jockri** [comment]
Yep, we should have a roadmap. For the moment there are not a lot of things planned. Below some big things we are going to work on:

v3.5.0
* Make sure all deprecations are gone (to be ready for SF 3.0)

v4.0.0
* Symfony 3.0

v4.x.x
* A general API to expose pages/pageparts/media/... so it can be uses by other platforms/apps/...

I will put this high level planning somewhere more visible. If you have suggestions for new features, or if you are working on something that you can share, please let us know.

**Comment by wesleylancel** [comment]
Thanks for sharing @jockri. Any chance #655 will be part of this?

**Comment by jockri** [comment]
I have updated the roadmap, and made it available via https://bundles.kunstmaan.be/documentation/contributing/roadmap

@wesleylancel We are thinking about rebranding the name of the CMS system, I'll keep you posted

**Comment by aistis-** [comment]
Hi @jockri, any news when v4 is expected?

**Comment by jockri** [comment]
@aistis- normally we will release this month. If you already want sf3 support, you can use the sf3 branch.

**Comment by aistis-** [comment]
@jockri cool, thanks
