### ISSUE TITLE
Search page generates missing node function

### ISSUE THREAD

**Issue by alexborton** [Kunstmaan/KunstmaanBundlesCMS#842]
The Search generator (as documented on the bundles website) includes a helper function: get_node_trans_by_node_id() that no longer exists. 

This seems like a very handy function as it will accept an id, rather than object and the results from the search are in the form of an array, including the translation id. 

Is there a reason this was removed? Can we have it back? Is there an alternative?

**Comment by wesleylancel** [comment]
The function is in the default site that the `GeneratorBundle` generates, you should be able to copy it from there: https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Twig/NodeTranslationTwigExtension.php.

I agree though that it might be useful to have it in the default twig extension.

**Comment by alexborton** [comment]
Thanks @wesleylancel, thats perfect.

**Comment by wouterv55** [comment]
@alexborton @wesleylancel I am working on it, soon you will be able to find it back in the default twig extension. Thanks for pointing this out.
