### ISSUE TITLE
[NodeBundle] Route '_slug' not found': You cannot generate a url from a redirect []

### ISSUE THREAD

**Issue by Perni1984** [Kunstmaan/KunstmaanBundlesCMS#866]
I have a lot (15+) messages like these in my production logs:

```
app.DEBUG: Router Kunstmaan\RedirectBundle\Router\RedirectRouter was unable to generate route.
Reason: 'Route '_slug' not found': You cannot generate a url from a redirect [] 
{"file":"/home/vagrant/vendor/symfony-cmf/routing/ChainRouter.php","line":236,
"class":"Symfony\\Cmf\\Component\\Routing\\ChainRouter","function":"generate"}
```

As I did not find a lot of documentation about the routing system in the nodeBundle, could eventually somebody more experienced with KumaCMS shed some light on how I can fix this?

**Comment by tentwofour** [comment]
I had the same issue, after migrating a site that had a lot of really 
old URLs that didn't match new ones, and didn't have proper redirects 
added. I believe It's part of the CMF router, if you change your 
production configuration's log settings from the default, adding in the 
action_level: error, they should disappear:

#/app/config/config_prod.yml

monolog:
     handlers:
         main:
             type:         fingers_crossed
             action_level: error
             handler:      nested


HTH.

On 27 December 2015 01:03:48 GMT-06:00, Christoph Pernsteiner 
<notifications@github.com> wrote:

    I have a lot (15+) messages like these in my production logs:

    |app.DEBUG: Router Kunstmaan\RedirectBundle\Router\RedirectRouter was
    unable to generate route. Reason: 'Route '_slug' not found': You
    cannot generate a url from a redirect []
    {"file":"/home/vagrant/vendor/symfony-cmf/routing/ChainRouter.php","line":236,"class":"Symfony\\Cmf\\Component\\Routing\\ChainRouter","function":"generate"}
    |

    As I did not find a lot of documentation about the routing system in
    the nodeBundle, could eventually somebody more experienced with
    KumaCMS shed some light on how I can fix this?

    —
    Reply to this email directly or view it on GitHub
    <https://github.com/Kunstmaan/KunstmaanBundlesCMS/issues/866>.

**Comment by Perni1984** [comment]
I understand, but this circumvents the "problem", if there is one. Eventually this is expected behaviour as I don't fully understand if it is "normal" that the generate() method of the RedirectRouter is called 15+ times during a page load and automatically throws a RouteNotFoundException. I would rather expect this happens 1 time during a page load, when there is no redirect for this particular page.

Can anybody shed some light on how the Router Internals work, or better the RedirectRouter of the RedirectBundle? I don't really understand why automatically a RouteNotFoundException is thrown (eventually this has to do with the standard symfony cmf implementation).
