### ISSUE TITLE
AdminList pagination does not work when clicking on first page link

### ISSUE THREAD

**Issue by mtnorthrop** [Kunstmaan/KunstmaanBundlesCMS#867]
When you have a multi-page AdminList and click on "Next" or a page higher than one, and then try to go back to page one by clicking "Previous" or the page one link in the pagination, you are again shown the most-recent page you were viewing instead of the first page, even though the URL is for the AdminList index without the "page" parameter.

For example, if your admin list is named "books" and you go to `/admin/books`, you are shown the first page of your books adminlist. If you then click on "Next" in the pagination, you are shown page 2 and your current URL is `/admin/books/?page=2`.

Now, if you click on "Previous" in the pagination, the URL is `/admin/books` again, but you're still shown the page 2 items.

It seems that this is being caused by the current page and filter data being stored in the session. When you return to the first page, and the URL does not contain a "page" parameter, the page number that you viewed most recently is taken from the session and displayed.

Is this a bug or am I the only one experiencing this?

**Comment by jockri** [comment]
This is indeed a bug.
