### ISSUE TITLE
[AdminList] Adding bulk actions to an adminlist prevents the delete button from working on the first item

### ISSUE THREAD

**Issue by mtnorthrop** [Kunstmaan/KunstmaanBundlesCMS#870]
When bulk actions are added to an AdminList, it causes the delete buttons for individual items to stop working.

It appears that this is due to the bulk action wrapping the whole list inside a form, and since forms can not be validly nested, the forms attached to the delete buttons are no longer recognized and clicking on the trash icon does nothing.

**Comment by whitewhidow** [comment]
seems to be working on master atm, what revision are experiencing this on,

Could you also paste a code sample of how you setup your bulkaction, i tested with the following code and it seems to be working fine (delete still works properly)

```php
    public function buildFields()
    {
        $bulkAction = new SimpleBulkAction(array('path' => 'acme_demo_path', 'params' => array()), 'bulk action title');
        $this->addField('title', 'Title', true);
        $this->addBulkAction($bulkAction);
    }
```

Thx

**Comment by mtnorthrop** [comment]
I'm using KunstmaanBundlesCMS version 3.4.2 (the one that's tagged as such for installation through Composer.)

This is a slightly edited version of my code for adding the action, in the configurator:

```
        $bulkPath = [
            'path' => 'my_bulk_action_path',
            'params' => ['param1' => $param1]
        ];
        $this->addBulkAction(new SimpleBulkAction($bulkPath, 'Bulk Delete', 'trash-o'));
```

The adminlist configurator has been heavily customized, so it is possible that the bug is in my own code, but the bulk action itself is working fine; it's the original "Delete" button that appears next to the first item in the adminlist that doesn't work.

I've just tested the adminlist delete buttons again, using Chrome and Firefox on Linux.

The delete button next to each adminlist item works properly for all the items, **except for the very first item at the top of the admin list**. The delete button for the first item in the list triggers the modal, but clicking the red "Delete" button inside the modal simply closes the modal without deleting the item.

I can see the delete form tags when viewing the page source in Firefox and Chrome, but they are **not** shown when inspecting the DOM through Chrome Developer Tools or through FireBug, which seems to indicate that these browsers see it as invalid HTML and have silently dropped it from their DOM structure.

When viewing the page source in Firefox, the form tags in the first item's delete modal are highlighted in red and Firefox gives this message: *"Saw a form start tag but there was already an active form element. Nested forms are not allowed. Ignoring the tag."*

If you're able to add a bulk action to your adminlist, and the delete button for the first item in your list still works, then this is probably a bug in my own code, and not in the AdminBundle. If that's the case, I'll close this ticket as invalid.

**Comment by whitewhidow** [comment]
you are correct, i had a list with 3 items, and had tested the removal of the first two, without actually trying the first item, indeed, the first item does not delete properly, am looking at it .

**Comment by whitewhidow** [comment]
this should solve the issue for now (moved thee delete forms outside of the other form) (not ideal, looping twice), can you verify.

thx

**Comment by mtnorthrop** [comment]
It looks like it's working now.

If this solution is not ideal, maybe an alternative would be to create a single modal and pass the ID of the item that needs deleting when the delete button is clicked.

There's an example of how to do this in the Bootstrap docs: http://getbootstrap.com/javascript/#modals-related-target

(I don't know whether this would work in the AdminBundle without any conflicts, but it seems to be an  option.)
