### ISSUE TITLE
How can I create a Structured Node in Backend

### ISSUE THREAD

**Issue by Perni1984** [Kunstmaan/KunstmaanBundlesCMS#872]
Hi,

as I have read about the possibilities to create structured nodes, to structure content, I was wonderin how I can create them in the backend?

Thanks.

Best,

Christoph

**Comment by denbatte** [comment]
You have to create the a new pagetype as structure node. Just as any other pagetype you add. After that you are able to add it in the back end just like other pages.

**Comment by Perni1984** [comment]
That was obvious - thanks for pointing out ;-)
