### ISSUE TITLE
Preselect a field value of a PagePart, depending on PageType where it is embedded

### ISSUE THREAD

**Issue by Perni1984** [Kunstmaan/KunstmaanBundlesCMS#874]
I have a field called ```yachtModel``` on my ```YachtPage``` Pagetype. I have a Pagepart called ```YachtGallery```, which also has a field ```yachtModel```.

Now, whenever I would add a ```YachtGallery``` Pagepart to a ```YachtPage``` I would like to ensure that the default field value of the PagePart corresponds to the current field value of the ```YachtPage```. How would I best go about this?

**Comment by denbatte** [comment]
I would personally make an entity (adminlist) of yachts and select one of those on your yachtpage. You can choose that same yacht in your pagepart. 

I'm not sure how to handle the default value but I know its possible. @jockri ? :)

**Comment by Perni1984** [comment]
sorry, I forgot to mention this, this is exactly how it is setup now. 

I have an Entity (Adminlist) `YachtModel`, which basically contains all relevant infos (technical data about the yacht, link to the relevant media folders to display the photos for the gallery). The fields in the `YachtPage` aswell as the field in the `YachtGallery` Pagepart link to this `YachtModel` entity. There are also other PageParts on the `YachtPage` with fields that link to the same `YachtModel` entity.

For end-user convenience I would like to ensure that the default `YachtModel` chosen in those PageParts is the same as the currently selected `YachtModel` of the `YachtPage`. I suppose I would have to use an `AddPagePartListener` or something similar, that grabs the currently selected `YachtModel` of the Page and puts this as default for the added PagePart.

**Comment by mlebkowski** [comment]
leave it blank on the PagePart as default, then in your pagepart view twig:

```twig
{# resource refers to the pagepart, but you have access to current page as well #}
{% set yachtModel = resource.yachtModel | default(page.yachtModel) %}
```

Looks good?

**Comment by jockri** [comment]
@mlebkowski That is indeed a good and simple solution.

**Comment by Perni1984** [comment]
sorry, I were some days off now. @mlebkowski thanks for the solution it works perfectly!
