### ISSUE TITLE
Access Pagetype instance in custom controller

### ISSUE THREAD

**Issue by Perni1984** [Kunstmaan/KunstmaanBundlesCMS#877]
I created a `YachtPage` Pagetype and associated a custom controller `YachtPageController` with an `index` action. My `Yachtpage` has some fields I need to access inside my `YachtPageController:index` action. How can I access the current `YachtPage` instance inside the `YachtPageController`?

**Comment by Perni1984** [comment]
ok, I figured it out myself, but I think it could be useful for somebody having the same issue.

In a custom Controller you can get the current Page (e.g. the entity implementing the `SlugActionInterface`) via:
```
$currentPage = $request->attributes->get('_entity');
```

**Comment by kimausloos** [comment]
Generally these will be injected:

https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/src/Kunstmaan/NodeBundle/EventListener/RenderContextListener.php#L66-L71

FYI, you can also call {{ dump() }} in twig and see all variables you currently have in scope in your twig file.
