### ISSUE TITLE
When selecting a piece of text on Safari/yosemite in the ckeditor, the pagescrolls to the bottom

### ISSUE THREAD

**Issue by roderik** [Kunstmaan/KunstmaanBundlesCMS#902]

**Comment by FVKVN** [comment]
Can't reproduce, @roderik can you provide an example?

**Comment by roderik** [comment]
I've demonstrated it to several ppl, including @VickyDeschrijver i believe

**Comment by dbeerten** [comment]
Not reproducible. @diskwriter Close this one?
