### ISSUE TITLE
Generating demosite - When doing doctrine:schema:create -> gives error

### ISSUE THREAD

**Issue by VickyDeschrijver** [Kunstmaan/KunstmaanBundlesCMS#922]
When you want to do action: app/console doctrine:schema:create; you get an error. The second time you try the same command, it works.

**Comment by VickyDeschrijver** [comment]
![screen shot 2016-01-20 at 15 59 12](https://cloud.githubusercontent.com/assets/9945442/12452478/e16c7566-bf8e-11e5-96b0-ddf35745de5d.png)

**Comment by sandergo90** [comment]
Can't reproduce this issue. I think it's because you had en existing database, correct ?
