### ISSUE TITLE
Shell helper doesn't work on Mac OSX

### ISSUE THREAD

**Issue by henrypenny** [Kunstmaan/KunstmaanBundlesCMS#931]
I'm on OSX 10.10.5 and the Shell helper isn't working as expected.

I've removed `nohup` from:

`vendor/kunstmaan/bundles-cms/src/Kunstmaan/UtilitiesBundle/Helper/Shell/Shell.php:22`

and this solves it for my setup. Is there a good way to detect if its running on Mac and put a switch in place?

**Comment by mlebkowski** [comment]
You can override this utility in your application.

```
class OsxShellHelper extends Shell {
    public function runInBackground($command, $priority = 0) {
       // custom logic
    }
}
```

And in your `config.yml`:

```
parameters:
   kunstmaan_utilities.shell.class: OsxShellHelper
```

**Comment by whitewhidow** [comment]
perhaps we can check if nohup is present on the system, by dong something like this:

        $try = shell_exec("nohup date");
        if ($try !== null) {
            //nohup is working 
        } else {
            //nohup is not working
        }

**Comment by henrypenny** [comment]
@whitewhidow 
Feature detection might be a little more robust?

**Comment by whitewhidow** [comment]
@henrypenny what exactly do you mean by 'Feature detection' ?

**Comment by henrypenny** [comment]
As per your suggested solution: testing whether a given feature (`nohup`) is available as opposed to assuming that OSX doesn't have it. Might there be other OSs without `nohup`?

**Comment by wesleylancel** [comment]
It seems my OSX does have nohup. Maybe just test with `which nohup`?

**Comment by whitewhidow** [comment]
yep that seems like a nice solution ..

**Comment by kimausloos** [comment]
The use of ```which``` for this kind of thing should be avoided for various reasons, there are alternatives though: http://stackoverflow.com/a/677212

**Comment by delboy1978uk** [comment]
Maybe use `is_executable()` ? http://jp.php.net/manual/en/function.is-executable.php

**Comment by delboy1978uk** [comment]
We don't need `nohup`. If we use `popen()` or `proc_open()` to run the command, then the process is *already* backgrounded :-)
http://php.net/manual/en/function.popen.php 
http://php.net/manual/en/function.proc-open.php

**Comment by Numkil** [comment]
The problem should be resolved in master branch. Instead of using shell_exec we are now using the Symfony Process object. Process does use proc_open as mentioned in the above comment. This completely negates the necessity for nohup and removes any platform specific code.
