### ISSUE TITLE
Backend Module pagination is incorrect for index page

### ISSUE THREAD

**Issue by alexborton** [Kunstmaan/KunstmaanBundlesCMS#960]
The module pagination in the backend seems to be trying to retrieve the index (or, page 1) from the session, instead of going straight to the first page. 

If i go to the 2nd page (in the blog, say) and then click **Previous** or **1**, i am taken back to the current page, but the URL does change to the index. Similarly, if i then leave the module and return, i am back on the page number i selected, not page 1. 

Currently, the only way for the user to get to page 1 is to manually change the URL (?page=1)

**Comment by whitewhidow** [comment]
i believe this was fixed here   https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/879

**Comment by alexborton** [comment]
Looks like you are correct, @whitewhidow but will have to wait for 3.5! Thanks.
