### ISSUE TITLE
Error when adding YouTube video from admin

### ISSUE THREAD

**Issue by wesleylancel** [Kunstmaan/KunstmaanBundlesCMS#978]
`Variable "imageurlretina" does not exist in /vendor/kunstmaan/bundles-cms/src/Kunstmaan/MediaBundle/Resources/views/Folder/show.html.twig at line 228`

**Comment by sandergo90** [comment]
Good catch. I've added a pull request for this. Will be merged soon.

**Comment by wesleylancel** [comment]
Thx!
