### ISSUE TITLE
Improve default site generator fixtures to handle non EN locales

### ISSUE THREAD

**Issue by roderik** [Kunstmaan/KunstmaanBundlesCMS#98]
We've hardcoded the fixtures, see https://github.com/Kunstmaan/KunstmaanBundlesStandardEdition/issues/84

**Comment by jockri** [comment]
We generate pages for all languages defined in the parameters.yml
https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/DataFixtures/ORM/DefaultSiteGenerator/DefaultSiteFixtures.php#L116
