### ISSUE TITLE
MenuBundle menu_entity configuration not fully supported

### ISSUE THREAD

**Issue by henrypenny** [Kunstmaan/KunstmaanBundlesCMS#998]
Changing the menu_entity configuration doesn't fully work.

Eg.

`vendor/kunstmaan/bundles-cms/src/Kunstmaan/MenuBundle/Service/MenuService.php:50 : `

`$menuObjects = $this->em->getRepository('KunstmaanMenuBundle:Menu')->findAll();`

And

`vendor/kunstmaan/bundles-cms/src/Kunstmaan/MenuBundle/Service/MenuService.php:63`

`$menu = new Menu();`

**Comment by jockri** [comment]
Indeed, this should be changed. Can you send a PR to fix this?
